kyma-project/busola

resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml

Bump resources images

---

core-ui/src/components/Lambdas/constants.js
core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js

- https://github.com/kyma-project/kyma/issues/10752
https://github.com/kyma-project/kyma/issues/10752

Deprecate Node.js 10 runtime

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
core-ui/src/components/Lambdas/gql/hooks/mutations/useCreateLambda.js
core-ui/src/components/Lambdas/helpers/misc/useLogsView.js
core-ui/src/components/Predefined/List/Function/Functions.list.js
resources/backend/deployment.yaml
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceModal/CreateInstanceModal.component.js
service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInstancesTable/ServiceClassInstancesTable.component.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/test/ServiceInstanceInfo.test.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceRowRenderer.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.component.js
service-catalog-ui/src/components/ServiceInstanceList/test/ServiceInstanceList.test.js
shared/hooks/navigate.js

- Remove `cmf-` prefix from navigation stuff
- Bump images

Purge cmf- prefix

---

core-ui/src/components/Predefined/Details/ConfigMap.details.js
core-ui/src/components/Predefined/Details/index.js

Add Config map details view

---

core-ui/src/components/Predefined/Details/OAuth2Clients/OAuth2Clients.details.js
core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.scss
core-ui/src/components/Predefined/Details/OAuth2Clients/common.js
core-ui/src/components/Predefined/Details/index.js
resources/web/deployment.yaml

Add detail for oauthclients

---

core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml

Git repositories shouldn't have a details view

---

core/src/luigi-config/navigation/navigation-data-init.js
core/src/luigi-config/navigation/static-navigation-model.js
package-lock.json

- Remove 'download kubeconfig' option

Remove 'download kubeconfig' option

---

core-ui/src/components/Predefined/List/Deployments.list.js
core-ui/src/components/Predefined/List/index.js
shared/components/GenericList/GenericList.scss

- Add more data to deployments list

Add more data to deployments list

---

core-ui/src/components/Predefined/List/OAuth2Clients.list.js
core-ui/src/components/Predefined/List/index.js
resources/web/deployment.yaml
shared/components/ResourcesList/ResourcesList.js

- Add new columns for oauth clients lists
- ...
- ...

Add new columns for oauth clients lists

---

core-ui/src/components/Predefined/List/Services.list.js
core-ui/src/components/Predefined/List/index.js
resources/web/deployment.yaml

- Add new columns for services lists
- ...
- ...

Add new columns for services lists

---

core-ui/src/components/Predefined/List/Function/Functions.list.js
resources/web/deployment.yaml

- Add new columns for functions lists
- ...
- ...

Add new columns for functions lists

---

core-ui/src/components/Predefined/List/ApiRules.list.js
core-ui/src/components/Predefined/List/OAuth2Clients.list.js
core/src/luigi-config/navigation/static-navigation-model.js
shared/components/ResourcesList/ResourcesList.js
shared/components/ResourcesList/helpers.js

Fix list titles

---

core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
resources/web/deployment.yaml

- Use the same notification for oauth clients
- ...
- ...

Use the same notification for oauth clients

---

shared/hooks/BackendAPI/useGet.js

- Adjust `useSingleGet` to use new headers format

Fix application connecting

---

core-ui/src/components/Predefined/Details/ApiRules.details.js
core-ui/src/components/Predefined/List/Services.list.js
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml

- Clean up navigation structure
- minor fixes
- ...
- ...

Clean up navigation structure, minor fixes

---

core-ui/src/components/Predefined/Details/DeploymentPods.js
core-ui/src/components/Predefined/Details/Replicaset.details.js
resources/web/deployment.yaml

Add links to pods details

---

core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
resources/web/deployment.yaml

- Unify notifications for the deployment creation
- ...
- ...

Unify notifications for the deployment creation

---

core-ui/src/components/App/App.js
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml
shared/components/ResourceDetails/ResourceDetails.js
shared/components/ResourcesList/ResourcesList.js

- Make roles and read only
- Remove cluster Service Brokers view (was removed before but then accidentally added while resolving conflicts)

Make roles read only, remove cluster Service Brokers view

---

core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
core-ui/src/components/Predefined/Create/Deployments.create.js
core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.create.js
core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
core-ui/src/components/Predefined/Create/index.js
core-ui/src/components/Predefined/List/Application/CreateApplicationModal.js
resources/web/deployment.yaml
shared/components/ModalWithForm/ModalWithForm.js

- Add deployment modal
- Unify notifcation usage across the `Create` components

Add deployment modal, unify notifications

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ApiRules/ApiRules.js
core-ui/src/components/Predefined/Details/Pod/Pod.details.js
core-ui/src/components/Predefined/Details/Service/Service.details.js
resources/web/deployment.yaml

- Add "expose service" to service details
- Cleanup Pod details code

Expose service

---

core-ui/src/components/Predefined/List/LimitRanges.list.js
core-ui/src/components/Predefined/List/ResourceQuotas.list.js
core-ui/src/components/Predefined/List/index.js
resources/web/deployment.yaml

Add more info to resourceQuotas and limitRanges

---

core/nginx/nginx.conf
resources/backend/deployment.yaml
resources/backend/hpa.yaml
resources/backend/kustomization.yaml
resources/web/deployment.yaml
resources/web/hpa.yaml
resources/web/kustomization.yaml

We introduce HPA to scale up our workloads

introducing HPA

---

core-ui/src/components/Predefined/Details/Namespace/Namespace.details.js
core-ui/src/components/Predefined/List/Events.list.js
core-ui/src/components/Predefined/List/index.js

- Add warning events list to the namespace details
- ...
- ...

Add warning events list to the namespace details

---

core/src/luigi-config/init-params.js

- as in title, switch from lzstring to lzma in saveInitParamsIfPresent

Switch to LZMA

---

resources/web/deployment-service-catalog.yaml
service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js

Fix plan selection

---

.github/pull-request-template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

- Changed `master` to `main` in docs.
See also #https://github.com/kyma-project/community/issues/515

Change master to main

---

resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml

bump images to the latest tag from master

---

core-ui/Dockerfile
core/Dockerfile
logging/Dockerfile
service-catalog-ui/Dockerfile

- third-party-images repo was moved and docker paths adjusted, so updating to the latest version for the busola base image
- ...
- ...
https://github.com/kyma-project/third-party-images/pull/75

updated to newest docker base image to adapt new path structure

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal/CreateServiceBindingForm.js

- Fix displaying bindings if secret not present
- Don't allow creating binding for not bindable instance
- Use usageKind.metadata.name instead of usageKind.spec.resource.kind

Fix displaying bindings if secret not present

---

resources/web/deployment-service-catalog.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceDetails.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
service-catalog-ui/src/shared/ServiceInstanceStatus.js

- Sometimes, after instance creation the status is not yet present - added a check for that.
- While creating an instance (SAP Commerce Cloud - Inbound OMM StockLevel), some required data wasn't there, resulting in call for `/...serviceinstances.../undefined` - now we skip this call until all needed information is here.

Fix minor Catalog bugs

---

resources/web/deployment-service-catalog.yaml
service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
service-catalog-ui/src/helpers/index.js

…e tab
- Add serviceClass labels to instance
- check metadata.labels to determine tab

Show instances in correct tab

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
resources/web/deployment-service-catalog.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceDetails.js

Check both plan and class for spec.bindable

---

resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml

Bump images with namespace-overview

---

core/src/assets/login.js
core/src/login.html
core/src/luigi-config/auth.js
resources/web/deployment.yaml

Make login prettier

---

core/src/luigi-config/navigation/navigation-data-init.js
core/src/luigi-config/navigation/queries.js
core/src/nopermissions.html

- propagate full response object so that error message could be propagated to `nopermissions` page

403  error message propagation

---

core/src/assets/login.js
core/src/login.html

Fix login flow with no token

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
core-ui/src/components/Lambdas/LambdasList/Repositories/RepositoryForm.js
core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
core-ui/src/components/Predefined/List/Application/CreateApplicationModal.js
core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionForm.js
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/ModalWithForm/ModalWithForm.js

- Make ModalWithForm submit event cancellable.
- Add type="button" on buttons in AddonsConfiguration form, so that these buttons don't act as "submit".
- Prevent defaulted form submit in some ModalWithForm forms.

Fix FF bugs

---

core/src/luigi-config/communication.js
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/hooks/BackendAPI/checkForTokenExpiration.js

Refresh page when token is about to expire

---

core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
core-ui/src/components/Lambdas/config.js
core-ui/src/components/Lambdas/constants.js
core-ui/src/components/Lambdas/helpers/runtime/runtime.js
core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
core-ui/src/components/Lambdas/hooks/useCreateLambda.js

Remove node10 add node14

---

resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/GenericList/SearchInput.js

Fix searching

---

core/src/luigi-config/communication.js
core/src/luigi-config/luigi-config.js
core/src/luigi-config/settings.js
resources/web/deployment.yaml

- I decided not to use "Kyma" prefix in title, as we have this Kyma favicon, haven't we?

Bring back window title

---

core-ui/src/components/App/App.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/RepositoryConfig/RepositoryConfig.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.js
core-ui/src/components/Lambdas/components/ResourceNameInput/ResourceNameInput.js
core-ui/src/components/Lambdas/hooks/useUpdateLambda.js
core-ui/src/components/ModalWithForm/ModalWithForm.js
core-ui/src/shared/helpers/getResourceUrl.js
core-ui/src/shared/helpers/index.js
resources/web/deployment.yaml

- It looks like `selfLink` of Function doesn't work anymore - grab the `resourceUrl` manually.
- It's `MessageStrip`, not `FormMessage`
- It's `transparent` Button, not `light`

Fix function create, update & Fundamental warnings

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/RepositoryConfig/RepositoryConfig.js
resources/web/deployment.yaml

- Add gap between columns on git repositories function view

Add gap between columns

---

core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
core-ui/src/components/Predefined/Create/Secrets/SecretForm.js
core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
core-ui/src/components/Predefined/Details/Secret/Secret.details.js
core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
shared/components/KeyValueForm/KeyValueForm.js
shared/components/LabelSelectorInput/LabelSelectorInput.js
shared/components/LabelSelectorInput/LabelSelectorInput.scss
shared/components/ResourceDetails/ResourceDetails.js
shared/hooks/navigate.js

Redirect user to namespace list after a namespace was deleted from its details view. Also, do some minor visual fixes.
- ...
- ...
- ...

Namespace delete redirect

---

core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/JwtDetails/JwtDetails.js
core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.js
core-ui/src/components/Predefined/Details/Roles/Rules.js

- Fix spacing on role/clusterRole details spacing 
- Fix spacing on ApiRules -> AccessStrategy -> JWT

Fix clusterRole spacing and ApiRules JWT spacing

---

resources/web/deployment.yaml
shared/components/ResourcesList/ResourcesList.js
shared/components/ResourcesList/ResourcesList.scss

Add pointer cursor to the link on the generic list

---

core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.js

- Bring back the grid so fields are adjusting to screensize
- Add margin bottom between checkboxes

Make access strategies inputs bigger

---

shared/utils/randomNamesGenerator/words.js

- Remove `master` from the `word.js` file
See also https://github.com/kyma-project/community/issues/5153

Remove one leftover

---

core-ui/src/components/Predefined/Details/Application/Application.details.js
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/GenericList/GenericList.scss
shared/components/GenericList/SearchInput.js

- Use `Menu` instead of non-existing class, adjust CSS.
- ALSO remove duplicated application labels on details view.

Fix search suggestion styles

---

core/src/luigi-config/auth/auth.js
core/src/luigi-config/init-params.js
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml

Fix modules for init params

---

tests/package-lock.json
tests/package.json

move cypress to optional dependency

---

backend/Dockerfile
core-ui/Dockerfile
logging/Dockerfile
service-catalog-ui/Dockerfile

- Fix for CVE-2021-30139 HIGH (7.5) vulnerability

Upgrade alpine to 3.13.5 version

---

backend/index.js
resources/backend/deployment.yaml

Set higher limits to the requests

---

core/src/luigi-config/navigation/navigation-helpers.js
resources/web/deployment.yaml

Return empty arrays instead of undefined in external links

---

core-ui/src/components/Lambdas/hooks/createLambdaInput.js
core-ui/src/components/Lambdas/hooks/useCreateLambda.js
resources/web/deployment.yaml

- Remove resources, buildResources and replicas from fn create input
- Remove some unused code

Remove function preset values

---

core-ui/src/components/App/App.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.scss
core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/NodeDetails.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/useNodesQuery.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverview.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
core-ui/src/components/Predefined/List/Events.list.js
core-ui/src/shared/constants.js
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/CircleProgress/CircleProgress.js
shared/hooks/BackendAPI/useGet.js

Cluster overview

---

core-ui/src/components/Clusters/components/KubeconfigTextArea/KubeconfigTextArea.js
core-ui/src/components/Clusters/components/KubeconfigUpload.js
core-ui/src/components/Clusters/shared.js

Deep merge params

---

resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml

Bump resources images in deployments

---

resources/web/deployment.yaml

Fix web deployment

---

tests/cypress.json

- Enable videos recording for Cypress tests
https://github.com/kyma-project/test-infra/pull/3681

Enable videos recording for Cypress tests

---

backend/package-lock.json
package-lock.json
resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/package-lock.json
tests/support/login.js
tests/tests/busola-create-a-configuration-resources.spec.js
tests/tests/busola-create-a-deployment.spec.js

- regenerate package-locks
- add step: "go to namespaces list" in tests

Whitesource package update

---

resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/GenericList/GenericList.js

- If `searchPhrase` changes, move back to first page (as before)
- If an entry on the last page has been deleted, move back to the last page

Fix pagination on polling

---

tests/support/login-commands.js
tests/tests/create-configuration-resources.spec.js
tests/tests/smoke-tests.spec.js

Enable smoke tests for namespace details

---

core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
shared/components/GenericList/SearchInput.js

Use highlighted search on the Logs view

---

CODEOWNERS
tests/cypress.json
tests/tests/test-cluster-overview.spec.js

- Test cluster overview view
- Test node details view

Test cluster overview

---

resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml

Bump images to newest versions

---

tests/tests/run-before.spec.js

Create screenshots folder for every Cypress run

---

resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/hooks/navigate.js
tests/cypress.json
tests/tests/create-a-deployment.spec.js

Fix navigation to pods details

---

tests/tests/run-before.spec.js

Don't make screenshot at tests start

---

.github/ISSUE_TEMPLATE/documentation-improvement.md
.github/ISSUE_TEMPLATE/security-vulnerability.md
.github/pull-request-template.md
CONTRIBUTING.md
NOTICE.md
package-lock.json
package.json
tests/README.md

Update README for Cypress tests and fix md linter

---

core-ui/src/components/Predefined/Details/DeploymentPods.js
resources/web/deployment.yaml

- Get proper replica set to filter pods

Get proper replica set to filter pods

---

tests/tests/login-enkode.spec.js

Fix getting namespace from config in tests

---

core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.scss
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/RepositoryConfig/RepositoryConfig.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.js
core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
core-ui/src/components/Predefined/Details/Pod/ContainersData.js
core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/KeyValueForm/KeyValueForm.js
shared/components/KeyValueForm/KeyValueForm.scss

Functions configmaps UI

---

core-ui/src/components/Predefined/Details/Deployment.details.js
core-ui/src/components/Predefined/Details/DeploymentPods.js
resources/web/deployment.yaml

- Filter pods by deployment.spec.selector.matchLabels

Fix deployments

---

resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/LabelSelectorInput/LabelSelectorInput.scss

Remove outline from the labels input

---

resources/web/deployment.yaml
shared/components/GenericList/GenericList.scss

Fix application mapping edit button

---

core/package-lock.json
core/package.json

- Fix WhiteSource vulnerability in glob-parent-3.1.0

Move copy-webpack-plugin to devDependencies

---

resources/backend/deployment.yaml
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/package.json

Fix shared build

---

backend/package-lock.json
backend/package.json
resources/backend/deployment.yaml

- Fix for CVE-2021-25950 HIGH (8.2) WhiteSource vulnerability

Remove webpack-merge from dependencies

---

resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/ResourcesList/ResourcesList.js
tests/tests/in-cluster-eventing.spec.js

- Use Function built in logs button in tests
- Remove the unwanted `expand labels` feature on compact lists
- ...

Use Function built in logs button in tests

---

resources/web/ingress--single.yaml
resources/web/ingress.yaml

- add annotation to ingress to redirect http traffic to https
- ...
- ...

force the ingress to use https

---

tests/package-lock.json
tests/package.json

- Upgrade Cypress to 7.6.0 version
- Upgrade cypress-file-upload to 5.0.8 version

Upgrade Cypress to 7.6.0 version

---

core/src/luigi-config/luigi-config.js
core/src/luigi-config/navigation/previous-location.js
resources/web/deployment.yaml

Fix bad OIDC cluster redirection

---

core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
resources/web/deployment.yaml

Add color coding to CRD schema

---

core/src/luigi-config/auth/auth.js
core/src/luigi-config/cluster-management.js
resources/web/deployment.yaml

Fix removing active cluster

---

core-ui/src/shared/components/EventSubscriptions/createSubscriptionInput.js
resources/web/deployment.yaml

[Why?](https://github.com/kyma-project/kyma/issues/11509)

Remove unnecessary fields from subscription CR

---

core-ui/src/components/Lambdas/config.js
core-ui/src/components/Lambdas/constants.js
core-ui/src/components/Lambdas/helpers/runtime/runtime.js
core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
resources/backend/deployment.yaml
resources/web/deployment.yaml

Add python39 runtime
- Add python39 runtime
https://github.com/kyma-project/kyma/issues/11299

Add python39 runtime

---

tests/README.md

Link causes "404 not found" error.
- Fix dead link causing governance job to fail

Fix dead link causing governance job to fail

---

package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml
shared/package-lock.json
shared/package.json

- Upgrade Fundamental Library Styles & Luigi

Upgrade Fundamental Library Styles & Luigi

---

resources/web/deployment.yaml
shared/components/GenericList/GenericList.js
shared/components/GenericList/GenericList.scss
shared/components/GenericList/components.js
shared/components/ResourcesList/ResourcesList.js
shared/contexts/YamlEditorContext.js

- ...
- ...
- ...
Resolves #268

Display a selected state for list items being edited

---

core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
core-ui/src/components/Predefined/Create/OAuthClients/CheckboxFormControl.js
core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
core-ui/src/components/Predefined/Details/Application/ConnectApplicationModal.js
core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
core-ui/src/components/Predefined/Details/DeploymentPods.js
core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/ScalingData.js
core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
core-ui/src/components/Predefined/Details/Secret/Secret.details.js
core-ui/src/shared/components/EventSubscriptions/createSubscriptionInput.js
resources/backend/deployment.yaml
resources/web/deployment.yaml
shared/components/Modal/Modal.js
shared/components/ModalWithForm/ModalWithForm.js
shared/components/ResourceDetails/ResourceDetails.js

Resolves #267 
About the "cancel" options - it doesn't make sense on each and every modal, so I left that one out.

Make sure we mark mandatory fields

---

tests/package-lock.json
tests/package.json

Upgrade Cypress to 7.7.0 version

---

resources/web/deployment.yaml
shared/components/LabelSelectorInput/LabelSelectorInput.js
shared/components/StringInput/StringInput.js

- Remove custom validation tooltip: "Please match the requested format"

Remove custom validation tooltip

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
core-ui/src/components/Predefined/Details/ApiRules.details.js
resources/web/deployment.yaml

- We need data from plan / clusterPlan and serviceClass / clusterServiceClass to determine if serviceInstance is bindable
- add missing key on apirules view

Fix create service binding

---

backend/common.js
core-ui/src/components/Predefined/Details/Namespace/NamespaceWorkloads/NamespaceWorkloads.js
resources/backend/deployment.yaml
resources/web/deployment.yaml
shared/contexts/YamlEditorContext/EditorActions.js
shared/contexts/YamlEditorContext/YamlContent.js

- Fail immediately if headers in backend request are wrong
- Fix YAML drawer search

Fail fast on invalid headers & fix search in Monaco

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
resources/web/deployment.yaml

- Fix application crush when there is no existing bindings

Fix application crush when there is no existing bindings

---

core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
core-ui/src/components/Lambdas/components/FormInput/FormInput.js
core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.js
core-ui/src/components/Lambdas/components/ResourceNameInput/ResourceNameInput.js
core-ui/src/components/Lambdas/constants.js
core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
resources/web/deployment.yaml
shared/components/Dropdown/Dropdown.js
shared/components/K8sNameInput/K8sNameInput.js
shared/components/LabelSelectorInput/LabelSelectorInput.js
shared/components/Tooltip/Tooltip.js

Remove the info icons

---

core-ui/src/components/Preferences/ThemeChooser.js
core/package-lock.json
resources/web/deployment.yaml

- Rename themes according to [Fiori Design Guidelines](https://experience.sap.com/fiori-design-web/theming/)

Rename themes according to Fiori Design Guidelines

---

tests/package-lock.json
tests/package.json

Upgrade Cypress to 8.0.0

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableForm/VariableForm.js
resources/web/deployment.yaml

Fix function environments edit

---

core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
resources/web/deployment.yaml

- Dialog: Create API Rule -> "Access Strategies" field -> Please fill in this field [with yellow icon!] -> different tooltip appears if field is empty

Remove different tooltip for Access Strategies

---

core-ui/src/components/Preferences/ThemeChooser.js
core-ui/src/index.scss
core/src/luigi-config/utils/theme.js
resources/web/deployment.yaml
shared/contexts/ThemeContext.js

- Rename and reorder themes in the dropdown (consulted with a Technical Writer)
- Make the light/dark theme default
- Remove the top border radius of the page header (there were some visible gaps which looked ugly in the dark mode)

Improve theme naming

---

core/src/luigi-config/settings.js
resources/web/deployment.yaml

- change collapse mode of the luigi menu

change collapse option

---

CODEOWNERS
core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
core/src/i18n/en.yaml
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassList/ServiceClassList.js
shared/components/K8sNameInput/K8sNameInput.js

- Move menu texts to i18n yaml file
- Improve tooltip text

Move menu texts to i18n yaml file

---

core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
resources/web/deployment.yaml
shared/contexts/NotificationContext.js

Automatically close success notifications

---

core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml

Fix translations for menu categories

---

core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml

Reorder Workloads menu

---

CODEOWNERS
OWNERS_ALIASES

Add qbalukom to CODEOWNERS instead of parostatkiem

---

Dockerfile.local

- A file was missing in backend. Fixed.

Fix local Busola Docker build

---

core/src/i18n/en.yaml
core/src/i18n/pl.yaml
resources/web/deployment.yaml
shared/components/ResourcesList/ResourcesList.js

- add luigi overlay when dialog is open
- add an information box when disabling confirmations

enable luigi backdrop and add info

---

Makefile

Add local and latest tag to local docker image

---

backend/package-lock.json
backend/package.json
resources/backend/deployment.yaml

- Fix for CVE-2021-32804 HIGH (8.2)
- Fix for CVE-2021-32803 HIGH (8.2)

Remove vulnerable npm package tar

---

core-ui/src/components/Predefined/List/Pod/Pods.list.js
core-ui/src/index.scss
core-ui/src/shared/components/CreateDeploymentForm/SimpleForm.js
core/src/i18n/en.yaml
resources/web/deployment.yaml
shared/components/K8sNameInput/K8sNameInput.js

Fix translations & create modal styles

---

core-ui/src/components/Preferences/Preferences.js
resources/web/deployment.yaml
shared/components/ResourcesList/ResourcesList.js
shared/hooks/useFeatureToggle.js

- fix invalid hook error in preferences

fix preferences and feature toggles

---

resources/backend/deployment.yaml
resources/backend/hpa.yaml

- Lately, Busola backend was frequently failing with OOM - bump its resources according to https://github.tools.sap/kyma/management-plane-config/pull/1122/files.

Bump backend resources

---

core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResources.details.js
resources/web/deployment.yaml
shared/components/ResourceDetails/ResourceDetails.js

Fix buttons translations for custom resources

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
resources/web/deployment.yaml

- Show Injected variables component only when catalog is present

Show Injected variables component only when catalog is present

---

Dockerfile
Dockerfile.local
backend/Dockerfile
backend/common.js
resources/backend/deployment.yaml
tests/tests/test-crds.spec.js

Upgrade alpine to 3.14.2 & improve backend logger

---

Makefile

Add cosign signing step

---

core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
resources/web/deployment.yaml

Enable access strategy test

---

core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResources.details.js
resources/web/deployment.yaml
shared/components/GenericList/GenericList.js
tests/tests/test-crds.spec.js

Fix Cypress test for CRDs

---

backend/common.js
backend/package-lock.json
backend/package.json
resources/backend/deployment.yaml

Add pino-http logger to the backend

---

core-ui/src/components/Predefined/Create/DNSEntries/AdvancedForm.js
core-ui/src/components/Predefined/Create/DNSEntries/CreateDNSEntryForm.js
core-ui/src/components/Predefined/Create/DNSEntries/SimpleForm.js
core-ui/src/components/Predefined/Create/DNSProviders/AdvancedForm.js
core-ui/src/components/Predefined/Create/DNSProviders/CreateDNSProviderForm.js
core-ui/src/components/Predefined/Create/DNSProviders/ProviderTypeDropdown.js
core-ui/src/components/Predefined/Create/DNSProviders/SimpleForm.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

Add i18n for DNS providers and entries

---

resources/web/deployment.yaml
shared/components/ResourceDetails/ResourceDetails.js
shared/components/ResourcesList/ResourcesList.js

- Don't remove status from code

Don't remove status from code

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
core-ui/src/components/Lambdas/helpers/lambdaVariables/test/serializeVariables.test.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

- Add owner reference to variables table

Add owner reference to variables table

---

core-ui/src/components/ApiRules/ApiRulesList/components.js
resources/web/deployment.yaml

- When api rule has simple host get data from gateway

When api rule has simple host get data from gateway

---

core-ui/src/components/Lambdas/constants.js
core-ui/src/components/Lambdas/helpers/lambdas/getLambdaStatus.js
core/src/i18n/en.yaml
core/src/i18n/pl.yaml
resources/web/deployment.yaml

- Recognise condition ( Running, Unknown, MinReplicasUnavailable ) as UNHEALTHY
https://github.com/kyma-project/kyma/issues/12005
https://github.com/kyma-project/kyma/pull/12110

Reflect min replicas unavailable as unhelthy function status

---

backend/index.js
resources/backend/deployment.yaml

- React on Ctrl+C when running busola in docker.

React on SIGINT

---

resources/web/deployment.yaml
shared/hooks/BackendAPI/useGet.js

- Changing the time range created one additional call, and the previous one was not cancelled properly 
- Timeout was created for each log stream, instead of each call
- ...

Cancel timeouts to not have multiple calls in the logs view

---

core-ui/src/components/Predefined/Create/Deployments/templates.js
resources/web/deployment.yaml

Fix server creation

---

core-ui/src/components/Predefined/Create/DNSProviders/DNSProviders.create.js
core-ui/src/components/Predefined/Create/Deployments/Containers.js
core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
core-ui/src/shared/ResourceForm/ResourceForm.js
core-ui/src/shared/ResourceForm/components/FormComponents.js
core-ui/src/shared/ResourceForm/components/Inputs.js
resources/web/deployment.yaml

tweak resource forms to add a few more convenience shortcuts

Resource form tweaks

---

backend/Dockerfile
resources/backend/deployment.yaml

- Fixes for openssl CVE-2021-3711 and CVE-2021-3712

Upgrade alpine to 3.14.2 version

---

core-ui/src/components/Predefined/Create/ServiceBindings/ServiceBindings.create.js
core-ui/src/components/Predefined/Create/ServiceInstances/ServiceInstances.create.js
resources/web/deployment.yaml

Fix translations for instance creation

---

backend/common.js
core/src/luigi-config/navigation/queries.js
resources/backend/deployment.yaml
resources/web/deployment.yaml
shared/hooks/BackendAPI/createHeaders.js

Move auth to custom header

---

core-ui/src/shared/components/CronJob/CronJobSchedule.js
resources/web/deployment.yaml
shared/contexts/ThemeContext.js

Fix crashing cronjobs view

---

core-ui/src/components/Predefined/Create/Certificates/SimpleForm.js
core-ui/src/components/Predefined/Details/Application/ServicesBoundModal.js
core-ui/src/index.scss
resources/web/deployment.yaml
shared/components/ResourcesList/ResourcesList.js
shared/components/ResourcesList/ResourcesList.scss

- Fix mouse cursor in the fd link class
- Fix class to className
- Add missing translation

Fix mouse cursor and translation

---

resources/ingress.yaml

as a security concerns we should disable CORS
- ...
- ...
- ...

disable CORS at the ingress level

---

.github/pull-request-template.md

Fix a dead link

---

tests/package-lock.json
tests/package.json

Upgrade Cypress to 8.5.0 version

---

backend/common.js
resources/backend/deployment.yaml

Don't send empty authorization header

---

core-ui/src/components/App/App.js
core-ui/src/components/Clusters/views/ClusterList.js
core-ui/src/components/Clusters/views/ClusterList.scss
core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
core/src/assets/config/config.json
core/src/i18n/en.yaml
core/src/luigi-config/cluster-management/clusters-storage.js
core/src/luigi-config/features.js
core/src/luigi-config/kubeconfig-id/constants.js
core/src/luigi-config/kubeconfig-id/kubeconfig-id.js
core/src/luigi-config/luigi-config.js
core/src/luigi-config/navigation/navigation-data-init.js
core/src/luigi-config/navigation/static-navigation-model.js
core/src/luigi-config/settings.js
core/src/luigi-config/utils/showAlert.js
resources/web/configmap.yaml
resources/web/deployment.yaml
tests/cypress.json
tests/tests/add-cluster-disabled.spec.js

- Make "Add Cluster" the feature
- Use common `showAlert` function in `core`
- Use _Clusters Overview_ for clusters list, not _Cluster Overview_.
- Swap `checkbox` with `Switch` on Gateway create modal.

Add Cluster as a feature

---

core-ui/src/components/Predefined/Create/ServiceBindings/ServiceBindings.create.js
resources/web/deployment.yaml

- Fix disabling of create button on create binding modal

Fix disabling of create button on create binding modal

---

core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml

- ...
- ...
- ...
https://github.com/SAP/fundamental-react/pull/1378

Fix ExternalResourceRef input

---

core-ui/src/components/Predefined/List/Services.list.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

add Service definition

---

core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
core-ui/src/components/Predefined/List/Application/Applications.list.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

- add defintion of Application and Addons Configuration
- ...
- ...

add integration components defintions

---

core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
core-ui/src/components/Predefined/List/ServiceBrokers.list.js
core/src/i18n/en.yaml
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassList/ServiceClassList.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceList.js

- add definition of Service Management items (Catalog, Instance, Broker)
- ...
- ...

add defintions of service management items

---

core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/tests/smoke-tests.spec.js

- change camelCase to natural language for CR components
- ...
- ...

use natural language for CR components

---

core-ui/src/components/Predefined/List/Namespaces.list.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

- add definition of Namespace component
- ...
- ...

add defintion to Namespace component

---

backend/utils/other.js
tests/package-lock.json
tests/package.json

- Upgrade Cypress to 9.0.0 version: https://docs.cypress.io/guides/references/changelog#9-0-0
Fixes #554

Upgrade Cypress to 9.0.0 version

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableForm/VariableModal.js
resources/web/deployment.yaml

Fix size of env variable modal

---

backend/index.js
resources/backend/deployment.yaml
tests/package-lock.json
tests/package.json

- Use node 14 for Busola and Cypress tests

Downgrade Cypress to 8.7.0

---

core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
resources/web/deployment.yaml
tests/cypress.json
tests/tests/test-cron-jobs.spec.js

- Added test for:
- create Cron Job,
- display information,
- edit details,
- Allowed edit for Cron Jobs.
Closes #562

Cronjobs test

---

core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
core-ui/src/components/Predefined/Create/Gateways/helpers.js
tests/cypress.json
tests/tests/test-gateways.spec.js

- Enable edit on gateways and test them.
Closes #551

Test gateways

---

backend/common.js
resources/backend/deployment.yaml

- pino-http autologging on on development and off on production

Change logs extensivity on production and development

---

resources/web/deployment.yaml
tests/cypress.json
tests/support/iframe-commands.js
tests/tests/test-statefulsets.spec.js

test stateful sets

---

core-ui/src/components/Predefined/Create/Certificates/Certificates.create.js
core-ui/src/components/Predefined/Details/Certificate/CertificateRefs.js
core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
core-ui/src/shared/components/Tokens.js
core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/cypress.json
tests/tests/certificates.spec.js

This update introduces test to the Certificates section
Closes #549

Add cypress tests for adding and deleting certificates

---

tests/tests/test-cluster-role-bindings.spec.js

Fix conflict of names.
- CRB_NAME with random number at the end
- ...
- ...

Repair client name in test

---

core-ui/src/shared/ResourceForm/useCreateResource.js
resources/web/deployment.yaml

fix ff form submit

---

core-ui/src/components/Predefined/Create/ServiceAccounts/ServiceAccounts.create.js
core-ui/src/components/Predefined/Create/ServiceAccounts/helpers.js
core-ui/src/components/Predefined/Details/ServiceAccount/GenericSecrets.js
resources/web/deployment.yaml
tests/cypress.json
tests/tests/test-cluster-role-bindings.spec.js
tests/tests/test-service-accounts.spec.js

- Allowed edit on Service Accounts
- Added tests for:
- Create,
- Details,
- Edit,
- Delete.
Closes: #548

Service Account tests and allow to edit

---

core-ui/src/components/Preferences/Preferences.js
core/package-lock.json
core/package.json
package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml

Upgrade Luigi to 1.19.0 version

---

core-ui/src/components/Predefined/Create/ConfigMaps/ConfigMaps.create.js
core-ui/src/components/Predefined/Create/Jobs/SpecSection.js
core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
resources/web/deployment.yaml

- CronJob YAML section in Edit was empty - fixed
- Add `disabled` attribute for Secret's type in Edit
- Adjust paths for CronJobs properties
Closes #609

Fix cron job update

---

resources/web/deployment.yaml
shared/components/K8sNameInput/K8sNameInput.js

- fix K8NameInput to always display current value

Fix nameinput edition between simple/advanced tabs

---

README.md

- change feature elements `isActive` to `isEnabled`

csmall change in the feature elements

---

tests/cypress.json
tests/tests/test.settings.spec.js

Adds test for application settings/preferences like theme, hidden namespaces, removing without confirmation

Add cypress tests for application settings

---

resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js

- Add a wrapper to the class component to use a hook
- ...
- ...
There is also a different issue - clicking encode/decode in the secrets details info modal closes it. Workaround for now - you can open the modal again to see the new state with decode/encoded values. - described in #638 
Closes #630

Add a wrapper to the class component to use a hook

---

README.md
core-ui/src/components/Predefined/Create/Certificates/Certificates.create.js
core-ui/src/components/Predefined/Details/Certificate/Certificate.details.js
core-ui/src/components/Predefined/Details/Certificate/CertificateRefs.js
core-ui/src/shared/ResourceForm/inputs/Text.js
resources/web/deployment.yaml
shared/components/K8sNameInput/K8sNameInput.js

- Fixed bug related to displaying CSR in the Edit modal
- Fixed bug related to displaying Secrets in the Edit modal
- Fixed some inputs 
- Add validation for secrets
**Related issue(s)** #608

Fix bugs related to CSR and Secrets in Certificate

---

core/src/i18n/en.yaml
resources/web/deployment.yaml

- fixed Privacy Options text bugs
- small refactor

fix text bug in the Privacy Options step

---

resources/web/deployment.yaml
shared/components/GenericList/Pagination/test/Pagination.test.js
shared/components/GenericList/test/GenericList.test.js

Fixes GenericList.test.js and Pagination.test.js in *shared* subrepo.

Fix jest tests in shared repo

---

core-ui/src/components/Preferences/ThemePreview/ThemePreview.js
core-ui/src/components/Preferences/ThemePreview/ThemePreview.scss
resources/web/deployment.yaml

- Fix UI bug when choosing a theme on Safari browser
Closes #628

Fix theme choose bug on Safari

---

core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
core-ui/src/shared/ResourceForm/inputs/ComboboxInput.js
resources/web/deployment.yaml

- Use manual selection type in all Comboboxes
- ...
- ...

Use manual selection type in all Comboboxes

---

resources/web/deployment.yaml
shared/components/GenericList/GenericList.scss
shared/components/ListActions/ListActions.js
shared/components/ListActions/ListActions.scss

- Fix action buttons alignment on cluster list
- Add margin between buttons

Fix action buttons alignment on cluster list, add margin between buttons

---

core-ui/src/components/Predefined/Details/Job/Job.details.js
core-ui/src/components/Predefined/List/Jobs.list.js
resources/web/deployment.yaml

- ...
- ...
- ...
Resolves https://github.com/kyma-project/busola/issues/662

Add jobs controlled by property

---

core-ui/src/components/Clusters/components/AddClusterWizard.js
core-ui/src/components/Clusters/shared.js
core-ui/src/shared/ResourceForm/components/Single.js
resources/web/deployment.yaml
tests/cypress.json
tests/support/loadKubeconfigFile.js
tests/tests/multiple-context-kubeconfig.spec.js

- Test multiple config
- Fix multiple config 'invalid' form bug
- ...
Resolves https://github.com/kyma-project/busola/issues/541

Test multiple contexts kubeconfig

---

README.md
core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/support/login-commands.js
tests/tests/add-cluster-disabled.spec.js
tests/tests/invalid-kubeconfig.spec.js
tests/tests/multiple-context-kubeconfig.spec.js
tests/tests/other-logins.spec.js

- Changed add cluster to connect cluster
- Repair tests for connect cluster
- ...
Closes #651

Connect cluster button

---

core-ui/src/components/Predefined/Create/GitRepositories/GitRepositories.create.js
resources/web/deployment.yaml
tests/tests/test-git-repositories.spec.js

Fixes the issue of repository-url input at *Git Repositories*. The input was losing focus after the first character was typed. 
#673

Fix blur issue at the git repos URL field

---

core-ui/src/components/Predefined/Create/DaemonSets/DaemonSets.create.js
core-ui/src/components/Predefined/Create/DaemonSets/templates.js
core-ui/src/components/Predefined/Create/Pods/Pods.create.js
core-ui/src/components/Predefined/Create/Pods/templates.js
core-ui/src/components/Predefined/Create/Services/Services.create.js
core-ui/src/components/Predefined/Create/Services/templates.js
core-ui/src/components/Predefined/Create/StatefulSets/StatefulSets.create.js
core-ui/src/components/Predefined/Create/StatefulSets/templates.js
core-ui/src/components/Predefined/Create/index.js
core-ui/src/shared/ResourceForm/components/ResourceForm.js
core-ui/src/shared/ResourceForm/components/Wrapper.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

Adds an option to create a resource in yaml (without the html simple/advanced form). Applied at the tabs without such option: pods, services, daemon sets and stateful sets.
Resolves #653

Add option to create any resource by yaml

---

core-ui/package-lock.json
core-ui/src/components/Predefined/Details/Gateway/GatewayServers.js
resources/web/deployment.yaml

Added link to secret in gateways.
- Added link to secret in gateways.
Closes #713

Link to secret in Gateways

---

resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/styled.js

Repair closing Decode/Encode button bug
- Repair closing Decode/Encode button bug
- Repair Close button
- ...
Closes https://github.tools.sap/kyma/backlog/issues/2161

Repair Close and Decode button

---

resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js

Decode secrets on instance details

---

tests/tests/test-ingresses.spec.js

Repair ingress tests

---

core/src/i18n/en.yaml
resources/backend/deployment.yaml
resources/web/deployment.yaml

- add info to protected resources tooltip on where modification of protected resources can be enabled.
- ...
- ...

Improve protected res tooltip

---

core-ui/src/components/Predefined/Details/Pod/Pod.details.js
resources/web/deployment.yaml

Fixed a link in the pods details view.
Fixes #734

Fix link in config map

---

core-ui/src/hooks/useMessageList.js
resources/web/deployment.yaml

Fix double slash in event link list
Resolves #719

Fix double slash in event link list

---

core-ui/src/shared/ResourceForm/components/Wrapper.js
resources/web/deployment.yaml

Fix no-repos bug at function create form
Fixes #733

Fix no-repos bug at function create form

---

core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
resources/web/deployment.yaml

- ...
- ...
- ...
Resolves #736

Show only stored CRD

---

core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CRCreate.js
core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
core-ui/src/components/Predefined/Details/CustomResourceDefinitions/templates.js
resources/web/deployment.yaml
tests/fixtures/test-custom-resource-instance.yaml
tests/fixtures/test-customresourcedefinisions.yaml
tests/support/commands.js
tests/support/loadCRD.js
tests/support/views/functions-view.js
tests/tests/test-custom-resource-definitions.spec.js
tests/tests/test-destination-rules.spec.js
tests/tests/test-ingresses.spec.js

Create a form at CRD details view to create the CRD instance. Form is prepopulated with basic data (unfortunately the exact validation rules are not available in the spec).
Resolves #654

Add form to create any CR based on the definition

---

core-ui/src/shared/ResourceForm/components/ResourceForm.js
core-ui/src/shared/ResourceForm/fields/Editor.js
core-ui/src/shared/ResourceForm/fields/Editor.scss
resources/web/deployment.yaml
shared/contexts/YamlEditorContext/EditorActions.js
shared/index.js

- Add copy etc buttons to the create resource yaml editor
- ...
- ...
Resolves #724

Add copy etc buttons to the create resource yaml editor

---

.github/workflows/codeql-analysis.yml

Create codeql-analysis.yml for Dependabot

---

core/src/i18n/en.yaml
core/src/luigi-config/nav-footer.js
resources/web/deployment.yaml
tests/cypress.json
tests/tests/test-dashboard-version.spec.js

- Changed `Version` to `Kyma Dashboard Version`
- Added link do version
- Added validation for commit, PR and dev version.
Closes #703

Kyma Dashboard Version with link

---

core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
core-ui/src/components/Predefined/List/CustomResourceDefinitions.list.js
resources/web/deployment.yaml

Fix CRD search

---

core/src/i18n/en.yaml
resources/web/deployment.yaml
shared/contexts/YamlEditorContext/EditorActions.js

- Add button that can hide/show managedFields and status

Hide read only lines from editor

---

core-ui/src/components/Predefined/Create/Functions/Functions.create.js
resources/web/deployment.yaml

- Add getting dependencies and source code from yaml in the function
Close: #775

Fix bug related to pasting yaml in function

---

core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
resources/web/deployment.yaml

Fix the creation of Limit ranges and Resource quotas

---

resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingForm.js

- Tiny fix to make validation work properly

Tiny fix to make validation work properly

---

core-ui/src/components/Predefined/Create/index.js
resources/web/deployment.yaml

We have double Subscription component export in `index.js`
- Deleted one export
- ...
- ...

Deleted double subscription export from index

---

resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingForm.js

- Fix problem with creation of service binding

Fix problem with creation of service binding

---

core-ui/src/components/Predefined/Details/StorageClasses/PersistentVolumesList.js
resources/web/deployment.yaml

We need to have links to connected Persistent Volumes.
- Added links with navigation to Persistent Volumes
- ...
- ...
Closes #810

Added links to connected persistent volumes on list view

---

core-ui/src/components/Predefined/Details/Application/ApplicationServicesDetails/ApplicationServicesDetails.js
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml
tests/support/views/functions-view.js

Fix redirection after application deletion

---

core-ui/src/components/Predefined/Create/CustomResourceDefinitions/CustomResourceDefinitons.create.js
resources/web/deployment.yaml

CRD name singular was wrong  and UI didn't show info "CRD created"
- Added `s` to name
- ...
- ...

Repair name singular

---

Dockerfile.local
tests/cypress-smoke.json

Show Kyma Version on Docker build

---

core-ui/src/components/Lambdas/components/FormInput/FormInput.scss
core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

- Fix the length of the name input in the `Create Addons Configuration` modal
- Add deep linking from PV to PVC

Fix addons' name input

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
resources/web/configmap.yaml
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassDetails/ServiceClassDetails.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingUsageForm/CreateServiceBindingUsageModal.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.js

- Add feature flag to disable readonly mode in catalog

Disable readonly mode in catalog

---

core-ui/src/components/Clusters/views/ClusterList.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/CreateVariable/CreateVariable.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
core-ui/src/components/Predefined/List/Events.list.js
core/src/i18n/en.yaml
resources/web/deployment.yaml
shared/components/ResourceDetails/ResourceDetails.js
shared/components/ResourcesList/ResourcesList.js
shared/hooks/useDeleteResource.js
tests/tests/reduced-permissions.spec.js

- Add confirmation to the deletion of clusters and env variables
- Fix missing backdrop on add env modal
- Remove one console error
Fixes #649

Add confirmation to the deletion of clusters and env variables

---

resources/web/deployment.yaml
shared/hooks/useProtectedResources.js

- Change protected resources icon from warning to locked

Change protected resources icon

---

core-ui/src/components/Lambdas/constants.js
core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
resources/web/deployment.yaml

- Deprecate nodejs12
https://github.com/kyma-project/kyma/issues/12381

Deprecate nodejs12

---

core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/support/login-commands.js
tests/tests/add-cluster-disabled.spec.js
tests/tests/invalid-kubeconfig.spec.js
tests/tests/multiple-context-kubeconfig.spec.js
tests/tests/other-logins.spec.js

- add plural form to CRD with multiple choice/type option
- small text refactor
Resolves #817

Plural form of some of the options in Cron Job, Job, Gateway, Oath2 Client, and DNE Entry views

---

core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
resources/web/deployment.yaml

- Fix small buttons on namespace details

Fix small buttons on namespace details

---

core-ui/src/components/Clusters/views/ClusterList.js
core-ui/src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
core-ui/src/shared/ResourceForm/components/ResourceForm.js
core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/cypress.json
tests/tests/edit-cluster.spec.js

Introduced a feature to edit Clusters 
Resolves #851

Introduce edit cluster option on the cluster list

---

core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
resources/web/deployment.yaml

Fix css timeframe function logs
Fixes #870

Fix css in timeframe-fn-logs

---

tests/busola-e2e-cleaner.yaml

- arnold
**Testing**
Just deploy on nkyma, changing `0 */3 * * *` to something quicker, like `*/1 * * * *`.
[Prow](https://github.com/kyma-project/test-infra/pull/4877)
Connected #894

Add job for cleaning Busola e2e tests on nkyma

---

core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
core-ui/src/components/ApiRules/ApiRuleStatus/test/ApiRuleStatus.test.js
core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/tests/in-cluster-eventing.spec.js
tests/tests/run-after.spec.js
tests/tests/test-issuers.spec.js

- Remove waiting of application removal - the removal takes sometimes around 30 seconds and waiting for it doesn't bring too much value to the test
- Wait for a proper API rule status before checking the gateway
- Wait for a proper Issuer status before editing it, to avoid version conflicts
Resolves #902

Stabilise tests

---

core-ui/src/components/Predefined/Create/Gateways/templates.js
resources/web/deployment.yaml
tests/tests/test-gateways.spec.js

Add default selector for Gateways

---

core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
core-ui/src/components/Predefined/Create/Jobs/templates.js
resources/web/deployment.yaml

Fix bug of concurrency policy in the Cron Jobs

---

core-ui/src/shared/ResourceForm/fields/KeyValueField.js
resources/web/deployment.yaml

- ...
- ...
- ...
Fixes https://github.com/kyma-project/busola/issues/918

Fix config map not updating, fix encoded config map data

---

core-ui/src/components/Predefined/Create/Jobs/Containers.js
core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
resources/web/deployment.yaml

Jobs and CronJobs can be created without command, so I deleted the required flag and validation. 
- Removed required flag
- Removed validation of no empty command
Closes #920

Repair creating Jobs and CronJobs

---

core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
core-ui/src/components/Predefined/Details/Job/Job.details.js
core-ui/src/components/Predefined/Details/Subscriptions/Subscriptions.details.js
resources/web/deployment.yaml

- Add `Events` list to the CRDS general views
- Add `Events` list to the Subscriptions, Jobs and CronJobs details views
Closes #930

Add events list to the CRDS general views

---

core-ui/src/components/Predefined/Details/Pod/Pod.details.js
resources/web/deployment.yaml

- Add deeplinks for secrets and persistent volume claims

Add deeplinks for secrets and persistent volume claims

---

core-ui/src/components/Lambdas/config.js
core-ui/src/components/Lambdas/constants.js
core-ui/src/components/Lambdas/helpers/runtime/runtime.js
core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
resources/web/deployment.yaml

- remove python38
See https://github.com/kyma-project/kyma/issues/12380

Remove python 38

---

nginx/nginx.conf

- https://stackoverflow.com/a/36003231

Set gzip proxied to all for web

---

CODEOWNERS

Add wchrapka to CODEOWNERS

---

core-ui/src/components/Predefined/Create/ServiceInstances/ServiceInstances.create.js
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/PlanColumnContent.js

- Fix bug when choosing different plan in Instances

Fix bug when choosing plan in Instances

---

core-ui/src/components/Predefined/Create/Secrets/helpers.js
resources/web/deployment.yaml

In the creation model, we haven't got apiVersion and kind in YAML.
- Added kind and apiVersion in create temaplate
- ...
- ...
Closes #1001

Added kind and apiVersion to Secrets create template

---

core-ui/src/components/Predefined/Create/Functions/Functions.create.js
resources/web/deployment.yaml

We haven't got inserting the function name into dependencies.
- Added function for deps
- ...
- ...
Closes #1000

Added inserting function name to dependencies

---

resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.js

We didn't use long descriptions.
- Changed descriptions long description
- ...
- ...
Closes #1009

Changed description to long description in service classes

---

backend/index.js
resources/backend/deployment.yaml

disable gzip for requests with follow=
Fixes #1031

disable gzip for requests with follow=

---

core-ui/src/components/Predefined/Details/ApiRule/Services.js
core-ui/src/components/Predefined/List/VirtualServices.list.js
resources/web/deployment.yaml

Fix Virtual Services navigation

---

core-ui/src/components/Predefined/Create/Subscriptions/FiltersSection.js
resources/web/deployment.yaml
tests/cypress.json

- ...
- ...
- ...
https://github.tools.sap/kyma/backlog/issues/2398

Removed specialCharacter validation for eventType

---

core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
core-ui/src/components/Predefined/Create/PersistentVolumeClaims/PersistentVolumeClaims.create.js
core-ui/src/components/Predefined/Create/PersistentVolumes/PersistentVolumes.create.js
core-ui/src/components/Predefined/Create/Pods/Pods.create.js
core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
core-ui/src/components/Predefined/Create/ServiceAccounts/ServiceAccounts.create.js
core-ui/src/components/Predefined/Create/StorageClasses/StorageClasses.create.js
core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
core-ui/src/shared/helpers/getResourceDefs.js
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #1048

Visual Resources for Storage Objects

---

core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
core-ui/src/components/Predefined/Details/DaemonSet/DaemonSet.details.js
core-ui/src/components/Predefined/Details/GitRepositories.details.js
core-ui/src/components/Predefined/Details/HPA/HPA.details.js
core-ui/src/components/Predefined/Details/HPA/HPASubcomponent.js
core-ui/src/components/Predefined/Details/NetworkPolicy/NetworkPolicy.details.js
core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
core-ui/src/components/Predefined/Details/ReplicaSet/Replicaset.details.js
core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.details.js
core-ui/src/components/Predefined/Details/Roles/Roles.details.js
core-ui/src/components/Predefined/Details/ServiceAccount/ServiceAccount.details.js
core-ui/src/components/Predefined/Details/StatefulSet/StatefulSets.details.js
core-ui/src/components/Predefined/Details/StorageClasses/StorageClasses.details.js
core-ui/src/components/Predefined/List/DNSEntries.list.js
core-ui/src/components/Predefined/List/DNSProviders.list.js
resources/web/deployment.yaml
shared/components/ResourceDetails/ResourceDetails.js
shared/utils/helpers.js

- ...
- ...
- ...
Resolves #1090

Fix lowercase in the 'resource not found page'

---

core-ui/src/components/Predefined/Create/Roles/GenericRoleCreate.js
core-ui/src/components/Predefined/Create/Roles/Roles.create.js
core-ui/src/components/Predefined/Create/Roles/helpers.js
core/src/i18n/en.yaml
resources/web/deployment.yaml

Add simple role presets

---

CODEOWNERS
OWNERS_ALIASES

Update repository owners

---

core-ui/src/shared/hooks/usePrometheus.js
resources/web/deployment.yaml

Fix error handling for graph

---

core-ui/src/shared/components/ResourceGraph/ResourceGraph.js
core-ui/src/shared/components/ResourceGraph/ResourceGraph.scss
resources/web/deployment.yaml

Improve styling for ResourceGraphs
- Added `LayoutPanel.Body`
- ...
- ...
Closes #1181

Improve styling for ResourceGraphs

---

core-ui/src/shared/components/ResourceGraph/buildGraph/buildNetworkGraph.js
resources/web/deployment.yaml

fix graph-viz bug

---

OWNERS_ALIASES

Adjust owners

---

core-ui/package-lock.json
core-ui/package.json
core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/LambdaReplicas.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/LambdaResources.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement.scss
core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/TableElements/Input.js
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #1184

Fix function resources form

---

backend/Dockerfile
backend/package.json
core-ui/package.json
core/package.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #1065

Clean up npm start commands

---

core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
core-ui/src/components/Predefined/List/PersistentVolumes.list.js
core-ui/src/shared/components/RelatedPods.js
core-ui/src/shared/components/Selector/Selector.js
resources/web/deployment.yaml

- Change the way we filter pods from an URL to a filter function

Fix deleting all Pods in namespace via details view

---

CODEOWNERS

Remove Wojtek from codeowners

---

core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/support/login-commands.js
tests/tests/cluster/test-invalid-kubeconfig.spec.js
tests/tests/cluster/test-multiple-context-kubeconfig.spec.js
tests/tests/cluster/test-other-login-options.spec.js

- Add info in the **Connect cluster** view that a user can also browse the computer in search for the kubeconfig file.
Resolves #1233

Clusters overview info

---

backend/package-lock.json
backend/package.json
resources/backend/deployment.yaml

Override version of "async" to prevent a vulnerability https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-43138
Resolves #1238

Update "async", dep of express-jwt

---

core-ui/src/resources/Secrets/helpers.js
core-ui/src/shared/helpers/getResourceDefs.js
resources/web/deployment.yaml

fix getResourceDefs functions

---

core-ui/src/components/Clusters/views/ClusterList.js
core-ui/src/components/CustomResources/CRDList.js
core-ui/src/components/CustomResources/CustomResources.js
core-ui/src/components/CustomResources/CustomResourcesByGroup.js
core-ui/src/components/CustomResources/GroupingListPage.js
core-ui/src/components/CustomResources/GroupingListPage/GroupingListPage.scss
core-ui/src/components/HelmReleases/HelmReleasesList.js
core-ui/src/hooks/useCustomMessageListener.js
core-ui/src/resources/Events/EventList.js
core-ui/src/resources/createResourceRoutes.js
core-ui/src/shared/components/GenericList/GenericList.js
core-ui/src/shared/components/GenericList/SearchInput.js
core-ui/src/shared/components/ResourcesList/ResourcesList.js
core/src/luigi-config/communication.js
resources/web/deployment.yaml
tests/tests/cluster/test-custom-resources.spec.js
tests/tests/namespace/test-custom-resources.spec.js

As a user, after clicking `/` on the keyboard I want to open a search input.
- Added listeners for `/`
- Changed search input for CustomResources
- ...
Closes #1213

Open search shortcut

---

core-ui/src/resources/CronJobs/CronJobCreate.js
core-ui/src/resources/Deployments/DeploymentCreate.js
core-ui/src/resources/Gateways/GatewayCreate.js
core-ui/src/resources/Issuers/IssuerCreate.js
core-ui/src/resources/Jobs/JobCreate.js
core-ui/src/resources/Roles/GenericRoleCreate.js
core-ui/src/resources/Secrets/SecretCreate.js
core-ui/src/resources/Secrets/helpers.js
core-ui/src/shared/helpers/getResourceDefs.js
resources/web/deployment.yaml

- Remove presets in the Edit Mode
- Fix another bug with Secret presets
Closes #1166

Remove presets in the Edit Mode

---

core-ui/src/shared/components/PodTemplate/PodTemplate.js
core-ui/src/shared/components/PodTemplate/components.js
core-ui/src/shared/hooks/useIntersectionObserver.js
resources/web/deployment.yaml

Load graphs when 20% of the graph container is visible

---

core-ui/src/resources/ServiceAccounts/index.js
resources/web/deployment.yaml

- Fix too many connections in the SA graphs causing the browser to freeze
- ...
- ...
Resolves #1275

Fix too many connections in the SA graphs

---

core-ui/src/resources/PersistentVolumeClaims/index.js
resources/web/deployment.yaml

PV and PVC graphs are showing too much data.
- Changed `=` to `===`
- ...
- ...
Closes #1289

Repair pvc to pv connect

---

core-ui/src/resources/APIRules/AccessStrategyForm.js
resources/web/deployment.yaml

- Fix bug when changing a handler in Api Rule rules

Fix bug when changing a handler in Api Rule

---

core-ui/src/resources/ClusterRoles/helpers.js
core-ui/src/resources/CronJobs/CronJobCreate.js
core-ui/src/resources/GitRepositories/helpers.js
core-ui/src/resources/Jobs/JobCreate.js
core-ui/src/resources/Jobs/templates.js
core-ui/src/resources/Roles/helpers.js
resources/web/deployment.yaml

- Change the name of the default preset to `Hello` in CronJobs and Jobs. Add a new preset that is a default one and clears the form
- Add default presets to the Roles and ClusterRoles
- Remove generating a name in the `Git Repository` creation form
Closes #1263

Improve default presets 

---

core/src/luigi-config/cluster-management/cluster-management.js
core/src/luigi-config/navigation/navigation-data-init.js
core/src/luigi-config/navigation/navigation-helpers.js
resources/web/deployment.yaml
tests/tests/cluster/test-cluster-configuration.spec.js

- ...
- ...
- ...
Closes #1276

External nodes as a feature

---

core-ui/src/components/HelmReleases/tests/HelmReleaseData.test.js
core-ui/src/service-catalog-ui/Wrapper.js
core-ui/src/shared/ResourceForm/components/ResourceForm.js
core-ui/src/shared/components/MonacoEditorESM/Editor.js
core-ui/src/shared/components/MonacoEditorESM/Editor.scss
core-ui/src/shared/components/MonacoEditorESM/monaco-autocomplete.worker.js
core-ui/src/shared/components/ReadonlyEditorPanel.js
core-ui/src/shared/contexts/YamlEditorContext/EditorActions.js
core-ui/src/shared/contexts/YamlEditorContext/YamlContent.js
core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/tests/namespace/test-network-policies.spec.js
tests/tests/namespace/test-virtual-services.spec.js

Add editor actions to the new editor. 
Resolves #1253

Editor Actions for Monaco ESM

---

core/package-lock.json
core/package.json
core/src/luigi-config/communication.js
core/src/luigi-config/utils/feature-toggles.js
package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml
tests/tests/namespace/test-namespace-overview.spec.js
tests/tests/namespace/test-protected-resources.spec.js

- Bump luigi and trigger Luigi.configChanged() to update toggles
Resolves #768

Cluster interaction toggles

---

core-ui/src/resources/LimitRanges/templates.js
resources/web/deployment.yaml

- ...
- ...
- ...
Resolved #1315

Fix limits creation

---

nginx/nginx.conf

Updates nginx configuration to cache version.json for 1m.
Resolves #1318

Fix PR version on dev

---

core-ui/src/shared/components/MonacoEditorESM/useAutocompleteWorker.js
resources/web/deployment.yaml

bump-version

---

core-ui/src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
core-ui/src/shared/components/RelatedPods.js
core-ui/src/shared/components/ResourcesList/ResourcesList.js
resources/web/deployment.yaml

- Add a `disableCreate` prop.
Closes #1224

Disable create for related resources

---

core-ui/src/shared/hooks/usePrometheus.js
resources/web/deployment.yaml

- As in title
Closes #1204 1204

Remove Kyma version auto-detection when Kyma 2.1.1. is live on all clusters

---

README.md
core-ui/src/command-pallette/CommandPalletteUI/CommandPaletteUI.js
core-ui/src/command-pallette/CommandPalletteUI/useSearchResults.js
core-ui/src/resources/Applications/CreateBindingModal/CreateBindingModal.js
core-ui/src/resources/Namespaces/NamespaceList.js
core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
core-ui/src/shared/helpers/getHiddenNamespaces.js
core/src/assets/defaultConfig.json
core/src/luigi-config/cluster-management/cluster-management.js
core/src/luigi-config/constants.js
core/src/luigi-config/kubeconfig-id/index.js
core/src/luigi-config/navigation/navigation-data-init.js
docs/features.md
resources/web/deployment.yaml
tests/tests/cluster/test-cluster-configuration.spec.js

- Moves the hidden namespace list to the config features.
- Moves the disabled nodes list to the config features.
Resolves #1311, resolves #1273

Hidden namespaces, disabled nodes as features

---

core-ui/src/shared/components/DefinitionList/DefinitionList.js
resources/web/deployment.yaml

- ...
- ...
- ...
Resolves #1314

Fix service instances and service bindings details layout

---

core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.js
core-ui/src/resources/APIRules/AccessStrategyForm.js
core-ui/src/resources/APIRules/helpers.js
core-ui/src/shared/components/StatusBadge/StatusBadge.scss
core-ui/src/styles/index.scss
core/src/i18n/en.yaml
resources/web/deployment.yaml

- Changed displayed info from the handler,
- Added tooltip for wrong value,
- Added color changer for wrong value.
Closes #1349

Added case for wrong accesstrategy type

---

core/src/assets/defaultConfig.json
docs/features.md
resources/web/deployment.yaml

- Remove kube-public from hidden namespaces
- ...
- ...
Resolves #1352

Remove kube-public from hidden namespaces

---

core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml

Fix nav nodes flow

---

core-ui/src/shared/components/MonacoEditorESM/Editor.scss
resources/web/deployment.yaml

- Changed error display info.
Closes #1287

Fix problems with create form UI

---

core-ui/src/resources/Deployments/DeploymentCreate.js
core-ui/src/resources/Deployments/DeploymentCreate.scss
core-ui/src/resources/Deployments/templates.js
core-ui/src/resources/Namespaces/NamespaceCreate.js
core-ui/src/resources/ReplicaSets/ReplicaSetCreate.scss
core/src/i18n/en.yaml
resources/web/deployment.yaml
tests/cypress.json
tests/fixtures/test-services.yaml
tests/tests/namespace/test-deployments.spec.js
tests/tests/namespace/test-services.spec.js

- ...
- ...
- ...
Closes #1335

Removed service yaml in deployment

---

core-ui/src/command-pallette/CommandPaletteProvider.js
core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
core-ui/src/shared/components/MonacoEditorESM/Editor.js
core-ui/src/shared/components/MonacoEditorESM/getSchemaLink.js
core-ui/src/shared/components/MonacoEditorESM/useAutocompleteWorker.js
core-ui/src/shared/constants.js
core/src/luigi-config/cluster-management/cluster-management.js
resources/web/deployment.yaml

Adds custom links to schema tooltips 
Solves #1284

custom links in monaco tooltips

---

core-ui/src/components/Extensibility/ExtensibilityDetails.js
resources/web/deployment.yaml

- Fix breadcrumbs
Closes https://github.com/kyma-project/busola/issues/1410

Fix breadcrumbs

---

core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/resources/Events/EventList.js
core-ui/src/shared/components/EventsList.js
core-ui/src/shared/components/ResourcesList/ResourcesList.js
resources/web/deployment.yaml

- Fix #1408
- Fix title on namespaced Events
Closes #1408

EXT: Window titles are the same on list and details views

---

core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/ExtensibilityList.js
core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.js
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #1403 
Fixes #1409 (Closes 2 topic in that issue)

added props for displaying button in ErrorBoundary

---

core-ui/package-lock.json
core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/ExtensibilityList.js
core/src/luigi-config/feature-discovery.js
resources/web/deployment.yaml

- singular kind
- customResources on navigation reload

minor fixes

---

core-ui/src/components/App/App.js
core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/ExtensibilityList.js
core-ui/src/components/Extensibility/ResourceSchema.js
core-ui/src/components/Extensibility/components/Panel.js
resources/web/deployment.yaml

- ...
- ...
- ...
Fixes https://github.com/kyma-project/busola/issues/1402

Fix crashing view if a user puts an object instead of an array

---

core-ui/src/components/Extensibility/ResourceSchema.js
core-ui/src/components/Extensibility/helpers.js
core-ui/src/index.js
core/src/luigi-config/luigi-config.js
core/src/luigi-config/navigation/customPaths.js
resources/web/deployment.yaml

- ...
- ...
- ...
Resolves https://github.com/kyma-project/busola/issues/1432

Fix translations bug for extensibility

---

core-ui/src/components/Extensibility/components/Table.js
resources/web/deployment.yaml

- Allow title for table
Closes #1419

Allow title for table

---

core-ui/package-lock.json
core-ui/package.json
core-ui/src/components/Extensibility/ResourceSchema.js
resources/web/deployment.yaml

- Updated ui-schema library
- Changed container prop from boolean to string to prevent console error
Resolves #1443

Update UI-Schema to prevent console errors

---

core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
core-ui/src/components/Extensibility/metadataSchema.js
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #1458

Fix for editing labels in extensibility

---

core/src/luigi-config/customResources.js
resources/web/deployment.yaml

- improve error handling for config maps
closes #1401

Handle errors

---

core-ui/src/components/Extensibility/ExtensibilityList.js
core-ui/src/resources/createResourceRoutes.js
resources/web/deployment.yaml
tests/tests/namespace/test-api-rules.spec.js

- ...
- ...
- ...
Closes #1455

Fix slash shortcut

---

core-ui/src/components/Functions/config.js
core-ui/src/components/Functions/constants.js
core-ui/src/components/Functions/helpers/runtime/runtime.js
core-ui/src/components/Functions/helpers/runtime/test/runtime.test.js
docs/extensibility/form-widgets.md
resources/web/deployment.yaml

Nodejs16 will be improved in Kyma 2.4 not in 2.3 so we have to remove this changes https://github.com/kyma-project/busola/pull/1426
- ...
- ...
- ...

remove nodejs16

---

core-ui/src/components/Extensibility/components-form/NameRenderer.js
resources/web/deployment.yaml

- Fixed read-only name input in extensibility form
Resolves #1475

EXT: Fixed read-only name input in form

---

docs/extensibility/README.md
docs/extensibility/configmap-sections.md
docs/extensibility/display-widgets.md
docs/extensibility/resources.md

- add the README.md file
- change title and fix formatting in configmap-sections.md
See also #1480

updated ext docs

---

core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeTab.js
core-ui/src/resources/Applications/ApplicationDetails.js
core-ui/src/resources/Namespaces/NamespaceDetails.js
resources/web/deployment.yaml

- Remove application connector components if the service catalog is disabled
- Remove remaining service usage etc components if the service catalog is disabled
- ...
Resolves #1509

Remove also application connector components if service catalog is disabled

---

core-ui/src/shared/ResourceForm/inputs/Number.js
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #1576

Fix for 0 as null in ext create modal

---

core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
core-ui/src/shared/components/MonacoEditorESM/Editor.js
core-ui/src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
core-ui/src/shared/components/MonacoEditorESM/hooks/useOnBlur.js
core-ui/src/shared/components/MonacoEditorESM/hooks/useOnChange.js
core-ui/src/shared/components/MonacoEditorESM/hooks/useOnFocus.js
core-ui/src/shared/components/MonacoEditorESM/hooks/useUpdateValueOnParentChange.js
resources/web/deployment.yaml

Revert monaco change that break the edito

---

backend/common.js
backend/index.js
backend/settings/defaultConfig.json
core-ui/src/components/App/App.js
core-ui/src/hooks/tracking.js
core-ui/src/hooks/useTracking.js
core-ui/src/resources/Applications/ApplicationServices.js
core-ui/src/shared/useComponentDidMount.js
core/src/assets/defaultConfig.json
core/src/luigi-config/cluster-management/cluster-management.js
core/src/luigi-config/communication.js
core/src/luigi-config/tracking.js
resources/backend/deployment.yaml
resources/web/deployment.yaml

- Also fix tiny bug on Application details
- When someone doesn't use our frontend BUT uses backend - we don't use `/backend/tracking` endpoint. Instead I've added possibility to increate logs output by setting the TRACKING flag.
**Testing**
Remember to enable TRACKING feature in `defaultConfig.json` (on frontend and probably on backend).

Add first session & cluster change tracking

---

core-ui/src/components/Extensibility/components/Widget.js
core/src/luigi-config/tracking.js
resources/web/deployment.yaml

- Send Authorization header with SSO
- Fix tiny Widget bug

Fix tracking with SSO

---

core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/components/Widget.js
core-ui/src/components/Extensibility/components/tests/Widget.test.js
core-ui/src/setupTests.js
core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
core-ui/src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
core-ui/src/shared/typechecking/CustomPropTypes.js
docs/extensibility/resources.md
resources/web/deployment.yaml

- As in issue.
- Add more tests
Closes #1539

Extensibility: Details view: Hide key if the value is empty from panels

---

core-ui/src/resources/ServiceBindings/helpers.js
core-ui/src/resources/ServiceInstances/ServiceBindingList.js
core-ui/src/resources/ServiceInstances/helpers.js
resources/web/deployment.yaml

- ...
- ...
- ...
Resolves #1553

Fix btp versions missalign

---

core-ui/src/resources/ConfigMaps/ConfigMapDetails.js
resources/web/deployment.yaml

- Fix error on config map details when there are no labels

Fix error on config map details when there are no labels

---

docs/extensibility/resources.md

- fix formatting of parameters written in the `code` format in the Extensibility documentation.
Resolves #1532

Fix formatting of parameters in the Extensibility documentation

---

NOTICE.md

changed the copyright year

---

examples/pizzas/configuration/pizza-orders-configmap.yaml
examples/pizzas/configuration/pizzas-configmap.yaml

Ext: Fix description and formulas

---

docs/extensibility/display-widgets.md

Fix resourceLink docs

---

core/src/i18n/en.yaml
resources/web/deployment.yaml

- Change sorting name from Time to Age

change Time to Age

---

core-ui/src/resources/OAuth2Clients/OAuth2ClientList.js
resources/web/deployment.yaml

- fix the link to OAuth2 description

fix link to OAth2 description

---

core-ui/src/components/Functions/helpers/functions/getFunctionStatus.js
core-ui/src/hooks/useVersionWarning.js
core-ui/src/resources/ConfigMaps/ConfigMapDetails.js
core-ui/src/resources/ServiceInstances/ServiceInstanceData.js
core-ui/src/shared/utils/helpers.js
resources/web/deployment.yaml

Fix sentry errors

---

docs/extensibility/README.md
docs/extensibility/resources.md

- Changed steps in the Quick Steps section of the Extensibility README.md file
- Added note about the possibility of adding Extensibility Config Map in the user's own Namespace.
- updated the version section in the Resources.md file.
Resolves #1690

Adjust Extensibility documentation to current status

---

core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
core-ui/src/components/BusolaExtensions/BusolaExtensionEdit.js
core-ui/src/components/BusolaExtensions/constants.js
core-ui/src/components/BusolaExtensions/helpers.js
core-ui/src/components/Extensibility/migration.js
core/src/i18n/en.yaml
core/src/luigi-config/customResources.js
docs/extensibility/resources.md
examples/pizzas/configuration/pizza-orders-configmap.yaml
examples/pizzas/configuration/pizzas-configmap.yaml
examples/resources/configuration/certificates.yaml
examples/resources/configuration/gitrepositories.yaml
examples/resources/configuration/services.yaml
resources/web/deployment.yaml

Move version to labels

---

core-ui/src/components/Functions/config.js
core-ui/src/components/Functions/constants.js
core-ui/src/components/Functions/helpers/runtime/runtime.js
core-ui/src/components/Functions/helpers/runtime/test/runtime.test.js
resources/web/deployment.yaml

- add nodejs16 as non-default runtime
https://github.com/kyma-project/kyma/issues/14067

Add nodejs16 runtime

---

core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
core-ui/src/components/BusolaExtensions/BusolaExtensionEdit.js
core/src/luigi-config/customResources.js
docs/extensibility/resources.md
resources/web/deployment.yaml

Removes the alternative version of adding the EXT translations through:
```
data:
translations-en: {}
translations-pl: {}
```
Resolves #1698

Remove support for translations-xx format

---

core-ui/src/components/BusolaExtensions/helpers.js
core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/ExtensibilityList.js
core-ui/src/components/Extensibility/components/PendingWrapper.js
core-ui/src/components/Extensibility/components/ResourceList.js
core-ui/src/components/Extensibility/components/Widget.js
core-ui/src/components/Extensibility/components/tests/Table.test.js
core-ui/src/components/Extensibility/components/tests/Widget.test.js
core-ui/src/components/Extensibility/contexts/DataSources.js
core/src/i18n/en.yaml
docs/extensibility/display-widgets.md
docs/extensibility/resources.md
examples/pizzas/configuration/pizzas-configmap.yaml
examples/resources/configuration/services.yaml
resources/web/deployment.yaml

Closes #1700 
Tbh I'm not sure if we should include `ownerLabelSelectorPath` in `resource`. Thoughts? @Lyczeq  agrees with the approach I've used in the code.

Extensibility: convert "relations" section to "dataSources"

---

core-ui/src/components/Preferences/ProtectedSettings.js
resources/web/deployment.yaml

- Hide the protected resources toggle if the feature is disabled
- ...
- ...
Resolves https://github.com/kyma-project/busola/issues/1674

Hide the protected resources toggle if the feature is disabled

---

core-ui/src/components/Extensibility/ExtensibilityCreate.js
examples/pizzas/configuration/pizzas-configmap.yaml
resources/web/deployment.yaml

- added comma to pizza config-map,
- added `|| prettyfiKind` to singularName
- ...

fix pizzas configmap and editing extensibility

---

core-ui/src/shared/ResourceForm/components/Presets.js
core-ui/src/shared/ResourceForm/components/ResourceForm.js
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #1632

fix for no refreshing monaco for presets

---

core-ui/src/resources/Functions/FunctionCreate.js
resources/web/deployment.yaml

**To reproduce**
- Create function with `Source Type` set to `Git Repository`
- Try editing it on details view

Fix git Function edit

---

core-ui/src/components/Extensibility/components/ResourceRefs.js
core-ui/src/shared/helpers/universalLinks.js
resources/web/deployment.yaml

- Fix linking to namespace details
- Fix margins when ResourceRf is used in Columns

Namespaces ResourceRef

---

core-ui/src/components/Extensibility/components/ResourceLink.js
examples/resources/configuration/certificates.yaml
examples/resources/configuration/gitrepositories.yaml
examples/resources/configuration/services.yaml
resources/web/deployment.yaml

- Adjusted examples from the resources directory to the new format
- Fixed a ResourceLink, previously it was necessary to use linkText, now it takes a name as a default

Fixed Certificates and the ResourceLink widget

---

core-ui/src/components/Extensibility/components-form/GenericList.js
core-ui/src/components/Extensibility/components-form/NumberRenderer.js
core-ui/src/components/Extensibility/components-form/SimpleList.js
core-ui/src/components/Extensibility/components-form/StringRenderer.js
docs/extensibility/form-widgets.md
resources/web/deployment.yaml

- added placeholders to generic/simple list and string/number renderer
- ...
- ...
Closes #1782

allow placeholders in extensibility

---

core-ui/src/components/Extensibility/components/ResourceLink.js
core-ui/src/components/Extensibility/contexts/DataSources.js
core-ui/src/shared/components/ResourcesList/ResourcesList.js
docs/extensibility/display-widgets.md
resources/web/deployment.yaml

- Fixed a ResourceLink widget and changed the example in the docs
- Fixed the Table's docs to use `$item` in the example

Fix ResourceLink widget and Table's docs

---

CODEOWNERS
OWNERS_ALIASES

- add Lyczeq mrCherry97 to codeowners

Adjust codeowners

---

core-ui/src/shared/components/ResourceGraph/buildGraph/helpers.js
core-ui/src/shared/components/ResourceGraph/getResourceGraphConfig.js
core-ui/src/styles/index.scss
examples/resources/configuration/istio/gateways.yaml
resources/web/deployment.yaml

Handle gateways on ResourceGraph

---

core-ui/src/components/BusolaExtensions/helpers.js
resources/web/deployment.yaml

- Change path to source
- ...
- ...

Fix remaining paths for extensions created via UI

---

core-ui/src/components/Functions/config.js
resources/web/deployment.yaml

- change sample code of functions to demonstrate how to use context and log
https://github.com/kyma-project/kyma/issues/14023

Improve Sample Code of Kyma Functions

---

core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
core-ui/src/components/Functions/helpers/runtime/runtime.js
resources/web/deployment.yaml

- as in the title
Fixes https://github.com/kyma-project/kyma/issues/15339

Allow users to create function without dependencies

---

core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
core-ui/src/components/Extensibility/components-form/SimpleList.js
resources/web/deployment.yaml

Fix translations for tooltips in simple list and monaco

---

core-ui/src/components/Extensibility/helpers/index.js
resources/web/deployment.yaml

Fix translations

---

docs/extensibility/datasources-section.md
docs/extensibility/display-section.md
docs/extensibility/form-section.md
docs/extensibility/jsonata.md
docs/extensibility/presets-section.md
docs/extensibility/resources.md

- Change code blocks from the Example sections to YAML
- Minor doc improvements
Resolves #1873

Change code blocks from the Example sections to YAML

---

core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/ExtensibilityList.js
core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
core-ui/src/shared/components/ResourcesList/ResourcesList.js
docs/extensibility/resources.md
resources/web/deployment.yaml

- add `disableEdit` and `disableDelete` flag to general section,
- add  props to List and Details,
- pass props to actions in the List and details,
- add info to docs.
Closes #1670

EXT: add disableEdit and Delete flag

---

core-ui/src/components/Extensibility/components/ExternalLink.js
core-ui/src/components/Extensibility/components/JoinedArray.js
core-ui/src/components/Extensibility/components/tests/JoinedArray.test.js
docs/extensibility/display-section.md
resources/web/deployment.yaml

add `children` support to `JoinedArray`

Widgets in joined array

---

docs/features.md

Add extensibility feature documentation

---

core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/ExtensibilityList.js
core/src/luigi-config/utils/configChanged.js
resources/web/deployment.yaml

- Fix 3611665502: Cannot read properties of undefined (reading 'navigation')
- Fix 3627167219: Cannot read properties of undefined (reading 'kind')

Sentry20220904

---

core-ui/src/components/App/App.js
resources/web/deployment.yaml
tests/tests/cluster/test-cluster-overview.spec.js
tests/tests/namespace/test-resource-upload.spec.js

Remove cy.wait() from tests

---

docs/extensibility/form-section.md
examples/pizzas/configuration/pizzas-configmap.yaml
examples/resources/istio/authorization-policies.yaml
examples/resources/istio/gateways.yaml
examples/resources/istio/service-entries.yaml
examples/resources/istio/sidecars.yaml
examples/resources/istio/virtual-services.yaml

update `SimpleList` in examples to always use children.

Simplelist examples

---

core/src/luigi-config/busola-cluster-params.js
resources/web/deployment.yaml

Fix fetching configs

---

README.md

- ...
- ...
- ...
part of #1875

Update docs with config - json to yaml changes

---

docs/features.md

- ...
- ...
- ...
Closes #1875

align docs to new yaml configs

---

core-ui/package-lock.json
core-ui/package.json
package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml

- Bump react-i18next
- install enzyme, fundamental-react and js-yaml types

Add types for some packages

---

CONTRIBUTING.md

- ...
- ...
- ...
Resolves #1950

Add code guidelines for devs

---

CODEOWNERS

Removing myself as CODEOWNER
- ...
- ...
- ...

Removing myself as CODEOWNER

---

core-ui/src/components/Extensibility/components-form/GenericList.js
core-ui/src/components/Extensibility/components/Columns.js
core-ui/src/components/Extensibility/components/ResourceLink.js
core-ui/src/shared/components/MonacoEditorESM/Editor.scss
resources/web/deployment.yaml

Fix sentry

---

core-ui/src/components/Preferences/Preferences.scss
resources/web/deployment.yaml

fix: Preferences height and font size

---

core-ui/src/components/ApiRules/ApiRulesList.js
core-ui/src/components/ApiRules/components.js
core-ui/src/components/Extensibility/ExtensibilityDetails.js
core-ui/src/components/Extensibility/ExtensibilityList.js
core-ui/src/resources/APIRules/HostAndSubdomain.js
resources/web/deployment.yaml

- Fix issue 3687743692 - Cannot read properties of undefined (reading 'kind')
- Fix issue 3685451824 - Cannot read properties of undefined (reading 'match')
- Fix issue 3719616314 - e.endsWith is not a function
- Fix issue 3725002913 - Cannot read properties of undefined (reading 'name')

Sentry 202211

---

core-ui/src/components/Extensibility/ExtensibilityCreate.js
core-ui/src/components/Extensibility/helpers/index.js
examples/resources/serverless/functions.yaml
resources/web/deployment.yaml

- Fix presets to merge the provided preset option with an empy template
Choosing presets still doesn't work in functions but it's [different topic](https://github.com/kyma-project/busola/issues/2031). You can test the PR with the extensibility gateways/pizzas

fix: ext presets

---

core-ui/src/shared/ResourceForm/useCreateResource.js
resources/web/deployment.yaml

- ...
- ...
- ...
Resolves #2036

Fix resource version on edit

---

core-ui/src/components/Clusters/shared.js
core-ui/src/header/Header.tsx
core-ui/src/shared/hooks/BackendAPI/createHeaders.ts
core-ui/src/shared/hooks/BackendAPI/useFetch.ts
core-ui/src/state/authDataAtom.ts
core-ui/src/state/clusterAtom.ts
core-ui/src/state/clustersAtom.ts
core-ui/src/state/utils/getClustersInfo.js
nginx/nginx.conf

Add possibility to add, remoce and switch clusters

---

core-ui/src/components/Extensibility/ExtensibilityList.js
core-ui/src/shared/components/ResourceGraph/buildGraph/helpers.js
resources/web/deployment.yaml

Sentry fix 28.11.22

---

tests/cypress.json

- Since Otters team fixed Serverless we can bring back apirules and eventing functions

fix: bring back api-rules/eventing tests

---

core-ui/public/defaultConfig.yaml
core-ui/src/components/App/useLoginWithKubeconfigID.ts
core-ui/src/components/Clusters/shared.ts
core-ui/src/components/Clusters/views/ClusterList.js
core-ui/src/components/Preferences/ProtectedSettings.tsx
core-ui/src/hooks/useFeature.ts
core-ui/src/shared/hooks/useGetHiddenNamespaces.ts
core-ui/src/sidebar/Footer/useGetLegalLinks.ts
core-ui/src/state/authDataAtom.ts
core-ui/src/state/clusterAtom.ts
core-ui/src/state/configFeatures/configFeaturesSelector.ts
core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
core-ui/src/state/navigation/externalNodesSelector.ts
core-ui/src/state/navigation/filters/shouldNodeBeVisible.ts
core-ui/src/state/resourceList/resourceListSelector.ts
core-ui/src/state/types.ts
core-ui/src/state/utils/effects.ts

**Testing**
```yaml
config:
features:
KUBECONFIG_ID:
isEnabled: true
config:
kubeconfigUrl: 'http://127.0.0.1:8090'
showClustersOverview: false
defaultKubeconfig: kubeconfig--kyma-prow--nkyma.yaml
```
Closes #2079

kubeconfig id

---

core-ui/src/components/Extensibility/ExtensibilityList.js
resources/web/deployment.yaml

`disableCreate`, `disableEdit` and `disableDelete` don't work on the list view.
- fix simple bug with `features.actions`
- ...
- ...

Fix actions in general for list view

---

core-ui/src/components/App/App.js
core-ui/src/components/Clusters/shared.ts

HandleResetEndpoint

---

core-ui/src/components/App/resourceSchemas/useResourceSchemas.ts
core-ui/src/components/Clusters/components/AddClusterWizard.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
core-ui/src/components/Clusters/views/ClusterOverview/useGetVersions.js

Use recoil state instead of luigi context

---

core-ui/src/components/Extensibility/components/ResourceList.js
examples/pizzas/configuration/pizzas-configmap.yaml

Small fix for resource lists

---

core-ui/src/shared/components/Link/Link.tsx
core-ui/src/sidebar/Footer/Footer.tsx
tests/tests/cluster/test-dashboard-version.spec.js
tests/tests/cluster/test-other-login-options.spec.js

adjust dashboard version and added dataTestId prop

---

core-ui/public/i18n/en.yaml
core-ui/src/components/App/App.tsx
core-ui/src/components/App/ClusterRoutes.js
core-ui/src/components/App/IncorrectPath.js
core-ui/src/components/App/NamespaceRoutes.js
core-ui/src/hooks/useUrl.ts

Handle incorrect path

---

core-ui/src/components/Extensibility/hooks/useVariables.js
resources/web/deployment.yaml

fix broken `$item` in jsonata for `defaultValue`

fix $item in defaultValue

---

core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
resources/web/deployment.yaml

Fix Sentry 12.12.2022

---

examples/resources/configuration/dns-providers.yaml

- ...
- ...
- ...
part of #1956

create configmap for dns-providers

---

core-ui/src/components/Extensibility/ExtensibilityCreate.js
resources/web/deployment.yaml
tests/tests/namespace/run-prepare-functions.spec.js

re-add resetting vars on yaml change
reset vars on preset change

fix reset vars

---

core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
resources/web/deployment.yaml

- Fix widget resource for vars

Fix widget resource for vars

---

Dockerfile.local
core-ui/public/config/defaultConfig.yaml
core-ui/src/state/navigation/extensionsAtom.ts
docs/extensibility/README.md
gulpfile.js
resources/web/deployment.yaml
tests/tests/cluster/test-cluster-configuration.spec.js

fix for missing extensions call

---

core-ui/src/state/navigation/extensionsAtom.ts
resources/web/deployment.yaml

fix extensions

---

core-ui/src/resources/OAuth2Clients/index.js
core-ui/src/state/navigation/categories.ts
resources/web/deployment.yaml
tests/support/views/api-rules-view.js
tests/tests/namespace/test-api-rules.spec.js
tests/tests/namespace/test-oauth2.spec.js

- Fix double navigation for apirules
- fix oauth2clients navigation label

Fix double navigation

---

core-ui/src/resources/Services/ApiRulesList.js
resources/web/deployment.yaml

go to services, reload. should load properly instead of crashing

fix services loading

---

core-ui/src/components/Extensibility/ExtensibilityCreate.js
core-ui/src/components/Extensibility/contexts/Trigger.js
core-ui/src/components/Extensibility/hooks/useVariables.js
core-ui/src/components/Extensibility/plugins/TriggerHandler.js
resources/web/deployment.yaml

1. do not reset values so visibility is not changed
2. do not fire triggers when switching from yaml to form

fix dynamic values even more

---

core-ui/src/components/Extensibility/components/ExternalLink.js
core-ui/src/shared/components/Link/Link.tsx
core-ui/src/sidebar/NavItem.tsx
resources/web/deployment.yaml

- fix isSelected function,
- change `Link` for ExternalLinks,
- adjust icon for ExternalLinks in Extensibility

fix selected leftNav item and change ExternalLink in LeftNav

---

core-ui/src/components/App/IncorrectPath.js
core-ui/src/sidebar/NavItem.tsx
resources/web/deployment.yaml

- Wait for extensions (with it's paths) to load before showing the path not found message
- ...
- ...
Resolves [2187](https://github.com/kyma-project/busola/issues/2187)

Wait for extensions to load to display a redirection error

---

CODEOWNERS
OWNERS_ALIASES

- Add nataliasitko to CODEOWNERS ans OWNERS_ALIASES
- https://github.com/kyma-project/kyma/issues/16378

Add nataliasitko to codeowners

---

core-ui/src/state/extensibilitySchemasAtom.ts
core-ui/src/state/navigation/extensionsAtom.ts
resources/web/deployment.yaml

fix: fetching extensibility Schemas

---

core-ui/src/header/Header.tsx
core-ui/src/header/NamespaceDropdown/NamespaceDropdown.tsx
core-ui/src/sidebar/NavItem.tsx
resources/web/deployment.yaml

add closing namespace nav

---

core-ui/src/header/Header.tsx
resources/web/deployment.yaml

- ...
- ...
- ...
Closes #2204

fix cluster

---

docs/extensibility/form-section.md

- change the values to correct ones (`trigger` and `subscribe`)
- reword the desriptions to better explain why they are in the infinitive

fix trigger docs

---

core-ui/src/state/navigation/extensionsAtom.ts
core-ui/src/state/navigation/sidebarNavigationNodesSelector.ts
core-ui/src/state/resourceList/mapBusolaResourceToNavNode.ts
resources/web/deployment.yaml
tests/support/exceptions.js

- Filter all nodes by the visibility
- ...
- ...
Resolves #2212

Hide extensions of resources not existing on a cluster

---

Dockerfile.local
backend/config/config.yaml
backend/index.js
core-ui/public/kubeconfig
resources/backend/deployment.yaml
resources/web/deployment.yaml

Busola hotfix: kubeconfig path & backend configuration

---

core-ui/src/components/Clusters/views/ClusterList.js
core-ui/src/state/authDataAtom.ts
resources/web/deployment.yaml

- Add bold for active cluster
- Run OIDC flow only if we enter an OIDC cluster - before we run it everytime the page loaded, even if we were on `/clusters`
Fixes #2220

Fix refreshing on /clusters

---

core-ui/public/defaultConfig.yaml
resources/web/deployment.yaml

remove kubeconfig from gardener in defaultConfig

---

core-ui/src/shared/ResourceForm/useCreateResource.js
resources/web/deployment.yaml

- fix of overwriting resources that has changed in the meantime
Resolves #2139 
How to test???
- Open two browser tabs of the same Function
- Click Edit in both tabs to have Edit form opened
- Modify the first one and click update
- In the second one modifiy something different and click update
- 🥳 It works

fix: overwriting resources that has changed in the meantime 

---

core-ui/public/defaultConfig.yaml
core-ui/src/components/Extensibility/helpers/jsonataWrapper.js
examples/resources/configuration/subscriptions.yaml
resources/web/deployment.yaml

- fix readableTimestamp for jsonata,
- enable Extensibility in defaultConfig,
- fix subscriptions config-map.
Closes https://github.com/kyma-project/kyma-dashboard/issues/44

fix readableTimestamp for jsonata

---

CODEOWNERS

remove Daria and Piotr as CODEOWNERS, it was a pleasure to work with both of you

---

core-ui/public/schemas/schema-form.yaml
core-ui/src/components/Extensibility/components-form/StringRenderer.js
docs/extensibility/form-section.md
resources/web/deployment.yaml

- add readOnly prop from schema,
- add info about it to docs.
Closes https://github.com/kyma-project/kyma-dashboard/issues/45

add readOnly prop from schema and add to docs

---

core-ui/src/shared/ResourceForm/fields/K8sNameField.js
docs/extensibility/form-section.md
resources/web/deployment.yaml

fix require name

---

resources/web/deployment.yaml
src/state/navigation/assignToCategories.ts

Sort items in side nav

---

examples/apps/whoami/all.yaml
public/i18n/en.yaml
resources/backend/hpa.yaml
resources/web/deployment.yaml
resources/web/hpa.yaml
src/hooks/useVersionWarning.ts
src/resources/HorizontalPodAutoscalers/HPABehavior.js
src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerDetails.js
src/resources/HorizontalPodAutoscalers/index.ts
src/resources/HorizontalPodAutoscalers/templates.js
tests/integration/fixtures/test-HPA.yaml
tests/integration/tests/namespace/test-HPA.spec.js
tests/integration/tests/namespace/test-navigation.spec.js

- bump version of hpa to `v2`
- remove metrics and minPods from `template` for create and from tests,
- remove handler for unsupported version.
Closes #1566

bump hpa to v2 and adjust non required fields

---

resources/web/deployment.yaml
src/state/navigation/extensionsAtom.ts

fix: comparing extensions' properties

---

docs/extensibility/form-section.md
public/schemas/schema-form.yaml
resources/web/deployment.yaml
src/components/Extensibility/components-form/ResourceRefRenderer.js
src/components/Extensibility/components-form/ResourceRenderer.js

- add `filter` to ResourceRef widget
- fix `filter` in Resource widget
- add docs for missing properties in the above widgets
- update schema-form
Closes #2307

fix: synchronize Resource and ResourceRef API

---

docs/features.md
public/defaultConfig.yaml
resources/web/deployment.yaml
tests/integration/tests/namespace/test-settings.spec.js
tests/integration/tests/namespace/test-stateful-sets.spec.js

- Make `kube-public` namespace hidden by default

On local busola hide only kube-public

---

resources/web/deployment.yaml
src/resources/HorizontalPodAutoscalers/HPASubcomponent.js

- fix displaying Replicaset related HPAs
Closes #2310

fix: display HPAs on Replicaset details view

---

resources/web/deployment.yaml
src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.scss

- Add border and margin to dropdown over the code editor

Tiny UI fix

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/SimpleList.js
src/components/Extensibility/components-form/SimpleList.scss

fix simple list styling

---

resources/web/deployment.yaml
src/components/Clusters/views/EditCluster/EditCluster.js

Fix edit cluster

---

public/schemas/schema-form.yaml
resources/web/deployment.yaml
src/components/Extensibility/components-form/MonacoRenderer.js

- add `YAML` language to GenericList's template in schema form
- handle non given language in CodeEditor
Closes #2230

fix: add language to GenericList's template

---

resources/web/deployment.yaml
src/hooks/useGetSchema.js
src/shared/ResourceForm/inputs/ComboboxInput.js

- fix getting Service schema
- fix Combobox input bug that didn't clear the value after removing it

fix: handling undefined in ComboboxInput

---

resources/web/deployment.yaml
src/components/Extensibility/components/Badge.js

- change the old way of jsonata usage to the new one that returns array of value and an error
Closes #2051

fix: badge highlights jsonata function usage 

---

resources/web/deployment.yaml
src/resources/OAuth2Clients/index.js
tests/integration/tests/namespace/test-oauth2.spec.js

fix: change  oauth2clients label

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/MultiCheckbox.js
src/components/Extensibility/components-form/StringRenderer.js
src/components/Extensibility/components/Badge.js
src/components/Extensibility/components/ExternalLink.js
src/components/Extensibility/components/Text.js
src/components/Extensibility/components/tests/Table.test.js
src/components/Extensibility/components/tests/Widget.test.js

- Unify translations in components-form
- Add translations in components

Translations

---

public/i18n/en.yaml
resources/web/deployment.yaml
src/components/App/IncorrectPath.js

- add checking url for extensions,
- add redirect to custom resources details view if extensibility view doesn't exist.
Closes #1672

fix redirect for non existing extension link

---

resources/web/deployment.yaml
src/sidebar/Sidebar.scss
src/state/navigation/assignToCategories.ts

How to reproduce?
Take a look at #2341
Add `isEnabled` to that feature
Closes #2341

fix: remove children icon in the category that already exists

---

resources/web/deployment.yaml
src/shared/ResourceForm/fields/DataField.js

- Allow data entries that starts with a dot for example:
```
data:
.metadata: sth
```

Allow data entries that starts with a dot

---

resources/web/deployment.yaml
src/shared/hooks/BackendAPI/useGet.js
src/state/authDataAtom.ts
src/state/navigation/assignToCategories.ts

- remove flag which blocked silent renew of token,
- add additional `setupVisibilityEventsHooks` event for page visibility,
- add `useCallback` to refetch,
- change `React.use...` to `use...`.
Closes #2347

fix: silent renew token

---

resources/web/deployment.yaml
src/components/CustomResources/CustomResources.js

After all namespace task we forgot to remove debug `<<{namespace}>>` in CR.js
- ...
- ...
- ...

remove debug

---

resources/web/deployment.yaml
src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts

- ...
- ...
- ...
Closes #2359

fix switch context on cluster overview

---

resources/web/deployment.yaml
src/resources/Roles/helpers.js

- fix `core-api-group` for preset,
- ...
- ...

fix all permissions Role preset

---

resources/web/deployment.yaml
src/resources/DaemonSets/DaemonSetCreate.js

fix daemonSets

---

resources/web/deployment.yaml
src/resources/Subscriptions/SubscriptionDetails.js

fix subscriptions

---

resources/web/deployment.yaml
src/components/App/NamespaceRoutes.tsx

- Allow to see resource view without rights to namespace itself

Allow to see resource view without rights to namespace itself

---

CODEOWNERS
OWNERS_ALIASES

remove Lyczeq and add valentin

---

CODEOWNERS
OWNERS_ALIASES

remove mmitoraj

---

resources/web/deployment.yaml
src/resources/Deployments/DeploymentCreate.js
src/resources/Namespaces/NamespaceCreate.js
src/shared/hooks/useSidecarInjection.js

- ...
- ...
- ...
Closes #2378

fix for sidecar injection

---

resources/web/deployment.yaml
src/sidebar/Footer/useGetBusolaVersion.ts

fix regex for versions

---

resources/web/deployment.yaml
src/shared/components/GenericList/SortModalPanel.js

- Sort-List-Dialog closes now after sorting

Sort-List-Dialog closes now after sorting

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/ResourceRenderer.js

Fix resource widget

---

resources/web/deployment.yaml
src/shared/hooks/BackendAPI/config.js

- ErrorResponse: Refresh token is invalid or expired.

Sentry issue 3872900555
