kyma-project/busola

README.md
backend/package.json
package.json
scripts/npx-release.sh

- It turns out we can't `npm publish` from the root folder - all the libraries from the root package.json would be installed. Instead, I've added a script `scripts/npx-release.sh`, which copies valid name and version from root package.json into backend one, runs `npm publish` from there and rollbacks unnecessary changes.
- Remove mysterious `localhost` file.

Rework npx release

---

core/src/luigi-config/navigation/navigation-data-init.js
core/src/luigi-config/navigation/static-navigation-model.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/test/ServiceInstanceInfo.test.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceRowRenderer.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.component.js
service-catalog-ui/src/components/ServiceInstanceList/test/ServiceInstanceList.test.js

- It looks like `keepSelectedForChildren` is MANDATORY if a node has any children
- Add preload for SC
- Change links in SC

Fix static catalog nodes

---

core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
core-ui/src/components/ApiRules/ApiRuleStatus/test/ApiRuleStatus.test.js

Well, despite creating like 20 apirules I didn't manage to reproduce this bug, but I have seen it myself before, so I decided to just add a bonus check for them, to be safe.
- Add a check for `apiRule.status`
- Add more test cases for APIRule status

Fix APIRule status bug

---

core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/helpers.js
core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/__snapshots__/helpers.test.js.snap

- Use selector instead of ownerRef during service creation
**Testing**
- Create a workload from namespace details (you can use `nginx:latest` at targetPort `80`). Create apirule for the service (make sure to use `noop`, then enter the apirule `host` in the browser.

Fix Workload creation

---

core-ui/src/components/Predefined/Details/Replicaset.details.js

- Add ready pods display to ReplicaSet details
- Resolve `key` issues

Add status pods to RS details

---

core-ui/src/components/Predefined/List/ServiceBrokers.list.js
core-ui/src/components/Predefined/List/index.js

- As in title. I decided not to style url as link, because it's a internal address anyway.

Add status and url to Service Brokers list

---

resources/web/deployment-service-catalog.yaml
service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js

Resolves https://github.com/kyma-project/kyma/issues/11009 on Busola side.
In short, `serviceClassRef.name` and `servicePlanRef.name` (and its cluster-wide variants) should not be provided. We should use `serviceClassExternalName` and `servicePlanExternalName` instead (and only!). Addmission hook fills the `ref` fields automatically basing on the `externalName` fields provided.
- ...
- ...
- ...

Fix serviceInstance creation

---

core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
core-ui/src/index.scss
core-ui/src/shared/components/Secret/SecretData.js
core-ui/src/shared/components/Secret/test/SecretData.test.js
resources/web/deployment.yaml

- Display error on API Rule create / edit error
- Make sure checkboxes are visible on Safari
- Fix secrets details - they were doubly encoded
Closes https://github.com/kyma-project/kyma/issues/10321

Show error on api rule create/edit error

---

backend/package-lock.json
backend/package.json
core/src/luigi-config/auth.js
core/src/luigi-config/navigation/navigation-data-init.js
package-lock.json
package.json

- Remove init params on logout
- Add @babel/runtime to backend, as npx mode requires it (this happened after adding `json-url` to backend)
```
npx @kyma-project/busola@0.0.1-rc.6
Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /Users/i515358/.npm/_npx/44792/lib/node_modules/@kyma-project/busola/node_modules/json-url/dist/node/index.js
- /Users/i515358/.npm/_npx/44792/lib/node_modules/@kyma-project/busola/index-npx.js
```
- Release new npx mode version

Logout fixes

---

core/src/assets/login.js
resources/web/deployment.yaml

To reproduce: create NS with name 'm'. It won't show up on namespace list.
- In case of link-created init params, we split the system namespaces in initParams.js, but in case of kubeconfig drag-n-drop created init params, they weren't split - and 'm' indeed belongs in long string of 'kyma-syste**m** kube-syste**m**...', causing the bug.

Fix system namespaces filtering

---

core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
package-lock.json
package.json
resources/web/deployment.yaml

- Turns out `application` backendmodule isn't required for displaying subscription section on lambda details - remove it!
- Bump NPX for rc.8

Remove application module from subscription section requirements

---

core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/ApiRuleFormHeader.js
core-ui/src/components/ApiRules/ApiRulesList/ApiRulesList.js
core-ui/src/components/ApiRules/ApiRulesList/components.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
core-ui/src/components/Lambdas/hooks/useCreateLambda.js
core-ui/src/components/Predefined/Details/ApiRules.details.js
core-ui/src/components/Predefined/Details/Application/ApplicationServices.js
core-ui/src/components/Predefined/Details/Application/NamespaceBindings.js
core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
core-ui/src/components/Predefined/Details/Namespace/NamespaceWorkloads/NamespaceWorkloads.js
core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
core-ui/src/components/Predefined/Details/Pod/Pod.details.js
core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.js
core-ui/src/components/Predefined/Details/Roles/Rules.js
core-ui/src/components/Predefined/List/ApiRules.list.js
core-ui/src/components/Predefined/List/Function/Functions.list.js
core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInstancesTable/ServiceClassInstancesTable.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceRowRenderer.js
service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.js
shared/components/ResourceDetails/ResourceDetails.js
shared/components/StringInput/StringInput.js

- Use `navigationContext`:
- `${resource}`s on list
- `${resource} on :details
- I used the `resourceType` as a values on lists, as we use it in generic resource details.
- Fix some `key` warnings
- Fix catalog service class navigation
- Fix namespace details lowercase breadcrumb

Rework navigation contexts

---

resources/web/deployment-service-catalog.yaml
resources/web/deployment.yaml
shared/components/ResourceDetails/ResourceDetails.js
shared/components/ResourcesList/ResourcesList.js
shared/contexts/YamlEditorContext.js

- As in title. Also, rename `json` occurences to `yaml`.

Hide drawer on namespace change

---

core-ui/src/components/Clusters/components/AuthForm.js
core-ui/src/components/Clusters/components/ClusterConfiguration.js
core-ui/src/components/Clusters/components/test/ClusterConfiguration.test.js
resources/web/deployment.yaml

- auto-fill the input fields on the "OIDC login" form reveal
- re-fill the inputs on context change
- add unit tests 🎆 

Auto-fill OIDC data when available in the kubeconfig

---

core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
core-ui/src/index.js
core-ui/webpack.config.js
package-lock.json
package.json
resources/web/deployment.yaml
service-catalog-ui/src/index.js
shared/index.js
shared/package-lock.json
shared/package.json

- So it looks like using `setupMonaco` multiple times breaks the editor - sometimes.
- I've also moved the `@monaco-editor/react` from root package.json to shared, so we always use a shared-wrapped version.

Fix monaco

---

core/src/luigi-config/init-params/constants.js
core/src/luigi-config/init-params/init-params.js
core/src/luigi-config/kubeconfig-id.js
core/src/luigi-config/luigi-config.js
core/src/luigi-config/navigation/previous-location.js
resources/backend/deployment.yaml
resources/web/deployment.yaml
tests/support/enkode.js
tests/tests/login-enkode.spec.js

- Handle kk-id during app bootstrap
- Add test case
Testing:
- So, we by default we can't login to kk-id cluster - `kymatest` authenticates them, and we have no access here to add `callbackUrl`. BUT if we change the local port from 4200 to 8000, then it will work!
- This means we can't really test it on our cluster.
- Another way would be to run a simple backend:
```
const express = require("express");
const cors = require("cors");
const port = 3030;
const app = express();
app.use(cors());
const kk = {/* drop a oidc kubeconfig here */};
app.get("/*", (req, res) => {
res.send(kk);
});
app.listen(port, () => {
console.log(`Example app listening at http://localhost:${port}`);
});
```
and make the `kubeconfigId` (can be easily changed via …

Handle kubeconfig ID param

---

core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
core-ui/src/components/Predefined/Details/CronJobs/CronJobJobs.js
core-ui/src/components/Predefined/Details/Job/Job.details.js
core-ui/src/components/Predefined/Details/Job/JobCompletions.js
core-ui/src/components/Predefined/Details/Job/JobConditions.js
core-ui/src/components/Predefined/Details/Replicaset.details.js
core-ui/src/components/Predefined/Details/ResourcePods.js
core-ui/src/components/Predefined/Details/index.js
core-ui/src/components/Predefined/List/Jobs.list.js
core-ui/src/components/Predefined/List/index.js
core/src/i18n/en.yaml
core/src/luigi-config/navigation/static-navigation-model.js
resources/web/deployment.yaml

- add job list and details
- create a common `ResourcePods` component for pod lists
- **important** use the `ResourcePods` for replica sets - not 100% sure if the results are correct, as the original fetched everything and filtered manually (but since replica sets have all the necessary references, and I didn't notice any differences, I assume it's correct)

Job workloads

---

resources/web/deployment.yaml
shared/components/KeyValueForm/KeyValueForm.js
shared/components/KeyValueForm/KeyValueForm.scss
shared/hooks/BackendAPI/useGet.js

- We didn't compare lists lengths in `useGet`, so the hook didn't update the list. Fixed!
- I was to check for Function's variables list - it refreshes properly, no work done here.
- Use `FormTextArea` instead of `textarea` in ConfigMap (& Secret) editor, simplifying CSS and making it react to theme changes.

Fix lists refresh & CM create styles

---

core/src/luigi-config/busola-cluster-params.js
core/src/luigi-config/cluster-management.js
core/src/luigi-config/kubeconfig-id.js
core/src/luigi-config/luigi-config.js
core/src/luigi-config/navigation/navigation-data-init.js
core/src/luigi-config/utils/target-cluster-config.js
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml
shared/contexts/ThemeContext.js
tests/cypress.json
tests/tests/cluster-configuration.spec.js

- Add possibility to configure Busola by target cluster. The order is as follows: init params *override* configmap from target cluster *overrides* Busola cluster configmap *overrides* default built-in config.
- I've placed the configmap (`busola-config`) in kube-public namespace, [as it seemed to fit here](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#viewing-namespaces).
- Add a test for loading the config.
- Shut up the `lint-staged` warning (that yellow one on `git commit`).
- Fix Monaco editor's theme bug.
Testing:
- `kmain` - configmap with custom `externalLinks`
- `main` - configmap with custom `externalLinks`
- `llama` - no configmap here.

Handle params from target cluster

---

Dockerfile.local
core/src/luigi-config/cluster-management/cluster-management.js
core/src/luigi-config/cluster-management/clusters-storage.js
core/src/luigi-config/init-params/init-params.js
resources/web/deployment.yaml

- Replace `defaultStorage` for Docker builds
- Propagate storage to other scripts
Testing:
- You can check out Docker image: `docker run -p 3001:3001 wawrzyn321/busola-local-347`

Store configuration in sessionStorage in Docker

---

core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
core-ui/src/index.js
core/src/luigi-config/luigi-config.js
resources/web/deployment.yaml

- I've added a handler in `core` and `core-ui`.
- I've also changed the default language in `core-ui` - it was `undefined` at start (before proper one came from `MicrofrontendContext`), causing some false positive warnings.
- There's no detection of "dev vs prod" in `core`, as we always build into `production`... There won't be many changes anyways.

Warn on missing translation key

---

backend/common.js
backend/index.js
backend/package-lock.json
backend/package.json
core/src/luigi-config/auth/auth.js
nginx/nginx.conf
resources/backend/deployment.yaml
resources/ingress.yaml
resources/web/deployment.yaml

- Disable the `X-Powered-By: Express` header.
- Add `Cache-Control`. Funny thing, it looks like none of those headers was actually sent, so I moved 'em to `location` directive. Just copied them, we could use `include` for this, but I don't think it's worth it.
- Add additional data to 50x errors: request id. I'm not proud of modifying original `Request` by adding an `id` prop, so ideas are welcome.
- I've disabled the version (with `server_tokens off` directive).
- A matter of nginx version (and testing it!): we have actually 2 nginxes - one in `web` pod, another one in ingress controller.
- `web` - just curl the Busola url with http (it should 308 you to https)
- ingress - curl invalid url, e.g. …

Backend security fixes

---

core-ui/src/components/Predefined/Create/ReplicaSets/ReplicaSets.create.js
core-ui/src/shared/components/Deployment/ContainersViews.js
core/src/i18n/en.yaml
core/src/luigi-config/communication.js
resources/web/deployment.yaml
tests/cypress.json
tests/tests/test-replica-sets.spec.js

Adding automated tests for Replica sets.
- Added test for creating Replica set
- Added tests that check details and list views
- Added test that modifies a resource and checks new values
- Modified Replica Set to use Edit button
- Added translation
- Fix bug: After deleting a pod in Cypress, there was a redirect to the Cluster Overview page
Related issue:  #555

Automated tests for Replica sets

---

core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
core-ui/src/components/Predefined/Create/Jobs/SpecSection.js
resources/web/deployment.yaml

I found a bug that allowed a user to change the value of the restartPolicy in the Job. After a change and update the error from backend appeared which said that this field is immutable. 
- set restartPolicy as readOnly after a creation

Set restartPolicy in Jobs as read only

---

core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
core-ui/src/shared/ResourceForm/fields/Editor.js
core-ui/src/shared/components/ReadonlyEditorPanel.js
core/src/index.css
resources/web/deployment.yaml
shared/components/SideDrawer/SideDrawer.js
shared/contexts/YamlEditorContext/YamlContent.js

Fixes scrolling page when mouse is over a monaco container and removes the scrollbars from the main iframe container to disallow double scrolls.

Fix scrolling page when mouse is over monaco container

---

tests/tests/test.settings.spec.js

Fixes cypress test.settings to wait for a created config map before fetching the list.

Fix test.settings to check for created config map

---

core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
core-ui/src/components/Lambdas/components/TabsWithActions/TabsWithActions.scss
core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
core-ui/src/components/Predefined/Details/Application/ApplicationStatus.js
core-ui/src/components/Predefined/Details/Namespace/NamespaceStatus.js
core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
core/src/i18n/en.yaml
core/src/luigi-config/navigation/navigation-data-init.js
resources/web/deployment.yaml
shared/components/StatusBadge/StatusBadge.js
shared/hooks/useProtectedResources.js

- `StatusBadge`: don't prepend status text to tooltip message if `additionalContent` is set.
- Namespaces: tooltips stolen from [sources](https://raw.githubusercontent.com/kubernetes/api/master/core/v1/types.go) (`NamespacePhase`)
- Services: no statuses here
- Applications: seeing from types.go file (`components/application-operator/pkg/apis/applicationconnector/v1alpha1/types.go`, `release-1.25` branch), status is just a string.
- Addons & ClusterAddons: 2 statuses, one for `AddonStatus` (either `Ready` or `Failed`, no tooltip), one for `RepositoryStatus` (of type `string`, tooltip when status is not `Ready`)
(`kyma1.25/installation/resources/crds/service-catalog-addons/addonsconfigurations.addons.crd.yaml`)
- API Rules: they were …

Migrate discovery and network, namespaces, integration views to new translatable labels

---

Dockerfile
Dockerfile.local
resources/web/deployment.yaml
shared/components/KeyValueForm/test/KeyValueForm.test.js
shared/components/StatusBadge/test/StatusBadge.test.js
shared/hooks/BackendAPI/tests/useGet.test.js
shared/hooks/BackendAPI/useGet.js

- Allow up to 2 consecutive requests to fail until displaying an error
- Fix `shared` tests
- Enable `shared` tests on CI
Closes #694

Add error tolerancy for useGet

---

core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
resources/web/deployment.yaml
tests/README.md
tests/support/login-commands.js
tests/tests/test-replica-sets.spec.js

Adds an option to run Cypress tests on a cluster autheticated via OICD. Autodetects the authentication type. 
If you use OIDC, remember to provide a username and password, like for example: 
CYPRESS_OIDC_PASS=XXXXX CYPRESS_OIDC_USER=xxx@xxx.com $(npm bin)/cypress run --browser chrome
Resolves #835

Option to login through OIDC during tests

---

core-ui/src/shared/ResourceForm/fields/DataField.js
core-ui/src/shared/ResourceForm/fields/DataField.scss
resources/web/deployment.yaml
tests/tests/test-secrets.spec.js

Fix switching focus on enter in textarea in config maps
Fixes #820

fix switching focus on enter in textarea in config maps

---

core-ui/src/components/NoPermissions/NoPermissions.js
core-ui/src/components/NoPermissions/NoPermissions.scss
core-ui/src/index.scss
core/src/i18n/en.yaml
core/src/luigi-config/communication.js
core/src/luigi-config/navigation/navigation-data-init.js
resources/web/deployment.yaml

**Testing**
* Unassign all your roles on https://apskyxzcl.accounts400.ondemand.com/admin/#/users
* Add yourself a role binding (e.g. `/cluster/shoot--hasselhoff--kmain/namespaces/default/rolebindings/details/ns2` - not that's a `Role`, not a `ClusterRole`)
* Use the following kubeconfig (basically OIDC kubeconfig, BUT without a _namespace_ in _context_)
```
apiVersion: v1
kind: Config
current-context: shoot--hasselhoff--kmain-oidc
contexts:
- name: shoot--hasselhoff--kmain-oidc
context:
cluster: shoot--hasselhoff--kmain-oidc
user: shoot--hasselhoff--kmain-oidc
clusters:
- name: shoot--hasselhoff--kmain-oidc
cluster:
server: 'https://api.kmain.hasselhoff.shoot.canary.k8s-hana.ondemand.com'
certificate-authority-data: >-
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5akNDQWQ2Z0F3SUJBZ0lRTlpWYl …
```

Improve User Experience for users with Namespace Access only

---

core-ui/src/resources/OAuth2Clients/OAuth2ClientDetails.js
core-ui/src/resources/OAuth2Clients/OAuthClientSpecPanel.js
resources/web/deployment.yaml

I decided to not display an error/loading message when a secret doesn't exist because this is what we usually do in other resources(SC/PV/PVC). If a `secretName` value exists but the secret doesn't, the name of the secret is displayed but without a link to the details.
- Remove an error/loading message on oauth details view
- Add displaying a link to the secret if it exists
Closes #1106

Remove messages on OAuth details view. Display a link to secret if it exists 

---

core-ui/src/resources/DnsEntries/DnsEntryList.js
core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
resources/web/deployment.yaml

When a resource doesn't exist UI is displaying resourceName without space in some cases.
- Change `||` to `,` in calling function
- ...
- ...
Closes #1227

Repair calling prettifyNamePlural function

---

core-ui/src/resources/Pods/index.js
resources/web/deployment.yaml

- Sooo Pod can be connected not only by `pod.spec.containers[*].env`, but also by `pod.spec.volumes` 🤦 
Closes #1331

Handle CMs & Secrets connected to Pod via volume

---

core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/CommitmentGraph.js
core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/queries.js
resources/web/deployment.yaml

- Don't show loading indicator on Nodes list and `CommitmentGraph` after it was loaded once.
- Fix small bug with `CommitmentGraph` - the little arrow at "Utilized" wasn't cleared properly.
**Testing**
- For Nodes list, change `core-ui/src/shared/hooks/usePrometheus.js:180` - instead of `step * 1000` (usually 1 minute), use something like `5000` (5s).
- For graph, change the same thing in `core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/useMetricsQuery.js:30`.
Closes #1384

Prevent layout shifts on cluster overview

---

core-ui/src/components/Extensibility/components/Plain.js
core-ui/src/components/Extensibility/components/Table.js
core-ui/src/shared/components/GenericList/GenericList.js
core/src/i18n/en.yaml

- Fixed the bug of incorrect Table Widget breaking the details page
- Added a key prop to remove console errors
- Added a prop to the GenericList component that is displayed when there's an incorrect extensibility configuration 
- Added translations
Resolves #1440

Fix incorrect Table Widget to not break the page 

---

core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
core-ui/src/components/Extensibility/helpers.js
core-ui/src/components/Extensibility/metadataSchema.js
docs/extensibility/form-widgets.md
resources/web/deployment.yaml

- Move workaround for `type: object` from ResourceRefs to helpers
- Add workaround to KeyValuePairRenderer
- Bring back `type: object` to metadataSchema
Closes #1558

Fix KeyValuePairRenderer

---

examples/pizzas/configuration/pizzas-configmap.yaml

- Adjust usage of `GenericList` widget. Without that the expanded Form>Toppings>Topping section was empty.
- Add missing translations for `ownerReferences` properties

Fix pizzas form example

---

core-ui/src/components/App/resourceSchemas/resourceSchemas.worker.js
core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/Editor.js
core-ui/src/hooks/useGetSchema.js
core-ui/src/resources/Namespaces/NamespaceCreate.js
core-ui/src/resources/Namespaces/templates.js
core-ui/src/shared/ResourceForm/components/ResourceForm.js
core-ui/src/shared/ResourceForm/fields/Editor.js
core-ui/src/shared/components/MonacoEditorESM/Editor.js
core-ui/src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
core-ui/src/shared/components/SchemaViewer/SchemaViewer.js
resources/web/deployment.yaml

- As in connected issue - now we pass the schemaId just once, instead of computing it each time. It will be always valid:
- On `create` from, it's taken from template, which we define - we it's valid.
- On `edit` form, it's provided by object which must have been valid already to be created.
- Adjust error handling for schema worker
Closes #1329

Fix schema inferring

---

core-ui/src/components/BusolaExtensions/helpers.js
resources/web/deployment.yaml

- use `source` instead of `path` for list and details
- don't save `type`

fix generated extension code

---

backend/common.js
resources/backend/deployment.yaml

**Testing**
Use the following code in our App.js - it makes continuous calls that return 503/502:
```
import { useSingleGet } from 'shared/hooks/BackendAPI/useGet';
export default function App() {
const fetch = useSingleGet();
setInterval(async () => {
try {
console.log(
await fetch(
'/api/v1/namespaces/kyma-system/services/monitoring-prometheus:web/proxy/api/v1/status/runtimeinfo',
),
);
} catch (e) {
console.log(e);
}
}, 2000);
return null;
```

Proxy: change 503 to 502

---

core-ui/package-lock.json
core-ui/package.json
core-ui/src/shared/hooks/useValidateResourceBySchema/useValidateResourceBySchema.js
resources/web/deployment.yaml

Current schema validator doesn't work on production environment becuase it uses `eval` and our security policy blocks it. We should change the validation library.
- Replace schema validation library
- `url` library was installed because it is required in the library above, according to the [issue](https://github.com/tdegrunt/jsonschema/issues/367)

change schema validation library

---

core-ui/src/components/Functions/config.js
core-ui/src/components/Functions/constants.js
core-ui/src/components/Functions/helpers/runtime/runtime.js
core-ui/src/components/Functions/helpers/runtime/test/runtime.test.js
examples/resources/serverless/functions.yaml
resources/web/deployment.yaml
tests/tests/namespace/run-prepare-functions.spec.js

- removed nodejs12 - user should not be able to use nodejs12 from kyma UI
See also https://github.com/kyma-project/kyma/issues/15771

remove deprecated nodejs12 (and nodejs10)

---

Dockerfile.extensions.local
Dockerfile.local
Makefile
resources/web/deployment.yaml

- Don't build `kyma-dashboard` image, as it's built in [kyma-dashboard](https://github.com/kyma-project/kyma-dashboard/) - so remove `Dockerfile.extensions.local`.
- I decided not to remove Gulp & npm scripts entries (e.g. `pack-extensions`), as well as docs (`Embedding an extension in Busola` in `docs/extensibility/README.md`) since some open-source Busola user may use it.

Cleanup build process: remove extensions

---

core-ui/src/components/HelmReleases/decodeHelmRelease.js
resources/web/deployment.yaml

- String.fromCharCode.apply returns Maximum call stack size exceeded on bigger objects
- Change it to TextDecoder

Fix maximum call stack size exceeded in helm releases and secrets

---

resources/web/deployment.yaml
src/resources/ServiceAccounts/index.ts
src/shared/components/ReadableCreationTimestamp/ReadableCreationTimestamp.tsx

Changes:
- improve readable timestamp to show remaining time
- fix matching ServiceAccounts with its Secrets on ResourceGraph 
How to test?
1. Use the extension from the following [PR](https://github.com/kyma-project/kyma-dashboard/pull/74)
2. Choose `istio-system` namespace
3. Go to the list view of the extension
4. `Expiration time` column should display `in X days` instead of `in X minutes`
part of https://github.com/kyma-project/busola/issues/1958

feat: improve readable timestamp to show remaining time & fix: ResourceGraph

---

Dockerfile
Dockerfile.local
Makefile
resources/web/deployment.yaml
src/sidebar/Footer/useGetBusolaVersion.ts

In order to migrate to image-builder and remove privileged mode from build jobs `sed`'ing needs to be moved into the Dockerfile with usage of `--build-arg`.
Additionally update getGithubLink logic to parse new tag format. This should be safe and always return at least a 1 object array.
https://github.com/kyma-project/test-infra/issues/5891

Add TAG_DEFAULT_TAG build-arg to Dockerfiles

---

resources/web/deployment.yaml
src/components/Extensibility/components/JoinedArray.js

- fix displaying joinedArray break.

fix displaying JoinedArray break

---

resources/web/deployment.yaml
src/components/Clusters/views/ClusterOverview/ClusterStats.js
src/resources/Namespaces/AllNamespacesDetails.js
src/resources/Namespaces/NamespaceDetails.js
src/resources/Namespaces/NamespaceDetails.scss
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
src/resources/Namespaces/ResourcesUsage.js
src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
tests/integration/tests/namespace/test-namespace-overview.spec.js

- changed widgets look in NamespaceOverview
- removed tooltips for Pods and Deployments card

Change widgets in NamespaceOverview

---

resources/web/deployment.yaml
src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
src/shared/components/EmptyListComponent/EmptyListComponent.tsx
src/shared/components/ResourcesList/ResourcesList.js
tests/integration/tests/cluster/test-cluster-validation.spec.js

- fixed displaying Create button on all namespaces list view
- fixed Horizontal Pod Autoscalers header

fix: create button on all namespaces list view

---

resources/web/deployment.yaml

- Use `busola web` as `europe-docker.pkg.dev/kyma-project/prod/busola` contains backend not the web

fix: set correct image for busola web

---

src/resources/Namespaces/ResourcesUsage.js
src/resources/ResourceQuotas/ResourceQuotaList.js

- According to the docs: https://kubernetes.io/docs/concepts/policy/resource-quotas/#compute-resource-quota, the request.cpu and request.memory can be also put just in cpu and memory. Cover this scenario

fix: Display correct value for resource quota when spec is not in `requests`

---

src/components/KymaModules/KymaModulesAddModule.js

- fixed not being able to add modules when there are none initially

fix: Not able to add modules when there are none initially

---

src/components/Clusters/views/ClusterOverview/ClusterValidation/Scan.ts
src/components/Extensibility/helpers/jsonataWrapper.ts
src/state/navigation/extensionsAtom.ts
src/state/navigation/filters/permissions.ts
src/state/permissionSetsSelector.ts
src/state/utils/getConfigMaps.ts
tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js

- restricted users with cluster-wide access to Config Maps, fetched on a cluster level
- restricted user with no cluster-wide access to Config Maps, but full access on namespace level, fetch namespace-wide config maps

fix: incorrect permissions for restricted users

---

src/components/Extensibility/ExtensibilityDetails.js
src/components/Extensibility/ExtensibilityInjections.js
src/shared/ResourceForm/fields/MultiInput.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx

- removed empty space for empty health section
- fixed console errors

fix: remove empty space for empty health section

---

src/components/KymaModules/KymaModulesCreate.js
src/components/KymaModules/KymaModulesCreate.scss
src/components/KymaModules/KymaModulesList.js
src/shared/ResourceForm/components/ResourceForm.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/ResourceDetails/ResourceDetails.js

- fixed Modules form height, that was causing unnecessary scroll
- fixed discard changes not working for Modules edit

fix: discard changes and unnecessary scroll in Modules form

---

src/shared/components/ResourceCreate/ResourceCreate.js
tests/integration/support/create-edit-support.js

- Force footer to be at the bottom

Fix footer position

---

tests/integration/cypress.config.js
tests/integration/tests/cluster/test-cluster-configuration.spec.js
tests/integration/tests/cluster/test-edit-cluster.spec.js
tests/integration/tests/cluster/test-login-kubeconfigID.spec.js
tests/integration/tests/cluster/test-other-login-options.spec.js

- fix tests after changing gardener flow
Closes #2511

fix: Fix tests after changing gardener flow

---

src/components/Clusters/components/oidc-params.ts
src/components/Clusters/components/test/oidc-params.test.js

This PR addresses an isssue with the current handling of the `client_secret` in busola. It does not support equal signs (`=`) within the value, leading to the failure of the oidc flow. 

fix(oidc): client secret may contain equal signs

---

public/i18n/en.yaml
src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesAddModule.scss
src/components/KymaModules/ModulesCard.js

see issue https://github.com/kyma-project/busola/issues/3031

feat: adjust module cards

---

src/shared/components/GenericList/GenericList.js
src/shared/components/GenericList/GenericList.scss

- add cursor pointer CSSes
- fix setting up a className
See also #3011 

fix: cursor pointer on GenericList

---

src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesList.js

fix: empty module list

---

docs/extensibility/statics.md
src/state/navigation/extensibilityNodesExtSelector.ts
src/state/navigation/extensionsAtom.ts

- added external nodes for statics
- adjusted documentation
#3112 

feat: add external nodes for statics

---

src/shared/contexts/NotificationContext.tsx
src/styles/index.scss
tests/integration/support/commands.js

- switched toasts from UI5 messagestrip to UI5 toast
#3000 

fix: UI5 toast component

---

src/components/Clusters/views/ClusterList.js
src/components/Extensibility/helpers/index.js
src/shared/components/GenericList/GenericList.js
src/shared/components/GenericList/GenericList.scss
src/shared/components/GenericList/Pagination/Pagination.scss
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourcesList/ResourcesList.js
src/shared/helpers/linkExtractor.tsx
src/shared/hooks/useProtectedResources.js
src/styles/index.scss
tests/integration/support/commands.js
tests/integration/tests/namespace/test-reduced-permissions.spec.js

- Protected resource icon is clickable and opens a popover instead of the tooltip on hover interaction
- Protected resource icon in the table is now right next to the name instead of in a separate column
- removed spacing after last table item
- ClusterList: entire row is now navigateable, removed UI5link from name cell
- text in TableRows can now be selected without executing the onClick
#3011 

feat: uxc tables improvements

---

.github/workflows/busola-backend-build.yml
.github/workflows/busola-local-build.yml
.github/workflows/busola-web-build.yml
Dockerfile
Makefile

- added Busola web build to Github actions
- added Busola backend build to Github actions
- removed test job from Busola local

feat: move Busola web and backend build to github actions

---

docs/extensibility/60-form-widgets.md
public/schemas/schema-form.yaml
src/components/Extensibility/components-form/StringRenderer.js

- Adds a `disableOnEdit` property for `Text` widgets. Similar to the `Name` widget. 
Fixes issue #3116 , raised by myself. Reasoning for the feature is in the issue.

feat: disableOnEdit Text widget

---

src/components/Extensibility/contexts/DataSources.tsx

- Pass fallback namespace to datasources so on extensibility lists datasources can be filtered by current namespace
https://github.com/kyma-project/busola/issues/2574

feat: Pass fallback namespace to datasources

---

public/i18n/en.yaml
src/resources/Ingresses/IngressCreate.js
src/resources/Ingresses/IngressDetails.js
src/resources/Ingresses/IngressSpecification.js
src/resources/Ingresses/IngressStatus.js
src/resources/Ingresses/IngressStatus.scss
src/shared/components/ConditionList/ConditionList.tsx
src/shared/components/ExpandableListItem/ExpandableListItem.tsx
tests/integration/fixtures/test-ingress.yaml
tests/integration/tests/namespace/test-ingresses.spec.js

- enhance Ingress details view
- adjust tests
Closes #3067 

feat: enhance Ingress details view

---

src/components/Clusters/components/AddClusterDialog.js
src/components/Clusters/components/AddClusterWizard.js
src/components/Clusters/components/AddClusterWizard.scss
src/components/Clusters/components/AuthForm.js
src/components/Clusters/components/ChooseStorage.js
src/components/Clusters/components/ClusterPreview.js
src/components/Clusters/components/ClusterPreview.scss
src/components/Clusters/components/KubeconfigUpload/KubeconfigFileUpload.js
src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
src/components/Clusters/components/oidc-params.ts
src/components/Clusters/components/test/oidc-params.test.js
src/components/Clusters/shared.ts
src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
src/components/Clusters/views/EditCluster/EditCluster.js
src/resources/RoleBindings/RoleForm.js
src/resources/RoleBindings/SubjectForm.js
src/shared/ResourceForm/components/FormField.js
src/shared/components/Dropdown/Dropdown.js
src/state/authDataAtom.ts

- fixed UI issues of cluster wizard
- adjusted forms in cluster wizard to match UX specification
- adjusted code to handle multiple scopes specified in the kubeconfig
- changed scope input field to scopes list input
- multiple scopes can be displayed in review step
- adjusted unit test for oidc parsing
#3055 #3288

fix: cluster-wizard UI & oidc-scopes

---

src/resources/ConfigMaps/ConfigMapDetails.js
src/resources/ConfigMaps/index.tsx
src/resources/Pods/index.tsx
src/shared/components/MonacoEditorESM/Editor.js
src/shared/components/ReadonlyEditorPanel.js

- feat: added binaryData to Config Map details
- feat: add encode/decode base64 to `ReadonlyEditorPanel`

feat: Enhance Config Maps

---

public/i18n/en.yaml
src/resources/RoleBindings/GenericRoleBindingDetails.js
src/resources/RoleBindings/RoleRef.js
src/shared/hooks/BackendAPI/useGet.js

- feat: Enahnce Role Bindings and CRB
#2857 

feat: Enahnce Role Bindings and CRB

---

.gitignore
.prettierignore
Dockerfile
src/shared/utils/env.ts
src/shared/utils/path.test.ts
src/shared/utils/path.ts
src/state/configuration/configurationAtom.ts
src/state/navigation/extensionsAtom.ts
start_nginx.sh

- add env file to choose which configuration to load at busola startup
https://github.com/kyma-project/busola/issues/3299

feat: Dynamic config

---

docs/extensibility/30-details-summary.md
docs/extensibility/50-list-and-details-widgets.md
src/components/Extensibility/ExtensibilityDetails.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceStatusCard/ResourceStatusCard.js

- Add long columns in status card

feat: Add long columns in status card

---

.github/workflows/busola-kyma-build.yml
Dockerfile
Dockerfile.kyma
Dockerfile.local
Dockerfile.local.kyma

- Use one node version
- remove instalation of nodejs
https://github.com/kyma-project/busola/issues/3298

feat: Unify nodejs version for building

---

public/i18n/en.yaml
src/resources/LimitRanges/LimitRangeSpecification.tsx
src/resources/Namespaces/NamespaceDetails.js
src/resources/ResourceQuotas/ResourceQuotaCreate.js
src/resources/ResourceQuotas/ResourceQuotaDetails.scss
src/resources/ResourceQuotas/ResourceQuotaDetails.tsx
src/resources/ResourceQuotas/ResourceQuotaLimits.tsx
src/resources/ResourceQuotas/ResourceQuotaList.tsx
src/resources/ResourceQuotas/ResourceQuotasList.js
src/resources/ResourceQuotas/ResourceQuotasList.tsx
src/resources/ResourceQuotas/index.tsx
src/resources/index.js
src/shared/components/UI5Panel/UI5Panel.tsx
tests/integration/cypress.config.js
tests/integration/fixtures/test-resource-quotas.yaml
tests/integration/tests/namespace/test-namespace-overview.spec.js
tests/integration/tests/namespace/test-resource-quotas.spec.js

- created Resource Quotas details, list and create views
- adjusted Resource Quotas list on namespace overview
Closes #2991 

feat: create Resource Quotas views

---

public/i18n/en.yaml
src/resources/Events/EventDetails.js
src/shared/components/ResourceDetails/ResourceDetails.js

- improved EventDetails (Metadata & Specification Panels)

feat: enhance events

---

src/resources/Namespaces/AllNamespacesDetails.js
src/resources/Namespaces/NamespaceDetails.js
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
src/resources/ResourceQuotas/ResourceQuotasList.tsx

- added additional statistical cards to namespace overview
- adjusted the all-namespaces overview

feat: enhance namespace overview

---

src/components/BusolaExtensions/BusolaExtensionDetails.js
src/components/BusolaExtensions/BusolaExtensionEdit.js
src/shared/ResourceForm/fields/KeyValueField.js
src/shared/components/MonacoEditorESM/Editor.js
src/sidebar/CategoryItem.tsx

- fix console errors in Extensions
Closes #3317 

fix: fix console errors in Extensions

---

docs/extensibility/60-form-widgets.md
public/schemas/schema-form.yaml
src/components/Extensibility/components-form/KeyValuePairRenderer.js
src/shared/ResourceForm/fields/KeyValueField.js
src/shared/ResourceForm/fields/MultiInput.js

- `disableOnEdit` feature for `KeyValuePair` widget
- documentation for the new `disableOnEdit`
Fixes #3315 

feat: disableOnEdit KeyValuePair

---

README.md
kyma/README.md
tests/kyma/README.md
tests/kyma/package.json

- Adjust docs to new configuration management
- 
https://github.com/kyma-project/busola/issues/3298

feat: Update docs about recent changes related to kyma-dashboard

---

src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
src/shared/components/LayoutPanelRow/LayoutPanelRow.scss
src/shared/components/LayoutPanelRow/LayoutPanelRow.tsx

- remove capitalization of data in rows
- add option to enable capitalization
https://github.com/kyma-project/busola/issues/3359

fix: Remove capitalization of data in rows

---

src/hooks/useAvailableNamespaces.ts
src/shared/hooks/useGetHiddenNamespaces.ts

When feature `HIDDEN_NAMESPACES` is disabled, the busola goes into infinite loop. The problem is that we return simple `[]` value as dependency to useEffect instead of reactive value.
- use memo to cache hidden namespace and wrap the value into reactive value.

fix: infinite loop on hidden namespace

---

backend/package-lock.json
backend/package.json
backend/request-filters.js
backend/request-filters.test.js

see related isssue
- added filter for invalid, harmful characters such as "<", ">", ";", ".."  
- added filter for invalid request method TRACE, OPTIONS, HEAD
- added filter for forwarded and x-forwarded-for header
#3372

fix: tighten backend's request validation

---

README.md

- Add case with custom config and how to active it
- Add case with how to active build-in config for kyma.
https://github.com/kyma-project/busola/issues/3298

docs: Update docs about busola-kyma image

---

tests/integration/README.md

docs: accessibility tests

---

backend/request-filters.js
backend/request-filters.test.js

- adjust invalidHeaderFilter to not throw an error for empty headers

fix: adjust invalidHeaderFilter to handle empty headers correctly

---

src/shared/hooks/BackendAPI/useGet.js

- outsourced polling functionality into custom hook with proper error handling
#3296

fix: proper error handling for polling hook

---

src/components/Clusters/views/ClusterOverview/ClusterNodes.js
src/components/Extensibility/components/Badge.js
src/components/HelmReleases/HelmReleaseStatus.js
src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/components/ModuleStatus.tsx
src/resources/CustomResourceDefinitions/CurrentCRDVersion.js
src/resources/Ingresses/IngressDetails.js
src/resources/Jobs/JobCompletions.js
src/resources/Jobs/JobConditions.js
src/resources/Namespaces/NamespaceStatus.js
src/resources/PersistentVolumes/PersistentVolumeStatus.js
src/resources/Pods/ContainerStatus.js
src/resources/Pods/PodRestarts.js
src/resources/Pods/PodStatus.js
src/shared/components/BTPResourceStatus.js
src/shared/components/ExpandableListItem/ExpandableListItem.tsx
src/shared/components/PersistentVolumeClaimStatus.js
src/shared/components/PopoverBadge/PopoverBadge.tsx
src/shared/components/RunningPodsStatus.js
src/shared/components/StatusBadge/StatusBadge.js
src/shared/components/SubscriptionConditionStatus.js
src/shared/components/TooltipBadge/TooltipBadge.js

- adjust badges to V2 UI5
#3422 

fix: adjust badges

---

docs/extensibility/70-widget-injection.md
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourcesList/ResourcesList.js

As part of the issue https://github.com/kyma-project/api-gateway/issues/1423 the information for deprecation of APIRule v1beta1 in the API Gateway module must be displayed to the UI.
It was decided by the team that the FeatureCard is the best option to display this information. To limit the scope of this information we decided to display this only on the list view of the v1beta1 APIRules.
Using the `header-list` or `banner` injection slot in the ResourcesList resulted in a UI that wasn't very well-formatted.
So we want to propose to move the `banner` slot in the ResourcesList component just above the resources.
- Move `banner` injection slot above the listed resources
- Move `banner` slot in the resource details
- …

feat: Move banner slot in the Resource components

---

.github/workflows/create-release.yml

- create workflow to be caught by github actions
https://github.com/kyma-project/busola/issues/3375

feat: Create release workflow skeleton

---

src/header/Header.tsx
src/shared/components/ResourcesList/ResourcesList.js
src/shared/components/TileButton/TileButton.tsx
src/shared/components/VerticalTabs/VerticalTabs.scss

- adjust Preferences modal
#3422 

fix: adjust Preferences modal

---

src/components/Extensibility/ExtensibilityInjections.js
src/components/HelmReleases/HelmReleasesDetails.js
src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesList.js
src/resources/CustomResourceDefinitions/CRDSpecification.tsx
src/resources/Ingresses/IngressDetails.js
src/resources/LimitRanges/LimitRangeDetails.tsx
src/resources/LimitRanges/LimitRangeSpecification.tsx
src/resources/Namespaces/NamespaceDetails.js
src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
src/resources/PersistentVolumes/PersistentVolumeDetails.js
src/resources/ResourceQuotas/ResourceQuotaDetails.tsx
src/resources/RoleBindings/RoleRef.js
src/resources/RoleBindings/SubjectForm.js
src/resources/Secrets/SecretDetails.js
src/resources/ServiceAccounts/ServiceAccountDetails.js
src/resources/StorageClasses/PersistentVolumeClaimsList.js
src/resources/StorageClasses/PersistentVolumesList.js
src/resources/StorageClasses/StorageClassDetails.js
src/resources/helpers.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
src/shared/components/ResourceCreate/ResourceCreate.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceRef/ExternalResourceRef.js
src/shared/components/SchemaViewer/JSONSchema.js

fix: Ui5 console errors

---

src/resources/Deployments/DeploymentDetails.js
src/resources/Deployments/DeploymentStatus.js
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js
src/shared/components/ConditionList/ConditionList.tsx
src/shared/components/ExpandableListItem/ExpandableListItem.tsx

details and incluster overview
- Fix deployment status properly on deployments list, details and in the cluster overview

fix: Fix deployment status properly 

---

src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesCreate.js
src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/ModulesCard.js

- adjust `Add Modules` view to take data for modules from `ModuleMetaRelease` if `ModuleTemplate` is not available
- adjust `Edit Modules` view to take data for modules from `ModuleMetaRelease` if `ModuleTemplate` is not available 
- adjust `List` view of the modules, to take channel from `KymaCR.spec.[modules].channel` is `KymaCR.status.[modules].channel` is not avaibale
Closes #3459

feat(Modules): modules version adjustments to moduleCatalog changes

---

index.html

fix: Fix fonts in safari

---

.github/workflows/pull-integration-cluster-k3d.yml
.github/workflows/pull-integration-namespace-k3d.yml
.github/workflows/pull-kyma-integration-tests.yml
backend/package-lock.json
backend/package.json

- override cookie packages in express - CVE-2024-47764
- override  path-to-regexp packages in express - CVE-2024-52798
- add backend to paths for tests workflows

chore: override cookie and path-to-regexp packages in express

---

backend/package-lock.json
backend/package.json

- chore(deps): bump express version
- remove overrides

chore(deps): bump express version

---

index.html
src/components/Extensibility/ExtensibilityList.js

Currently custom extension cannot be loaded due to CSP:
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-XdJSyn1l8eeFeZ6L+DF4Ke18+VkBZcTCtFdVf75F4zc='), or a nonce ('nonce-...') is required to enable inline execution.
- Load custom script from blob

fix: Loading custom script from blob

---

src/shared/components/GenericList/components.js

- fixed selected prop not working in the tables
#3422 

fix: selected prop is not working in the tables

---

.github/workflows/pull-integration-cluster-k3d.yml
.github/workflows/pull-integration-namespace-k3d.yml
.github/workflows/pull-kyma-integration-tests.yml
.github/workflows/pull-lighthouse.yml
.github/workflows/pull-smoke-test-prod.yml
.github/workflows/pull-smoke-test-stage.yml
.github/workflows/pull-unit-tests.yml
src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesAddModule.scss
src/components/KymaModules/ModulesCard.js

- add displaying icons from ModuleTemaplates 
- add checking if the image is available on the link
Closes #3465 

feat(Modules): Add icon from ModuleTemplates

---

src/components/Nodes/NodeResources/NodeResources.js
src/components/Nodes/nodeQueries.js
src/shared/hooks/BackendAPI/useGet.js

- fixed refreshing of CPU and memory usage
- added option to compare entire resource in useGet
Fixes #3503 

fix: CPU and memory usage is not refreshing

---

src/shared/components/MonacoEditorESM/Editor.scss

- Style change. Increase z-index to improve visibility of description tooltip
Closes #3544 

fix: Popover rendering problem

---

src/components/Clusters/views/ClusterOverview/ClusterNodes.js
src/components/Nodes/MachineInfo/MachineInfo.js

- Removed deprecated kubeProxyVersion field,
- For the Nodes version column, replace the value from deprecated kubeProxyVersion with the value from the kubeletVersion field (it's the same value)
Closes #3521 

feat: Remove deprecated kubeProxyVersion property

---

src/components/App/App.tsx
src/components/App/initTheme.ts

- fixed theme not working properly on initial render and after refresh
#3422 

fix: theme not working properly on initial render and after refresh

---

examples/custom-extension/README.md
examples/custom-extension/busola-config.yaml

- Instruction on how to enable custom extensions in your cluster
- https://github.com/kyma-project/busola/issues/3497

Enable custom extensions: example

---

src/components/Extensibility/components/Badge.js

- Extract message from description and check validity
Closes #3560 

fix: Checking validity of the message for badge description

---

src/components/KymaModules/KymaModulesList.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss

- adjusted styles in Modules view
#3422 

fix: adjust styles in Modules view

---

src/components/Extensibility/components-form/KeyValuePairRenderer.js
src/resources/Namespaces/MemoryQuotas.js
src/resources/Namespaces/NamespaceCreate.js
src/resources/Namespaces/Presets.js
src/shared/ResourceForm/components/Presets.js
src/shared/ResourceForm/inputs/Dropdown.js
src/shared/components/Dropdown/Dropdown.cy.js
src/shared/components/Dropdown/Dropdown.js

- directly pass props to related components (instead of `...props` syntax) for better clarity
- removed unused properties inlineHelp, enableResource
- use ref instead of id to open popover
- change popover opening logic to correctly open for both clicking inside the input or on the icon

fix: open dropdown popover correctly

---

src/header/Header.tsx
src/header/SidebarMenu/useGetBusolaVersion.ts

- added a link to the release of the currently deployed version in kyma-dashboard version
Closes #3294 

feat: Link to the release of the currently deployed version in kyma-dashboard version

---

README.md

- docs: fix docker run commands

docs: Fix docker run commands

---

src/components/CustomResources/CustomResources.js
src/resources/CustomResourceDefinitions/CRCreate.js
src/resources/CustomResourceDefinitions/useCustomResourceUrl.js

Reverts kyma-project/busola#3652

revert: "fix: Use correct paths for cluster urls"

---

src/components/Clusters/components/AddClusterDialog.js
src/components/Clusters/components/AddClusterWizard.js
src/components/Clusters/components/AddClusterWizard.scss
src/components/Clusters/components/ClusterPreview.scss
src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
src/components/Extensibility/ExtensibilityWizard.js
src/shared/ResourceForm/components/ResourceForm.scss
src/shared/components/WizardButtons/WizardButtons.js

- reset ui5 variables for wizard step content padding and background
- adjusted margin of "Storage type configuration" - title
- fixed margin of OIDC switch in authentication form

fix: UI5v2 styling issues in cluster wizard

---

src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesEdit.js
src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/components/ModulesCard.js
src/components/KymaModules/support.ts
src/shared/hooks/useDeleteResource.js

- If modules is added with custom resource, busola tries to find ModuleTemplate to display ModuleResource
Closes https://github.com/kyma-project/busola/issues/3624

feat: Add ability to expand manually added module to kyma

---

public/i18n/en.yaml
src/components/KymaModules/KymaModulesList.js
src/shared/hooks/useDeleteResource.js

- feat: Add additional info on Module delete modal
backlog#6746

feat: Add additional info on Module delete modal

---

.github/workflows/pull-kyma-integration-tests.yml
src/components/CustomResources/CustomResources.js

- as in title
https://github.com/kyma-project/busola/issues/3670

feat: Run dev k3d tests after build

---

.github/workflows/busola-build.yml
.github/workflows/pull-kyma-integration-tests.yml
src/components/CustomResources/CustomResources.js

- Use workflow call to run integration tests
https://github.com/kyma-project/busola/issues/3670

feat: Use workflow call to run integration tests after image build

---

public/i18n/en.yaml
src/components/Clusters/views/ClusterOverview/ClusterDetails.js
src/components/Clusters/views/ClusterOverview/ClusterModulesCard.tsx
src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
src/components/KymaModules/support.ts
src/shared/components/CountingCard/CountingCard.tsx
tests/integration/tests/kyma-cluster/test-kyma-modules.spec.js

- added state of the Kyma modules in cluster overview
Closes #3659 

feat: Add state of the Kyma modules in cluster overview

---

src/components/BusolaExtensions/ExtensibilityStarterForm.scss
src/resources/ReplicaSets/ReplicaSetDetails.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss

- Truncation of title on resource  list and details page
- Truncation of form on create extension page

fix: Truncation of title and extension form

---

public/themes/hcb.css
public/themes/hcw.css
src/shared/components/UI5RadialChart/UI5RadialChart.js

- Adjust chart styles in high contrast theme

fix: Adjust chart styles in high contrast theme

---

src/components/KymaModules/providers/KymaModuleProvider.js
tests/integration/support/commands.js
tests/integration/tests/kyma-cluster/test-kyma-modules.spec.js

- uncomment delete tests
- fix delete module
https://github.com/kyma-project/busola/issues/3920

fix: Module deletion

---

src/shared/ResourceForm/tests/useCreateResource.test.js
src/shared/ResourceForm/useCreateResource.js

- Return focus to previus element when error modal is displayed.
https://github.com/kyma-project/busola/issues/3201

fix: Return focus to previus element when error modal is displayed

---

src/shared/components/FileInput/FileInput.js

- After uploading the kubeconfig in the Connect YAML dialog, the file name is now read out by a screen reader
Closes #3233

fix: Focus on file name after uploading a kubeconfig

---

src/components/Clusters/components/AddClusterDialog.tsx
src/components/Clusters/components/AddClusterWizard.js

- Changed the render order of buttons in the Cluster Wizard - it renders now after the form
Closes #3251 

fix: Reorder buttons in Cluster Wizard for screen reader
