resources/web/deployment.yaml
src/shared/components/ResourcesList/ResourcesList.js

- Fixed removing & editing of resources by providing correct URL of resource
- Create-Button is now hidden on namespace-All
- ...

Fix bug on allNamespace-view: removing, creating & editing of resources

---

resources/web/deployment.yaml
src/components/BusolaExtensions/BusolaExtensionCreate.js
src/shared/hooks/useDeleteResource.js

- fixed Redirection after Creation and Deletion of Extension

fixed Redirection after Creation and Deletion of Extension

---

CODEOWNERS
OWNERS_ALIASES

remove qbalukom from codeowners

---

CODEOWNERS
OWNERS_ALIASES

- Added Gosia to the CODEOWNERS files 

Add Gosia to CODEOWNERS

---

resources/web/deployment.yaml
src/components/Extensibility/ExtensibilityWizard.js
src/components/Extensibility/components/Wizard.js
src/state/navigation/extensionsAtom.ts

Allow edit for wizard

---

Makefile
README.md
backend/Makefile
resources/backend/deployment.yaml
resources/web/deployment.yaml

change gcr to europe-docker 

---

resources/web/deployment.yaml
src/components/Extensibility/ExtensibilityInjections.js

- ...
- ...
- ...
Closes #2456

change interval

---

resources/web/deployment.yaml
src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
src/resources/Namespaces/YamlUpload/useUploadResources.js

Fix upload Yaml

---

resources/web/deployment.yaml
src/resources/Namespaces/YamlUpload/YamlUploadDialog.js

Fix upload yaml v2

---

resources/web/deployment.yaml
src/components/Extensibility/ExtensibilityWizard.js
src/shared/utils/helpers.js

- add functionality `defaults` for editing resources in the wizard.

Wizard defaults

---

resources/web/deployment.yaml
src/state/preferences/showHiddenNamespacesAtom.ts
tests/integration/tests/namespace/test-daemon-sets.spec.js
tests/integration/tests/namespace/test-settings.spec.js

- Show hidden namespaces by default

Show hidden namespaces by default

---

resources/web/deployment.yaml
src/state/navigation/extensionsAtom.ts
src/state/types.ts

- ...
- ...
- ...
Closes #2470

allow overriding wizards

---

docs/features.md
public/defaultConfig.yaml
resources/web/configmap.yaml
resources/web/deployment.yaml

The two components are removed from kyma and busola should adjust to it:
- removed kiali navigation node
- removaed jaeger navigation node
- ...
https://github.com/kyma-project/kyma/issues/15852
https://github.com/kyma-project/kyma/issues/15412

removed navigation nodes for kiali and jaeger

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/AlertRenderer.js

Add possibility to have link in Alert

---

resources/web/deployment.yaml
src/components/Extensibility/useGetInjection.js

Fix statics on extensibility views

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/StringRenderer.js

Allow to have key and name

---

resources/web/deployment.yaml
src/components/Extensibility/helpers/index.js

- ...
- ...
- ...
Closes #2464

EXT: fix links for helm brackets

---

resources/web/deployment.yaml
src/state/navigation/extensionsAtom.ts

Override kube-public with kyma-system

---

resources/web/deployment.yaml
src/components/Extensibility/components/ExternalLink.js

fix vulnerability from checkmarx

---

package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml

bump monaco-yaml

---

resources/web/deployment.yaml
src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
src/resources/Namespaces/YamlUpload/useUploadResources.js
src/shared/components/ResourceGraph/DetailsCard/DetailsCard.tsx
src/shared/components/ResourceGraph/useRelatedResources.ts
src/shared/hooks/useIsInCurrentNamespace.ts
src/state/navigation/allNodesSelector.ts
src/state/resourceList/mapExtResourceToNavNode.ts

- Include extensibility resources in allNodes array
- Use the above list for
- links on custom resource details
- upload modal to determine clusterNodes and namespaceNodes
- graph details card to prepare the link
- to prepare related resources for graphs

Include extensibility resources in allNodes array

---

package-lock.json

bump yaml to version 2.2.2

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/.kyma-project-io/build-preview.sh
src/components/Extensibility/components-form/.kyma-project-io/values.yaml

test-website

---

resources/web/deployment.yaml
src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
src/shared/components/ResourcesList/ResourcesList.js

- hide nodes when they are forbidden.
Closes #2501

add checking errors and not to display

---

resources/web/deployment.yaml
src/components/CustomResources/CustomResources.js

- parsing data from yaml to put it to jsonpath.

fix parsing annotations data for CR

---

resources/web/deployment.yaml
src/state/navigation/extensionsAtom.ts

- Fix loading injections and wizards 

Fix loading injections and wizards 

---

.github/pull-request-template.md
milv.config.yaml
resources/web/deployment.yaml
src/components/Extensibility/contexts/DataSources.tsx

Fix resources lists on details views

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/StringRenderer.js

fix for previous target port 

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/StringRenderer.js

- fix for a parsing string to a number.

finall fix for parsing strings and number 

---

resources/web/deployment.yaml
src/components/Extensibility/contexts/DataSources.tsx

- ...
- ...
- ...
Closes https://github.com/kyma-project/kyma-dashboard/issues/199

fix fetching data sources

---

README.md

- @pPrecel requested a change, because readme is missleading.

fix info about node version

---

docs/features.md
public/defaultConfig.yaml
resources/web/deployment.yaml
src/header/Header.tsx
src/state/types.ts
tests/integration/tests/cluster/test-cluster-overview.spec.js

- add feedback icon,
- add feature flag.
Closes #2528

add feedback icon and config

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/Modules/Modules.js

- ...
- ...
- ...
Closes #2532

change combobocinput to dropdown

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/CollapsibleRenderer.js
src/components/Extensibility/components-form/GenericList.js
src/components/Extensibility/components-form/KeyValuePairRenderer.js
src/components/Extensibility/components-form/MonacoRenderer.js
src/components/Extensibility/components-form/ResourceRefRenderer.js
src/components/Extensibility/components-form/SimpleList.js

- set default value to `false` for `defaultExpanded` flag.

fix for default expanded flag

---

public/i18n/en.yaml
resources/web/deployment.yaml
src/components/Extensibility/components-form/Modules/Modules.js

- when there are no modules available busola displayed empty section -> added info about no modules available,
- when one module is available busola crashes -> fixed.

fix no modules and one module

---

resources/web/deployment.yaml
src/components/App/IncorrectPath.js
tests/integration/cypress.config.js
tests/integration/scripts/busola-integration-k3s.sh
tests/integration/support/login-commands.js
tests/integration/tests/cluster/test-navigation-features.spec.js
tests/integration/tests/extensibility/ext-test-pizzas.spec.js
tests/integration/tests/extensibility/ext-test-services.spec.js
tests/integration/tests/extensibility/ext-test-variables.spec.js
tests/integration/tests/namespace/test-reduced-permissions.spec.js
tests/lighthouse/lighthouse.spec.js
tests/lighthouse/scripts/busola-lighthouse.sh

- k3d for integrations tests,
- k3d for performance test,
- fix `IncorrectPath`,
- adjust tests to the new flow.

move tests from `nkyma` to k3d

---

resources/web/deployment.yaml
src/resources/RoleBindings/GenericRoleBindingList.js
src/resources/Roles/GenericRoleList.js

- Update links for the OS website domain change

Update links for the domain change

---

resources/backend/deployment.yaml
resources/web/deployment.yaml
src/shared/contexts/NotificationContext.tsx

- added hideIcon-flag on notification message-strip

Removed icon on notification message-strip

---

resources/backend/deployment.yaml
resources/web/deployment.yaml
src/header/Header.tsx

- sidebar-switcher is now hidden on cluster overview

hide sidebar-switcher on cluster overview

---

resources/web/deployment.yaml
src/setupTests.js
src/shared/components/PageHeader/PageHeader.js
src/shared/components/PageHeader/PageHeader.scss
src/shared/components/PageHeader/test/PageHeader.test.js
src/shared/components/ResourceNotFound/test/ResourceNotFound.test.js
tests/integration/support/navigate-back-to.js
tests/integration/tests/cluster/test-cluster-overview.spec.js
tests/integration/tests/cluster/test-custom-resources.spec.js
tests/integration/tests/cluster/test-persistent-volumes.spec.js
tests/integration/tests/extensibility/ext-test-pizzas.spec.js
tests/integration/tests/extensibility/ext-test-variables.spec.js
tests/integration/tests/namespace/a-run-before.spec.js
tests/integration/tests/namespace/test-custom-resources.spec.js
tests/integration/tests/namespace/test-deployments.spec.js
tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
tests/integration/tests/namespace/test-roles.spec.js
tests/integration/tests/namespace/test-settings.spec.js
tests/integration/tests/namespace/test-stateful-sets.spec.js

- replace LayoutPanel in PageHeader with UI5.

Ui5 headers

---

resources/backend/deployment.yaml
resources/web/deployment.yaml
src/header/Header.tsx
tests/integration/tests/cluster/test-custom-resources.spec.js

- upload-yaml-button in Shellbar is now hidden on noPermissions-View

no upload-yaml on noPermissions-view

---

package-lock.json

- bump semver
- bump word-wrap

Whitesource fixes

---

package-lock.json

Use semver 7.5.4 to 7.5.2

---

.mlc.config.json

- Push mlc config through prettier
- ...
- ...

Push mlc config through prettier

---

tests/integration/package.json

- Use tests with Chromium
/kind bug
/area ci

Use chromium

---

resources/web/deployment.yaml
src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/useMetricsQuery.js
src/components/Extensibility/components-form/SimpleList.js
src/components/Extensibility/components-form/StringRenderer.js
src/resources/Pods/PodRestarts.js
src/shared/ResourceForm/components/FormField.js
src/shared/ResourceForm/inputs/Dropdown.js
src/shared/components/MonacoEditorESM/Editor.js
src/shared/components/MonacoEditorESM/Editor.scss
src/shared/components/TooltipBadge/TooltipBadge.scss
src/shared/hooks/useDeleteResource.js

- styled message-strips in editor
- styled deleteResource-MessageBox
- fixed double label bug in SimpleList
- styled pod-restarts badge

UI5 styling and bugfixes

---

docs/extensibility/resources.md
resources/web/deployment.yaml
src/components/Extensibility/ExtensibilityList.js

- add filter functionality for general section,
- fix docs.

add functionality for filtering general

---

resources/web/deployment.yaml
src/components/Preferences/Preferences.scss
src/resources/Namespaces/NamespaceDetails.scss
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
src/shared/components/StatsGraph/StatsGraph.scss
src/shared/components/TileButton/TileButton.scss
src/shared/components/VerticalTabs/VerticalTabs.scss
src/sidebar/NavItem.tsx

- adjusted Preferences-Dialog on mobile
- adjusted PageHeader on mobile
- adjusted Namespace workloads
- adjusted statsgraph
- added external link icon to sidenavigationsubitems

improve mobile view

---

resources/web/deployment.yaml
src/hooks/usePermittedUrl.ts
src/shared/ResourceForm/components/ResourceForm.js
src/shared/components/ModalWithForm/ModalWithForm.js

- fix os usage setStates which causes broken create form for log pipelines.

fix setting states

---

.mlc.config.json

fix link checks

---

resources/web/deployment.yaml
src/components/BusolaExtensions/BusolaExtensionCreate.js
src/components/Extensibility/components-form/Jsonata.js
src/resources/RoleBindings/RoleForm.js
src/resources/Secrets/SecretCreate.js
src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
src/shared/ResourceForm/components/FormField.js
src/shared/ResourceForm/fields/ComboboxArrayInput.js
src/shared/ResourceForm/fields/K8sNameField.js
src/shared/ResourceForm/inputs/ComboboxInput.js
src/shared/ResourceForm/inputs/Text.js
src/shared/components/GenericList/SearchInput.js
src/shared/components/K8sNameInput/K8sNameInput.js
src/shared/components/K8sResourceSelect.js
src/shared/hooks/useCustomFormValidator.js
tests/integration/support/commands.js
tests/integration/support/helpers.js
tests/integration/support/paste-to-monaco.js
tests/integration/tests/namespace/test-protected-resources.spec.js
tests/integration/tests/namespace/test-reduced-permissions.spec.js

- added updates onInput for comboboxes
- added updates onInput for inputs
- adjusted custom form-validation to allow Key-Value-Pairs with empty value

instant value-updates for comboboxes & inputs

---

resources/web/deployment.yaml
src/header/Header.scss
src/header/Header.tsx
src/shared/ResourceForm/components/ResourceForm.js
src/shared/components/ErrorBoundary/ErrorBoundary.js
src/shared/components/ErrorBoundary/ErrorBoundary.scss
src/styles/index.scss
tests/integration/cypress.config.js
tests/integration/support/commands.js
tests/integration/tests/namespace/test-cron-jobs.spec.js
tests/integration/tests/namespace/test-protected-resources.spec.js
tests/integration/tests/namespace/test-roles.spec.js

- adjust styles for error boundary.

Fix error boundary component

---

resources/web/deployment.yaml
src/components/BusolaExtensions/BusolaExtensionCreate.js
src/shared/ResourceForm/components/ResourceForm.js
src/shared/ResourceForm/components/ResourceForm.scss

- fixed scroll-bug on create-extension view
- adjusted size of yaml-editor in create-forms

adjust create-form

---

resources/web/deployment.yaml
src/styles/index.scss

Firefox safari

---

resources/web/deployment.yaml
src/components/Extensibility/components-form/SimpleList.js
src/components/Extensibility/components/Columns.js
src/components/Extensibility/components/Table.js
src/components/Extensibility/components/Tabs.js
src/components/Extensibility/components/Tabs.scss
src/resources/Events/EventList.js
src/resources/Namespaces/AllNamespacesDetails.js
src/resources/Namespaces/NamespaceDetails.js
src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
src/resources/PersistentVolumes/PersistentVolumeList.js
src/resources/Pods/PodList.js
src/shared/ResourceForm/components/FormField.js
src/shared/ResourceForm/fields/MultiInput.js
src/shared/ResourceForm/fields/RuntimeResources.js
src/shared/ResourceForm/inputs/Checkboxes.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
src/shared/components/GenericList/GenericList.js
src/shared/components/PodTemplate/PodTemplate.js
src/shared/components/PodTemplate/components.js
src/shared/components/RelatedPods.js
src/shared/components/ResourcesList/ResourcesList.js
src/shared/components/Selector/Selector.js
src/styles/index.scss

- Fix tabs
- Fix margins on details pages

Ui5 fix margins

---

package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml
src/index.js
src/resources/ClusterEvents/index.js
src/resources/Events/index.js
src/resources/Namespaces/namespaceOverviewNode.ts
src/sidebar/SidebarNavigation.tsx
src/state/navigation/categories.ts

Adjust icons in navigation

---

sec-scanners-config.yaml

- Exclude paths for sec scanners
/kind bug
/area security
/cc @mrCherry97

Exclude paths for sec scanners

---

sec-scanners-config.yaml

- Fix excludes in sec-scanners-config

Fix excludes in sec-scanners-config.yaml

---

backend/index.js
resources/backend/deployment.yaml
sec-scanners-config.yaml

add comment and fix eslint problems

---

resources/web/deployment.yaml
src/hooks/useAvailableNamespaces.ts

Update namespace chooser

---

resources/web/deployment.yaml
sec-scanners-config.yaml
src/components/Clusters/components/AddClusterDialog.js
src/components/Clusters/components/AddClusterWizard.js
src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
src/components/Clusters/views/ClusterList.js
src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
src/components/CustomResources/CustomResourcesOfType.js
src/components/CustomResources/GroupingListPage.js
src/components/HelmReleases/HelmReleasesDetails.js
src/components/HelmReleases/HelmReleasesList.js
src/components/Nodes/NodeDetails/NodeDetails.js
src/resources/Namespaces/YamlUpload/YamlUpload.js
src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
src/shared/components/FileInput/FileInput.js
src/shared/components/GenericList/SearchInput.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourcesList/ResourcesList.js
src/state/showAddClusterWizard.ts

- remove unnecessary props and fix onCancel in YamlUpload,
- add addClusterWizard atom,
- fix onCancel for kubeconfigUpload.
Closes #2671

fix: upload Yaml and Kubeconfig YAML upload

---

resources/web/deployment.yaml
src/components/NoPermissions/NoPermissions.tsx

- fix button for no permissions view.

fix no-permissions button

---

.github/workflows/cypress-tests.yml

- Add manually-ran GH Action workflow which runs Cypress tests to check if we hit limit with 20 concurrently running jobs

Add test GH Action job

---

resources/web/deployment.yaml
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/GenericList/GenericList.js
src/shared/components/ReadableCreationTimestamp/ReadableCreationTimestamp.tsx
src/shared/components/ResourcesList/ResourcesList.js

- changed name to be bold
- changed position of protected-resource-icons
- changed format of creation-timestamp
- title description is now displayed in a popover

List improvements

---

sec-scanners-config.yaml

- busola image is not used on production

remove busola-local image from blackduck

---

Dockerfile
Dockerfile.local
backend/Dockerfile
resources/backend/deployment.yaml
resources/web/deployment.yaml

Bump base Alpine image

---

public/i18n/en.yaml
resources/web/deployment.yaml
src/resources/ResourceQuotas/ResourceQuotaList.js
src/resources/ResourceQuotas/templates.js

- add missing information about cpu 
Closes #2641

Add missing information in resource quota

---

Dockerfile
Dockerfile.local
README.md
backend/Dockerfile
backend/index.js
backend/package-lock.json
package-lock.json
resources/backend/deployment.yaml
tests/integration/package-lock.json
tests/integration/package.json
tests/integration/scripts/busola-integration-k3s.sh

- update node version to 20.x 
- update npm version to 10.x
- adjust tests

Bump node and cypress

---

Dockerfile
resources/web/deployment.yaml

- Bump base image for busola-web

Bump base image for busola-web

---

Dockerfile

- change nginx version to alpine

change nginx version to alpine

---

package-lock.json
package.json
public/defaultConfig.yaml
resources/backend/deployment.yaml
resources/web/deployment.yaml
src/components/App/Snow/Snow.js
src/index.js

- add snow 
- add feature flag

Add snow feature

---

CODEOWNERS
OWNERS_ALIASES

- add @chriskari as a codeowner

add chriskari as a codeowner

---

resources/backend/deployment.yaml
resources/web/deployment.yaml
src/components/App/Snow/Snow.js

- improve detection of light theme

Snow - Fix for light theme

---

resources/web/deployment.yaml
src/components/Extensibility/components/tests/Badge.test.js
src/components/Extensibility/components/tests/Table.test.js
src/components/Extensibility/components/tests/Widget.copyable.test.js
src/components/HelmReleases/tests/ReleaseDataPanel.test.js
src/resources/Pods/test/PodRestarts.test.js
src/shared/components/CopiableText/test/CopiableText.test.js
src/shared/components/GenericList/Pagination/test/Pagination.test.js
src/shared/components/GenericList/test/GenericList.test.js
src/shared/components/ListActions/test/ListActions.test.js
src/shared/components/ResourceDetails/tests/ResourceDetailsColumns.test.js
src/shared/components/ResourceDetails/tests/ResourceDetailsVisibility.test.js
src/shared/components/ResourceNotFound/test/ResourceNotFound.test.js
src/shared/components/Selector/tests/Selector.test.js
src/shared/components/StatusBadge/test/StatusBadge.test.js

- add import icons in unit tests
- wrap events into waitFor(act()) in unit tests

fix unit test errors

---

resources/web/deployment.yaml
src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
tests/integration/support/helpers.js
tests/integration/tests/namespace/test-service-accounts.spec.js

- changed Service Account token generation to every time the expiration seconds field is changed 
- adjusted e2e tests

Change Service Account token generation

---

resources/web/deployment.yaml
src/components/Clusters/views/ClusterOverview/ClusterStats.js

- adjusted color palette in radial charts in Cluster Overview

ClusterOverview colors adjustment

---

resources/web/deployment.yaml
src/components/CustomResources/GroupingListPage.js
src/components/Extensibility/components/PendingWrapper.js
src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.scss
src/resources/RoleBindings/RoleForm.js
src/shared/components/ResourceRef/ExternalResourceRef.js
src/shared/components/Spinner/Spinner.tsx
src/sidebar/Sidebar.tsx

- replaced old spinner component

replaced Spinner-components

---

package-lock.json
package.json
resources/backend/deployment.yaml
resources/web/deployment.yaml

- override crypto-js and d3-color, mend vulns.

override crypto-js and d3-color

---

resources/web/deployment.yaml
src/shared/components/GenericList/GenericList.js
src/shared/components/GenericList/test/GenericList.test.js

- Fix thee dots menu problem if empty
Closes https://github.com/kyma-project/busola/issues/2677

Don't display toolbar if actions are empty

---

resources/web/deployment.yaml
src/shared/components/ReadableCreationTimestamp/ReadableCreationTimestamp.tsx

- shortened date format and added time

Display Timestamp in Dashboard

---

resources/web/deployment.yaml
src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js

- fix setting color for progress indicator

fix setting color of progressindicator

---

resources/web/deployment.yaml
src/resources/ServiceAccounts/ServiceAccountDetails.js
src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
src/resources/ServiceAccounts/TokenRequestModal/useGenerateTokenRequest.ts

Fix GenerateTokenModal Bug

---

resources/web/deployment.yaml
src/components/Extensibility/components/ResourceList.js
src/shared/components/GenericList/SearchInput.js
src/shared/components/ResourceDetails/ResourceDetails.js

- make search by `/` unavailable in all modals
- make search by `/` unavailable in resource detail view
- prevent firefox's native quick find 
Closes https://github.com/kyma-project/busola/issues/2732

Fix search focus

---

public/i18n/en.yaml
resources/web/deployment.yaml
src/components/Clusters/views/ClusterOverview/ClusterNodes.js
src/components/Clusters/views/ClusterOverview/ClusterStats.js
src/components/Nodes/MachineInfo/MachineInfo.js
src/components/Nodes/MachineInfo/MachineInfo.scss
src/components/Nodes/NodeDetails/NodeDetails.js
src/components/Nodes/NodeResources/NodeResources.js
src/components/Nodes/nodeQueries.js
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js

- Adjust Node view resources to cluster view resources
- Use ProgressIndicatorWithPercentage in Cluster view node list

Make node view is similar to cluster view

---

resources/web/deployment.yaml
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
tests/integration/tests/cluster/test-custom-resources.spec.js

Show full-screen icon only on last column

---

.github/workflows/cypress-tests.yml

add gardenlinux

---

docs/contributor/testing-strategy.md

- create a `test-strategy` document related to microdelivery requirements.

create test-strategy document

---

resources/web/deployment.yaml
src/resources/other/BusolaExtensions.routes.js

- fix displaying extensions view when column layout is disabled

fix: displaying extensions view

---

resources/backend/deployment.yaml
resources/web/deployment.yaml
tests/integration/scripts/busola-integration-k3s.sh

feat: use latest image tag and remove need for bumps

---

src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceDetails/ResourceDetails.scss

- adjust fullscreen to desing
https://github.com/kyma-project/busola/issues/2753

feat: set metadata styling when resource is fullScreen

---

package.json
src/testing/index.js

- add eslint-check command
- remove an unused file.

feat: add eslint-check and remove unused file

---

src/components/Extensibility/components/ResourceButton.js

- fix `ResourceButton` for modules-banner

fix resourceButton

---

src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js

- fixed theme names in Monaco Editor

fix: Monaco editor is white in dark theme

---

tests/integration/support/commands.js
tests/integration/support/login-commands.js
tests/integration/support/paste-to-monaco.js
tests/integration/tests/cluster/test-custom-resources.spec.js
tests/integration/tests/cluster/test-dashboard-version.spec.js
tests/integration/tests/namespace/z-run-after.spec.js

fix: stabilise cypress tests

---

src/components/App/ExtensibilityRoutes.js
src/components/CustomResources/CustomResources.js
src/components/CustomResources/CustomResourcesOfType.js
src/resources/CustomResourceDefinitions/CustomResources.details.js
src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
src/resources/createResourceRoutes.js
src/resources/other/CustomResourceDetails.routes.js
src/resources/other/CustomResourceListOfType.routes.js
src/resources/other/CustomResourcesByGroup.routes.js
src/shared/components/GenericList/GenericList.js
tests/integration/support/commands.js
tests/integration/support/paste-to-monaco.js
tests/integration/tests/cluster/test-custom-resources.spec.js
tests/integration/tests/extensibility/ext-test-services.spec.js

- fixed columns jumping in all Extensibility and Custom Resources views

fix: view is jumping with column layout on some views

---

src/components/App/ExtensibilityRoutes.js
src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
src/resources/createResourceRoutes.js
src/resources/other/BusolaExtensions.routes.js
src/resources/other/CustomResourcesByGroup.routes.js
src/resources/other/helmReleases.routes.js
src/shared/ResourceForm/components/Presets.js
src/shared/ResourceForm/components/ResourceForm.js
src/shared/ResourceForm/components/ResourceForm.scss
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
src/shared/components/ResourceCreate/ResourceCreate.js
src/shared/components/ResourceCreate/ResourceCreate.scss
src/shared/hooks/useProtectedResources.js
src/styles/index.scss

-Adjust edit/create layout so the scroll is only on form, not the header
- ...
- ...

feat: Adjust edit/create layout

---

src/components/Extensibility/ExtensibilityDetails.js
src/components/Extensibility/components/Tabs.js
src/components/Extensibility/components/Widget.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceDetails/ResourceDetails.scss
src/shared/components/ResourceDetails/ResourceDetailsCard.js

- changed positioning of Tabs-widget on the details view
- adjusted margins

fix: positioning of tabs-widget

---

src/resources/createResourceRoutes.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/ResourcesList/ResourcesList.js

fix: cloning resources is not working

---

src/components/Extensibility/ExtensibilityCreate.js

- Fix translations on create form
- Remove unused code

fix: Translations on create form

---

src/resources/Roles/RuleInput.js
src/shared/ResourceForm/fields/KeyValueField.js
src/shared/ResourceForm/fields/MultiInput.js

- Fix bug with alignment in MultiInlnput

fix: Fix bug with alignment

---

src/components/CustomResources/CustomResources.js
src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
src/shared/components/GenericList/GenericList.js
src/shared/components/ResourcesList/ResourcesList.js

- added handling redirect for some Custom Resources
- added handleRedirect prop in Resources/Generic list

fix: path in custom resources

---

resources/web/deployment.yaml
src/components/App/ExtensibilityRoutes.js
src/components/Clusters/views/ClusterOverview/ClusterNodes.js
src/components/CustomResources/CustomResources.js
src/components/CustomResources/GroupingListPage.js
src/components/Extensibility/components/Table.js
src/components/HelmReleases/HelmReleasesList.js
src/resources/Pods/ContainersLogs.js
src/resources/Pods/ContainersLogs.scss
src/resources/createResourceRoutes.js
src/resources/other/CustomResourcesByGroup.routes.js
src/shared/components/GenericList/GenericList.js
src/shared/components/GenericList/GenericList.scss
src/shared/components/GenericList/SearchInput.js
src/shared/components/GenericList/constants.js
tests/integration/support/commands.js
tests/integration/support/inspect-list.js
tests/integration/tests/cluster/test-command-palette.spec.js
tests/integration/tests/cluster/test-custom-resources.spec.js
tests/integration/tests/cluster/test-navigation-features.spec.js
tests/integration/tests/namespace/test-custom-resources.spec.js
tests/integration/tests/namespace/test-jobs.spec.js
tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
tests/integration/tests/namespace/test-reduced-permissions.spec.js
tests/integration/tests/namespace/test-resource-upload.spec.js
tests/integration/tests/namespace/z-run-after.spec.js

Merge main into in-page-edit

---

src/components/HelmReleases/HelmReleasesDetails.js
src/components/HelmReleases/HelmReleasesList.js
src/shared/ResourceForm/fields/MultiInput.scss
src/shared/components/GenericList/GenericList.js

- fixed rows to be clickable in Helm Releases list
- fixed closing Helm Releases details in column layout
- fixed search in Helm Releases

fix: helm releases list is not working properly

---

src/resources/Pods/ContainersData.js

- add resetting layout in onClik for the button to logs,
- fix navigate URL.

fix: navigate to logs of pod

---

src/components/Extensibility/components-form/Modules/Modules.js
src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
src/shared/components/CopiableText/CopiableText.js
src/shared/components/DescriptionHint/DescriptionHint.js
src/shared/components/EmptyListComponent/EmptyListComponent.scss
src/shared/components/EmptyListComponent/EmptyListComponent.tsx
src/shared/components/ExternalLink/CopiableLink.tsx
src/shared/components/ExternalLink/ExternalLink.tsx
src/styles/index.scss
tests/integration/tests/extensibility/ext-test-pizzas.spec.js

- replace `a` with `Link` fro UI5
https://github.com/kyma-project/busola/issues/2791

feat: Replace `a`  with `ui5link`

---

src/components/App/ExtensibilityRoutes.js
tests/integration/support/create-edit-support.js
tests/integration/support/createNamespace.js
tests/integration/support/exceptions.js
tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
tests/integration/tests/cluster/test-cluster-validation.spec.js
tests/integration/tests/cluster/test-command-palette.spec.js
tests/integration/tests/cluster/test-custom-resources.spec.js
tests/integration/tests/cluster/test-persistent-volumes.spec.js
tests/integration/tests/cluster/test-storage-classes.spec.js
tests/integration/tests/extensibility/ext-test-pizzas.spec.js
tests/integration/tests/extensibility/ext-test-services.spec.js
tests/integration/tests/extensibility/ext-test-variables.spec.js

feat: Adjust cluster tests

---

src/resources/other/helmReleases.routes.js
src/shared/ResourceForm/components/FormField.js
src/shared/ResourceForm/components/ResourceForm.js
src/shared/ResourceForm/components/Title.js
src/shared/components/DescriptionHint/DescriptionHint.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
src/shared/components/ResourceCreate/ResourceCreate.js
src/shared/components/ResourceCreate/ResourceCreate.scss
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/contexts/YamlEditorContext/EditorActions.js
src/shared/contexts/YamlEditorContext/EditorActions.scss

- fixed background color in two column layout
- fixed action buttons in resource form
- some action buttons in resource form are disabled in form mode
- headers are smaller in DynamicPage component
- fixed header wrapping in DynamicPage component
- fixed hint buttons
- fixed opening second column in Helm Releases

fix: in-page edit UX adjustments

---

src/components/Clusters/views/ClusterOverview/ClusterOverview.js
src/components/CustomResources/CustomResourcesOfType.js
src/components/CustomResources/GroupingListPage.js
src/components/HelmReleases/HelmReleasesDetails.js
src/components/HelmReleases/HelmReleasesList.js
src/components/Nodes/NodeDetails/NodeDetails.js
tests/integration/tests/namespace/test-resource-upload.spec.js

- fixed Upload YAML on Helm Releases view
- fixed Upload YAML on Custom Resources view

fix: Upload YAML is broken on some views

---

src/resources/CronJobs/CronJobCreate.js
src/resources/Deployments/DeploymentCreate.js
src/resources/Jobs/ContainersSection.js
src/resources/Jobs/JobCreate.js
src/resources/ReplicaSets/ReplicaSetCreate.js
src/resources/RoleBindings/GenericRoleBindingCreate.js
src/resources/RoleBindings/SubjectForm.js
src/shared/components/Deployment/ContainersViews.js
tests/integration/support/commands.js
tests/integration/support/inspect-list.js
tests/integration/tests/cluster/test-cluster-validation.spec.js
tests/integration/tests/namespace/test-jobs.spec.js
tests/integration/tests/namespace/test-reduced-permissions.spec.js
tests/integration/tests/namespace/test-service-accounts.spec.js

fix: Fix tests and simple/advanced changes

---

src/components/Extensibility/useGetInjection.js

fix: fix injections bug

---

public/i18n/en.yaml
src/components/AIassistant/components/AIassistant.js
src/components/AIassistant/components/AIassistant.scss
src/components/AIassistant/components/Chat.js
src/components/AIassistant/components/Chat/Chat.js
src/components/AIassistant/components/Chat/Chat.scss
src/components/AIassistant/components/Chat/messages/Bubbles.js
src/components/AIassistant/components/Chat/messages/Bubbles.scss
src/components/AIassistant/components/Chat/messages/ErrorMessage.js
src/components/AIassistant/components/Chat/messages/MessageWithList.js
src/components/AIassistant/components/Chat/messages/MessageWithList.scss
src/components/AIassistant/components/Chat/messages/PlainMessage.js
src/components/AIassistant/components/Chat/messages/PlainMessage.scss
src/components/AIassistant/components/IntroBox.scss
src/components/AIassistant/components/PageInsights.js
src/components/AIassistant/components/PageInsights/InsightPanel.js
src/components/AIassistant/components/PageInsights/InsightPanel.scss
src/components/AIassistant/components/PageInsights/PageInsights.js
src/components/AIassistant/components/PageInsights/PageInsights.scss
src/components/AIassistant/utils/getChatResponse.js
src/components/AIassistant/utils/getPromptSuggestions.js
src/components/Clusters/views/ClusterOverview/ClusterOverview.js
src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
src/components/HelmReleases/HelmReleasesDetails.js
src/header/Header.tsx
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceDetails/ResourceDetailsCard.js
src/styles/index.scss

feat: kyma companion prototype

---

public/i18n/en.yaml
src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
src/resources/Namespaces/YamlUpload/YamlResourcesList.js
src/resources/Namespaces/YamlUpload/YamlResourcesList.scss
src/resources/Namespaces/YamlUpload/YamlUpload.js
src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
src/resources/Namespaces/YamlUpload/YamlUploadDialog.scss
src/shared/components/MonacoEditorESM/Editor.scss
src/styles/wizard-dialog.scss
tests/integration/tests/namespace/test-resource-upload.spec.js
tests/integration/tests/namespace/test-resource-validation.spec.js

- make upload yalm view more similer to the other views
https://github.com/kyma-project/busola/issues/2845

feat: Adjust upload yaml to new desing standards.

---

src/components/Extensibility/components-form/MonacoRenderer.js

- fixed editing Nodejs function dependencies in JSON format

fix: edit Nodejs function dependencies in JSON format

---

src/sidebar/Sidebar.scss
src/sidebar/SidebarNavigation.tsx

- fixed padding in Sidenav, especially under namespace combobox

fix: paddings in Sidenav 

---

src/resources/CustomResourceDefinitions/CRCreate.js
src/shared/ResourceForm/useCreateResource.js

fix: fix edit cr

---

src/resources/LimitRanges/LimitRangeList.js
src/resources/ResourceQuotas/ResourceQuotaList.js
src/shared/components/EmptyListComponent/EmptyListComponent.scss
src/shared/components/EmptyListComponent/EmptyListComponent.tsx
src/shared/components/ExternalLink/ExternalLink.tsx
src/shared/components/GenericList/components.js
src/shared/components/Labels/Labels.js
src/shared/components/PodTemplate/components.js
src/shared/components/ResourceGraph/ResourceGraph.tsx
src/shared/components/ResourcesList/ResourcesList.js
src/shared/components/Selector/Selector.js
src/shared/components/UI5Panel/UI5Panel.js
src/styles/index.scss

- In table column use `<Text>` instead oof `<Label>`
- Add shadow to tables 
- Disable illustrated messages in the tables in resource overview pages: limit ranges and resource quotas
- Switch learn more `link` to a `button`
- Illustrated message use `size: auto`
- Fix selector table title

fix: Ux changes in tables

---

src/header/Logo/Logo.tsx
tests/integration/tests/namespace/test-service-accounts.spec.js

fix: link for SAP logo

---

src/components/App/NamespaceRoutes.tsx
src/components/CustomResources/CustomResourcesOfType.js
src/components/Extensibility/ExtensibilityDetails.js
src/components/Extensibility/ExtensibilityList.js
src/resources/CustomResourceDefinitions/CustomResources.details.js
src/resources/Events/EventDetails.js
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
src/resources/helpers.js

- fixed errors connected with useGet and useFetch sending requests with "undefined" instead of resource name

fix: get/fetch errors

---

src/components/Extensibility/components/Widget.js
src/components/Extensibility/contexts/DataSources.tsx
src/shared/components/RelatedPods.js

- fixed Extensibility Widgets data not updating after resource change

fix: Extensibility Widgets data not updating after resource change

---

src/resources/Namespaces/NamespaceCreate.js

- fixed create form column closing after creating namespace

fix: create form column is not closing after creating namespace

---

src/resources/Namespaces/NamespaceCreate.js
src/resources/Namespaces/NamespaceCreate.scss

- fixed height for YAML form in namespaces

fix: YAML form for namespaces is not working

---

public/defaultConfig.yaml
src/header/SidebarMenu/useGetBusolaVersion.ts
src/resources/Events/EventDetails.js
src/resources/Events/EventList.js

- fix: busola version
- fix: defaultConfig
- fix: icons for badges

fix: busola version and defaultConfig

---

CODEOWNERS
OWNERS_ALIASES

add Oliwia as codeowner

---

src/components/Clusters/views/ClusterOverview/ClusterOverview.js
src/components/Clusters/views/ClusterStorageType.js
src/components/Extensibility/useGetInjection.js

- fix: injections without name or order
- fix: getting undefined on currentContext

fix: injections without name or order

---

src/shared/hooks/useDeleteResource.js

- fix: redirect after deleting on extension list

fix: redirect after deleting on extension list

---

src/components/CustomResources/CustomResources.js
src/resources/CustomResourceDefinitions/CRCreate.js
src/resources/CustomResourceDefinitions/useCustomResourceUrl.js

- remove redirect in Custom Resources when resource has extension defined

fix: remove redirect in Custom Resources when resource has extension defined

---

public/i18n/en.yaml
src/shared/components/ResourcesList/ResourcesList.js

- Fix tooltip bug that causes extension list to load with error

fix: tooltip bug that causes extension list to load with error

---

src/components/Clusters/views/ClusterOverview/ClusterNodes.js
src/components/CustomResources/CustomResources.js
src/components/CustomResources/GroupingListPage.js
src/components/Extensibility/components/Table.js
src/components/HelmReleases/HelmReleasesList.js
src/resources/createResourceRoutes.js
src/shared/components/GenericList/GenericList.js
src/shared/components/GenericList/SearchInput.js
src/sidebar/Sidebar.scss
tests/integration/tests/cluster/test-custom-resources.spec.js

feat: brought back slash-shortcut

---

docs/extensibility/README.md

- Updated the extensibility README.md

Update Extensibility README

---

examples/pizzas/README.md

Update the Pizzas example

---

src/resources/ServiceAccounts/GenericSecrets.js

- Hide create button on service account details view

Hide create button on service account details view

---

src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidationConfiguration.js

- fix: add initial resource to cluster validation

fix: add initial resource to cluster validation

---

src/components/App/ClusterRoutes.js

- fixed error when opening an invalid link to Busola and after that opening a correct link obtained from BTP 

fix: displaying incorrect Shoot after invalid link

---

src/components/Clusters/views/ClusterOverview/ClusterDetails.js

Fix API server address text cut off

---

src/command-pallette/CommandPaletteProvider.tsx
src/components/Extensibility/ExtensibilityCreate.js
src/resources/ConfigMaps/ConfigMapCreate.js
src/resources/CronJobs/CronJobCreate.js
src/resources/CustomResourceDefinitions/CRCreate.js
src/resources/CustomResourceDefinitions/CustomResourceDefinitionCreate.js
src/resources/DaemonSets/DaemonSetCreate.js
src/resources/Deployments/DeploymentCreate.js
src/resources/Ingresses/IngressCreate.js
src/resources/Jobs/JobCreate.js
src/resources/LimitRanges/LimitRangeCreate.js
src/resources/Namespaces/NamespaceCreate.js
src/resources/NetworkPolicies/NetworkPolicyCreate.js
src/resources/PersistentVolumeClaims/PersistentVolumeClaimCreate.js
src/resources/PersistentVolumes/PersistentVolumeCreate.js
src/resources/Pods/PodCreate.js
src/resources/ReplicaSets/ReplicaSetCreate.js
src/resources/ResourceQuotas/ResourceQuotaCreate.js
src/resources/RoleBindings/GenericRoleBindingCreate.js
src/resources/Roles/GenericRoleCreate.js
src/resources/Secrets/SecretCreate.js
src/resources/ServiceAccounts/ServiceAccountCreate.js
src/resources/StatefulSets/StatefulSetCreate.js
src/resources/StorageClasses/StorageClassCreate.js

- fix: useEffect in command pallete for discard changes modal
- fix: useState instead of if to improve performance for every create file

fix: useState instead of if to improve performance for every create file

---

src/shared/ResourceForm/components/ResourceForm.js

- fix: taking data to useEffect for discard changes

fix: taking data to useEffect for discard changes

---

public/i18n/en.yaml
src/resources/ReplicaSets/ReplicaSetDetails.js
src/resources/ReplicaSets/ReplicaSetStatus.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceDetails/ResourceDetails.scss
src/shared/components/ResourceDetails/ResourceDetailsCard.js
src/shared/components/ResourceStatusCard/ResourceStatusCard.js
src/shared/components/ResourceStatusCard/ResourceStatusCard.scss

- Adjust Metadata
- Adjust status
- Add events
Apply such replica-set to see render condition:
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
name: test-conditions
namespace: default
spec:
replicas: 2
selector:
matchLabels:
app: test-conditions
template:
metadata:
labels:
app: test-conditions
spec:
containers:
- image: nginx
imagePullPolicy: Always
name: test-conditions
priorityClassName: high
```
https://github.com/kyma-project/busola/issues/2909

feat: adjust status and metadata in replica set detail view

---

src/components/Extensibility/components/ResourceList.js

feat: disable create in details resource lists

---

src/command-pallette/CommandPaletteProvider.tsx
src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.tsx
src/components/Clusters/components/AddClusterWizard.js
src/components/KymaModules/KymaModulesList.js
src/header/Header.tsx
src/header/NamespaceChooser/NamespaceChooser.tsx
src/shared/ResourceForm/components/ResourceForm.js
src/shared/ResourceForm/useCreateResource.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/GenericList/GenericList.js
src/shared/components/ResourceCreate/ResourceCreate.js
src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx
src/shared/components/UnsavedMessageBox/helpers.ts
src/sidebar/NavItem.tsx
src/sidebar/SidebarNavigation.tsx
src/state/formOpenAtom.ts
src/state/resourceEditedAtom.ts

fix: refactor discard changes

---

src/components/App/ExtensibilityRoutes.js
src/components/Extensibility/helpers/getExtensibilityPath.ts
src/resources/Namespaces/NamespaceCreate.js
src/resources/ServiceAccounts/ServiceAccountCreate.js
src/shared/ResourceForm/components/ResourceForm.js
src/shared/ResourceForm/useCreateResource.js

- fix: resourceType in Extensibility routes,
- fix: urlPath in getExtensibilityPath
- remove unused import
Closes #2927

fix: custom urlPath for extensibility

---

src/command-pallette/CommandPalletteUI/handlers/crHandler.ts
src/components/Extensibility/components/EventList.js
src/hooks/useMessageList.js
src/resources/Events/EventDetails.js
src/state/navigation/extensionsAtom.ts

- fix fetching events in resource details for all namespaces list
- fix generating links for Involved Objects in Events

fix: events are empty when you open details from all namespaces list 

---

Dockerfile
Dockerfile.local
backend/Dockerfile

fix: bump apline image

---

src/components/Extensibility/components-form/StringRenderer.js

- fixed handling pure integers values in CR form fields of type string and added case for int-or-string type

fix: handle pure integers values in CR form fields of type string

---

.github/workflows/busola-local-build.yml

- feat: add workflow for building busola-local

feat: add workflow for building busola-local

---

.github/workflows/busola-local-build.yml

- fix: rename of busola-local workflow job

fix: rename of busola-local workflow job

---

src/shared/ResourceForm/components/ResourceForm.js

fix: modeSelector for form

---

.github/workflows/busola-local-build.yml

- feat: add paths (old run_if_changed) for local build

feat: add paths for local build

---

Dockerfile
Dockerfile.local
backend/Dockerfile

- Add USER 1000 to final docker image
https://github.com/kyma-project/busola/issues/2936

feat: Add USER to dockerfiles

---

src/shared/components/Labels/Labels.scss

fix: responsiveness of labels

---

src/shared/components/GenericList/GenericList.js
src/shared/components/GenericList/SortModalPanel.js
src/shared/components/GenericList/SortModalPanel.scss
src/shared/components/Modal/Modal.js
tests/integration/tests/extensibility/ext-test-pizzas.spec.js

feat: Redesign of sort dialog

---

docs/extensibility/50-list-and-details-widgets.md
public/i18n/en.yaml
src/components/Clusters/views/ClusterOverview/ClusterDetails.js
src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesQuery.js
src/shared/components/CountingCard/CountingCard.tsx

- feat: modules baner on cluster details
- docs: adjust modify to add
- fix: getting kyma resource for add modules

feat: modules baner on cluster details

---

src/components/Extensibility/components/ResourceList.js
src/components/Extensibility/components/Widget.js
src/shared/components/ResourcesList/ResourcesList.js
src/shared/hooks/BackendAPI/config.js
src/shared/utils/helpers.js

- don't display widget when there the data is not loaded
- show rbac errors
- improve error message displayed in panel
- add resource definition not found error handling.

fix: improve error handling on details view

---

public/i18n/en.yaml
src/components/Preferences/OtherSettings.tsx
src/shared/components/GenericList/GenericList.js
src/shared/components/GenericList/Pagination/Pagination.js
src/shared/components/GenericList/Pagination/Pagination.scss
src/shared/components/GenericList/Pagination/test/Pagination.test.js
src/state/preferences/pageSizeAtom.ts

- Introduced local pagination overwrite
- Introduced ALL section, showcasing all items in one page
- new layout and styling

feat: new pagination

---

src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js

- fix: correctly count healty pods
https://github.com/kyma-project/busola/issues/2990

fix: correctly count healty pods

---

src/resources/Namespaces/NamespaceDetails.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceHealthCard/ResourceHealthCard.js

…Details
- Remove Monitoring and Health title from details except for Namespace details

fix: Remove Monitoring and Health title from details except for Namespace details

---

public/i18n/en.yaml
src/resources/ReplicaSets/ReplicaSetDetails.js
src/resources/StatefulSets/StatefulSetDetails.js

- Add events
- Add Status
- Add Replicas card
- Fix imports paths in replica sets

feat: Adjust Statefull Sets

---

src/components/BusolaExtensions/BusolaExtensionEdit.js

- Fix editing the extensions
https://github.com/kyma-project/busola/issues/2986

fix: Fix ediiting the extension

---

public/i18n/en.yaml
src/resources/DaemonSets/DaemonSetDetails.js

feat: adjust daemonsets

---

public/i18n/en.yaml
src/resources/Deployments/DeploymentDetails.js

- Adjust deployments status
- Add events

feat: Adjust deployments

---

public/i18n/en.yaml
src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesAddModule.scss
src/components/KymaModules/KymaModulesList.js
src/shared/components/PopoverBadge/PopoverBadge.scss

- added option to change channel for the module
- fixed columns in form

feat: allow to change channel for the module

---

src/components/KymaModules/KymaModulesCreate.js

fix: editing kyma resource

---

examples/injections/countingcard.yaml
src/shared/components/UI5RadialChart/test/UI5RadialChart.test.js
tests/integration/tests/cluster/test-cluster-overview.spec.js

- added unit test
- added test case to integration test (cluster overview)

test: added tests of radialgraph

---

public/i18n/en.yaml
src/resources/ReplicaSets/ReplicaSetDetails.js
src/resources/StatefulSets/StatefulSetDetails.js

- move info from card to status in replicasets and statefulsets

feat: move info from card to status in replicasets and statefulsets

---

src/components/KymaModules/KymaModulesList.js

- Disable delete if module is not in spec,
- Assign findStatus to a variable

fix: Disable delete if module is not in spec, assign findStatus to a variable

---

.github/workflows/busola-local-build.yml
.github/workflows/pull-integration-cluster-k3d.yml
.github/workflows/pull-integration-namespace-k3d.yml
.github/workflows/pull-lighthouse.yml

- feat: add worflow for cluster tests

feat: add worflow for cluster and lighthouse tests to GHA

---

README.md

- New entry in the troubleshooting guide about SSL connectivity issues in k3d cluster (tls-san)

docs: Documented SSL connectivity issues in the README

---

src/components/KymaModules/KymaModulesList.js
src/resources/other/kymaModules.routes.js
src/shared/components/GenericList/GenericList.js

- Disable link to module details
- Fix badge for deleting state

fix: Modules disable link

---

examples/extensions/configuration/namespace.yaml
examples/extensions/configuration/potatoes-crd.yaml
examples/extensions/configuration/potatoes-updates-details-view.yaml
examples/extensions/samples/potato.yaml
src/components/BusolaExtensions/BusolaExtensionCreate.js
src/components/BusolaExtensions/ColumnsInput.js
src/shared/ResourceForm/components/CollapsibleSection.js
tests/integration/cypress.config.js
tests/integration/support/navigate-to.js
tests/integration/tests/extensibility/ext-test-extensibility.spec.js
tests/integration/tests/namespace/test-ingresses.spec.js
tests/integration/tests/namespace/test-jobs.spec.js

- Add extensibility test
- Fix extensibility create dialog

test: e2e extensibility

---

src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesList.js

- fix: modules view when modules are not presented in Kyma CR

fix: modules view when modules are not presented in Kyma CR

---

Dockerfile
Dockerfile.local
backend/Dockerfile

Bump images to get avoid of vulerabilities
- Bump alpine image

chore: bump alpine image

---

public/i18n/en.yaml
src/components/Clusters/views/ClusterOverview/ClusterStats.js
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js

- Add `pending` section
- Use very similar logic to mark `healthy` pods  used in pods list
https://github.com/kyma-project/busola/issues/3015

feat: Improve pods statistics

---

.github/workflows/pull-unit-tests.yml
Dockerfile
Dockerfile.local
package-lock.json

- separate unit tests from build
- remove running unit tests from Dockerfiles

feat: separate workflow for unit tests

---

package-lock.json
package.json
src/shared/contexts/ErrorModal/ErrorModal.scss

- remove node-sass library and add sass
- adjust CSSes
Closes #2385 

chore: remove node-sass library and add sass

---

src/shared/ResourceForm/components/ResourceForm.js

- fix: checking is form is open
Closes #3084 

fix: checking is form is open

---

docs/extensibility/README.md
docs/extensibility/jsonata.md
docs/extensibility/resources.md
docs/extensibility/wizard.md

docs: fix links

---

Dockerfile
Dockerfile.local
backend/Dockerfile

- chore: remove unused packages from dockerfiles
Closes #3042 

chore: remove unused packages from dockerfiles

---

public/i18n/en.yaml
src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesList.js

- feat: add badge for overriden channel
- fix: add beta to translations
Closes #3080 

feat: add badge for overriden channel

---

src/components/KymaModules/ModulesCard.js

- add data-testid for advanced panel for module

chore: add data-testid for advanced panel for module

---

src/components/Extensibility/components-form/MonacoRenderer.js

- Display tooltip on monaco editor label

feat: Show description tooltip on editor component

---

Dockerfile
Dockerfile.local
backend/Dockerfile

chore: Bump alpine and nginx images

---

public/i18n/en.yaml
src/components/Extensibility/ExtensibilityDetails.js
src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesList.js
src/resources/CustomResourceDefinitions/CustomResources.details.js
src/resources/other/kymaModules.routes.js
src/shared/components/ResourceDetails/ResourceDetails.js

- modules can now be deleted from details view
- bugfix: delete multiple modules without needing to refresh the page
- code refactoring: moved state from ModulesList and AddModules further up the hierarchy for better code organization
- close details view after deletion
#3079 

feat: delete modules from details

---

src/components/Nodes/NodeDetailsCard.js

- fix undefined on the address for hostname or internalIP

fix: nodes details

---

src/components/BusolaExtensions/BusolaExtensionDetails.js
src/resources/Roles/RuleInput.js
src/shared/ResourceForm/fields/KeyValueField.js
src/shared/components/CopiableText/CopiableText.js
src/shared/components/GenericList/SortModalPanel.js
src/shared/components/ListActions/ListActions.js
src/shared/components/ListActions/ListActions.scss
src/shared/components/Modal/Modal.js
src/shared/components/ModalWithForm/ModalWithForm.js
src/shared/components/ResourceCreate/ResourceCreate.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceGraph/SaveGraphControls.tsx
src/shared/hooks/useDeleteResource.js

see related issues
- changed button design to be secondary in extension details table
- changed button design to be tertiary in the delete resource dialog
- bug fix: sort modal opens up although button is disabled
- removed all double tooltips on buttons (moved custom tooltip to be displayed as browser tooltip)
- resourceGraph uses icon button component
#3005 #3006 #3007 #3009 #3039 

fix: bug fixes

---

src/components/Clusters/views/ClusterOverview/ClusterNodes.js
src/shared/components/Link/Link.tsx
tests/integration/tests/cluster/test-cluster-overview.spec.js

- fix: link for node details on cluster overview
- fix: add wrappingType to Link component
- chore: add data-testID
- tests: adjust cluster overview test
Closes #3010

fix: links in tables

---

public/schemas/schema-general.yaml
public/schemas/schema-wizard.yaml

- feat: add schema for wizards
Closes #2432 

feat: add schema for wizards

---

src/components/Extensibility/ExtensibilityDetails.js
src/components/KymaModules/KymaModulesList.js
src/resources/CustomResourceDefinitions/CustomResources.details.js
src/resources/other/kymaModules.routes.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceNotFound/ResourceNotFound.js
src/shared/helpers/linkExtractor.tsx
src/shared/hooks/BackendAPI/useGet.js

- fixed URL in changing in Modules view after refresh
- fixed modules sometimes displaying empty page when details can't be fetched
- fixed closing second column when there are no module details
- fixed module details displaying different resource in details when deleting
Closes #3106 

fix: refresh on module details and module details not working properly

---

src/shared/components/GenericList/components.js

For some views the arrow positioning of table list items was not the very end of the item
- adjusted positioning of list items' arrow icon to be at the very end of the item
#3008 

fix: error positioning of table items

---

src/resources/ConfigMaps/ConfigMapDetails.js
src/resources/DaemonSets/DaemonSetDetails.js
src/resources/Deployments/DeploymentDetails.js
src/resources/Jobs/JobDetails.js
src/resources/Jobs/JobList.js
src/resources/Pods/PodDetails.js
src/resources/ReplicaSets/ReplicaSetDetails.js
src/resources/Secrets/SecretDetails.js
src/resources/StatefulSets/StatefulSetDetails.js
src/shared/components/ControlledBy/ControlledBy.js

- clicking the ControlledBy link of a resource when currently on all-namespaces, will redirect to the specific namespace of the resource
#3003

fix: ControlledBy link for all namespaces

---

public/i18n/en.yaml
src/resources/NetworkPolicies/LabelSelector.js
src/resources/NetworkPolicies/NetworkPolicyDetails.js
src/shared/components/LayoutPanelRow/LayoutPanelRow.js
src/shared/components/Selector/Selector.js

- added events table to details
- improved label selector ui
- moved policyTypes from metadata panel to specification panel
#3207

feat: enhance network policies

---

docs/extensibility/statics.md
examples/statics/statics-external-nodes.yaml

- add example for External Nodes in static extensions

docs: add example for External Nodes in static extensions

---

public/i18n/en.yaml
src/resources/StorageClasses/PersistentVolumeClaimsList.js
src/resources/StorageClasses/PersistentVolumesList.js
src/resources/StorageClasses/StorageClassDetails.js

- feat: move config to configuration panel
- feat: move parameters to configuration panel
https://github.com/kyma-project/busola/issues/2857

feat: Enhance Storage Classes

---

.github/workflows/busola-backend-build.yml
.github/workflows/busola-local-build.yml
.github/workflows/busola-web-build.yml

- feat: add latest tag to builds

feat: add latest tag to builds

---

src/shared/components/ResourceGraph/DetailsCard/DetailsCard.tsx

- fixed redirect to resource in Resource Graph

fix: fix redirect to resource in Resource Graph

---

.dockerignore

- chore: add git dir to dockerignore

chore: add git dir to dockerignore

---

.dockerignore
Dockerfile
Dockerfile.local

And some minor Dockerfile optimizations
- Fix nginx permissions, wasn't owned by the `nginx` user
- Use yq to alter yaml, it's more reliable than sed
- Extend `.dockerignore` to avoid sending over unnecessary data
-

fix: nginx.conf permissions in container

---

Dockerfile
Dockerfile.local

- Fixes the missed `default_tag` handling in the previous commit

fix: default_tag in docker build

---

Dockerfile

- Chown in the final stage using `USER` switches in Dockerfile
- chown the appdir as well
- Use exact version of the nginx container image

fix: More chown and version pinning

---

src/resources/CustomResourceDefinitions/CustomResourceDefinitionCreate.js
src/resources/DaemonSets/DaemonSetCreate.js
src/resources/PersistentVolumes/PersistentVolumeCreate.js
src/resources/Pods/PodCreate.js
src/resources/StatefulSets/StatefulSetCreate.js
src/resources/StorageClasses/StorageClassCreate.js

fix: editing resources 

---

src/resources/LimitRanges/LimitRangeSpecification.scss
src/resources/Pods/ContainersLogs.scss
src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.scss

- fix deprecated nesting in SCSSes
Closes #3307 

fix: adjust SCSSes

---

src/shared/components/GenericList/GenericList.js
src/shared/components/ResourcesList/ResourcesList.js

- list entries need to match the namespace in addition to the name to be selected
#3306

fix: bug onRowClick with duplicate names

---

src/components/Extensibility/ExtensibilityDetails.js

feat: Add visibility to status

---

kyma/extensions/discovery-and-network/services.yaml

- sync of changes
https://github.com/kyma-project/busola/issues/3298

feat: sync kyma dashboard with PR https://github.com/kyma-project/kyma-dashboard/pull/376

---

src/resources/Jobs/ContainersSection.js
tests/integration/tests/namespace/test-jobs.spec.js

- fix: defaultOpen for job containers
UXes request

fix: defaultOpen for job containers

---

src/components/Extensibility/ExtensibilityWizard.js
src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
src/resources/Namespaces/YamlUpload/useUploadResources.js

- uploading a resource that already exists, will compare the resource to be uploaded with the already existing resource
#3327

fix: edit resource from upload yaml

---

backend/Dockerfile
backend/package-lock.json
backend/package.json

- use newest alpine
- bump express

chore: bump deps in backend image

---

package-lock.json
package.json
public/i18n/en.yaml
src/components/BusolaExtensions/BusolaExtensionDetails.js
src/components/Clusters/views/ClusterOverview/ClusterDetails.js
src/components/Clusters/views/ClusterOverview/ClusterNodes.js
src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
src/components/Extensibility/components-form/Jsonata.js
src/components/Extensibility/components-form/MonacoRenderer.js
src/components/Extensibility/components-form/SimpleList.js
src/resources/RoleBindings/RoleForm.js
src/resources/Secrets/SecretCreate.js
src/shared/ResourceForm/components/FormField.js
src/shared/ResourceForm/components/FormField.scss
src/shared/ResourceForm/fields/MultiInput.js
src/shared/ResourceForm/inputs/Checkboxes.js
src/shared/ResourceForm/inputs/ComboboxInput.js
src/shared/ResourceForm/inputs/Dropdown.js
src/shared/ResourceForm/inputs/Number.js
src/shared/ResourceForm/inputs/Switch.js
src/shared/ResourceForm/inputs/Text.js
src/shared/components/K8sResourceSelect.js
src/shared/components/ResourceDetails/ResourceDetails.scss
src/shared/components/ResourceRef/ExternalResourceRef.js
tests/kyma/tests/namespace/test-dns-providers.spec.js
tests/kyma/tests/namespace/test-issuers.spec.js

- reduced component hierarchy for form components (removed unnecessary divs and flexboxes)
#3351

fix: section editor performance

---

src/components/Clusters/views/ClusterList.js

- resetting the layout state on ClusterList resolved the issue
#2947

fix: incorrect redirect after new cluster is added

---

.github/workflows/lint-markdown-links-daily.yml
.github/workflows/lint-markdown-links-pr.yml

- use allowed version markdown lint check

fix: use allowed version of markdown lint check

---

src/components/KymaModules/KymaModulesList.js
src/shared/components/DescriptionHint/DescriptionHint.tsx
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/ResourceDetails/ResourceDetails.js

- added ariaTitle prop to DescriptionHint
- separated header text and description in Modules header
Closes #3141, closes #3143, closes #3144

fix: accessiblity - Info button in resources headers

---

.github/workflows/accessibility-tests.yml
tests/integration/tests/accessibility/test-namespace-overview.spec.js

tests: trigger acc test

---

.github/workflows/accessibility-tests.yml

chore: add ref for checkout in ACC GHA

---

.github/workflows/accessibility-tests.yml

- chore: install kyma on k3d for  accessbility tests

chore: install kyma on k3d for  accessbility tests

---

tests/integration/package.json

fix: Use correct image in tests package.json

---

.github/workflows/pull-integration-cluster-k3d.yml
.github/workflows/pull-integration-namespace-k3d.yml
tests/integration/package.json
tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
tests/integration/tests/cluster/test-edit-cluster.spec.js

- chore: hardcode older version of chrome for cypress

chore: hardcode older version of chrome for cypress

---

public/i18n/en.yaml
src/header/Header.tsx
src/header/SidebarSwitcher/SidebarSwitcher.tsx
src/shared/ResourceForm/components/CollapsibleSection.js
src/shared/components/DescriptionHint/DescriptionHint.tsx

- provide text alternatives for Side navigation , ‘Feedback’ and ‘Information’ buttons 
- fix double focus in the CollapsibleSection
Closes #3134, Closes #3156 

fix: accessibility - add tooltips and fix collapsibleSection focus

---

src/state/useAfterInitHook.ts

- fix redirect after double slashes
Closes #3355 

fix: fix redirect after double slashes

---

.github/workflows/accessibility-tests.yml

chore: fix acc workflow

---

src/shared/ResourceForm/components/CollapsibleSection.js
tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
tests/integration/tests/extensibility/ext-test-extensibility.spec.js
tests/integration/tests/extensibility/ext-test-variables.spec.js
tests/integration/tests/kyma-namespace/a-run-before.spec.js
tests/integration/tests/kyma-namespace/test-certificates.spec.js
tests/integration/tests/kyma-namespace/test-dns-providers.spec.js
tests/integration/tests/kyma-namespace/test-services.spec.js
tests/integration/tests/namespace/a-run-before.spec.js
tests/integration/tests/namespace/test-config-maps.spec.js
tests/integration/tests/namespace/test-cron-jobs.spec.js
tests/integration/tests/namespace/test-deployments.spec.js
tests/integration/tests/namespace/test-jobs.spec.js

- fix labels for expand/collapse buttons in Panel
- adjust tests
Closes #3142 

fix: labels for expand/collapse buttons in Panel

---

src/header/Header.tsx

- fixed logo title being announced entirely
#3135

fix: accessibility of kyma logo

---

src/resources/helpers.js
src/shared/components/GenericList/GenericList.js

- remove linebreak character at end of url paths in safari
#3411

fix: backend requests in safari

---

backend/request-filters.test.js

test: adjust unit tests to previous debugging changes

---

nginx/nginx.conf

- do not execute scripts loaded via data: URIs

fix: make CSP stricter

---

public/i18n/en.yaml
src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/components/ModuleStatus.tsx

- add second badge for modules status as a second status column
Closes #3119 

feat: add second badge for modules status

---

backend/common.js
backend/request-filters.js
backend/request-filters.test.js

- removed invalid header filter
- reverted prebious debugging changes

fix: remove invalid header filter

---

.github/workflows/busola-build.yml
.github/workflows/busola-web-build.yml

- Trigger web related build when changes are done to nginx.

fix: Fix build web trigger

---

.github/workflows/pull-kyma-integration-tests.yml
public/i18n/en.yaml
src/components/KymaModules/ChannelWarning.tsx
src/components/KymaModules/KymaModulesCreate.js
src/components/KymaModules/KymaModulesCreate.scss
src/components/KymaModules/ManagedWarnings.tsx
src/components/KymaModules/UnmanagedModuleInfo.tsx
src/components/KymaModules/components/ModuleStatus.tsx

- feat: add a checkbox to change managed/unmanaged modules
- add warning when changing managed/unmanaged
- add warning on save with managed/unmanaged changes
- add info if some of the module is unmanaged
Closes https://github.com/kyma-project/busola/issues/3357

feat: add checkbox to display managed modules

---

src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts
src/command-pallette/CommandPalletteUI/handlers/crHandler.ts
src/command-pallette/CommandPalletteUI/handlers/crListHandler.ts
src/command-pallette/CommandPalletteUI/handlers/crdHandler.ts
src/command-pallette/CommandPalletteUI/handlers/helmReleaseHandler.ts
src/command-pallette/CommandPalletteUI/handlers/logsHandler.ts
src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.ts
src/command-pallette/CommandPalletteUI/handlers/nodesHandler.ts
src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.ts
src/components/Clusters/shared.ts
src/components/Clusters/views/ClusterList.js
src/header/Header.tsx
src/hooks/useUrl.ts
src/resources/Namespaces/NamespaceList.js
src/shared/hooks/useDeleteResource.js
src/state/authDataAtom.ts
src/state/useAfterInitHook.ts

- added URI encoding of contextname to URL navigation
#3409

fix: allow usage of special characters in cluster context by encoding

---

.github/ISSUE_TEMPLATE/epic.md

- docs: add issue template for epics

docs: add issue template for epics

---

src/shared/components/GenericList/SearchInput.js

fix: Fix search slash

---

docs/extensibility/60-form-widgets.md
public/schemas/schema-form.yaml
src/components/Extensibility/components-form/NumberRenderer.js
src/shared/ResourceForm/inputs/ComboboxInput.js

- added enum parameter for Number Form Widget (like Text Form Widget)
- updated Form Widget documentation to reflect new feature
Resolves #3443

feat: enum parameter for Number Form Widget

---

src/shared/contexts/NotificationContext.tsx

fix: toast adjustments

---

docs/extensibility/50-list-and-details-widgets.md

- Fix not working links in docs

fix: wrong links

---

src/shared/components/Tokens.js

- adjust tokens not to be selectable
#3422 

fix: adjust tokens

---

src/resources/Deployments/DeploymentCreate.js

- Add replicas to deployment form

feat: Add replicas to deployment form

---

docs/extensibility/50-list-and-details-widgets.md
src/components/Extensibility/components/FeaturedCard/FeaturedCard.js

As part of the issue https://github.com/kyma-project/api-gateway/issues/1423 the information for deprecation of APIRule v1beta1 in the API Gateway module must be displayed to the UI.
It was decided by the team that the FeatureCard is the best option to display this information. The FeatureCard allows only two illustrations for `Modules` and `AI` for now.
Both of those illustrations doesn't match for the use-case. It would be good to allow FeatureCards without any illustration so it can be used in more use-cases.
- Add new `None` option for illustration in FeatureCard
- https://github.com/kyma-project/api-gateway/issues/1423
- docs: Documentation only …

feat: FeatureCard without illustration

---

src/components/Clusters/views/ClusterOverview/ClusterOverview.js
src/components/Clusters/views/ClusterOverview/ClusterStats.js
src/components/Clusters/views/EditCluster/EditCluster.js
src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
src/components/KymaModules/ModulesCard.js
src/components/Nodes/NodeDetails/NodeDetails.js
src/resources/CustomResourceDefinitions/CurrentCRDVersion.js
src/resources/Namespaces/AllNamespacesDetails.js
src/resources/Namespaces/YamlUpload/YamlResourcesList.js
src/resources/ResourceQuotas/ResourceQuotaDetails.tsx
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/ResourceDetails/ResourceDetails.js
src/shared/components/ResourceHealthCard/ResourceHealthCard.js

fix: adjust headers size

---

src/hooks/useGetSchema.js
src/resources/ConfigMaps/ConfigMapCreate.js
src/resources/CronJobs/CronJobCreate.js
src/resources/Jobs/ContainersSection.js
src/resources/Jobs/JobCreate.js
src/resources/Jobs/ScheduleSection.js
src/resources/Namespaces/NamespaceCreate.js
src/resources/RoleBindings/GenericRoleBindingCreate.js
src/resources/Roles/GenericRoleCreate.js
src/resources/Roles/RuleInput.js
src/resources/Secrets/SecretCreate.js
src/resources/createResourceRoutes.js
src/shared/ResourceForm/fields/ItemArray.js
src/shared/ResourceForm/fields/RichEditorDataField/RichEditorDataField.js
tests/integration/tests/namespace/test-cron-jobs.spec.js

- added tooltips to other resource forms
- bugfix: update schema context when the current resource changes
#3290

feat: add tooltips for other resource forms

---

src/shared/components/Spinner/Spinner.tsx

- adjust spinner size to new props

fix: spinner

---

.github/workflows/busola-web-build.yml

- allow build to be run against `release` feature branch to speed up development of release workflow
- ...
- ...
https://github.com/kyma-project/busola/issues/3375

chore: Allow run web-build against release featue branch

---

public/i18n/en.yaml
src/components/Nodes/MachineInfo/MachineInfo.js
src/components/Nodes/NodeDetails/NodeDetails.js
src/components/Nodes/NodeDetailsCard.js
src/components/Nodes/NodeResources/NodeResources.js
src/components/Nodes/nodeQueries.js
src/components/Nodes/nodeQueries.test.js
src/resources/Namespaces/ResourcesUsage.js
src/shared/components/UI5RadialChart/UI5RadialChart.js
src/shared/utils/helpers.js

- Calculate pod resources per node
https://github.com/kyma-project/busola/issues/2817

feat: Show resoruces per node

---

src/components/App/App.tsx

fix: theme is not working

---

src/components/Extensibility/components/ExternalLink.js
src/resources/other/kymaModules.routes.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
src/shared/components/ResourceDetails/ResourceDetails.js
tests/integration/tests/cluster/test-custom-resources.spec.js
tests/integration/tests/namespace/test-service-accounts.spec.js

- Don't truncate buttons
- Show more buttons on details

fix: Truncated deep links

---

kyma/extensions/kyma/kyma.yaml
src/components/Extensibility/components/Badge.js
src/components/Extensibility/helpers/jsonataWrapper.ts

- Display Module Status and Installation Status on kyma details page (extensibility)

feat: Display modules status in the same way on all views

---

src/resources/Namespaces/AllNamespacesDetails.js

fix: fix all namespaces

---

src/header/Header.tsx

- adjusted  logo accessibility to uI5 V2
#3422 

fix: UI5 logo accessibility

---

src/header/Header.tsx
src/styles/index.scss
src/styles/reset.css

- removed unneeded properties from reset.css
- minor adjustments

adjust reset.css

---

docs/contributor/testing-strategy.md

- change naming of the workflows from prow convention to github actions
- add information about testing Kyma envs
- add information about accessibility tests

docs: adjust testing strategy to github actions and add new workflows

---

sec-scanners-config.yaml

- chore: add package-locks to exclude for checkmarx

chore: add package-locks to exclude for checkmarx

---

.github/workflows/accessibility-tests.yml
tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js

- tests: fix cron job acc test

tests: fix cron job acc test

---

backend/index.js

- proxy should handle all HTTP methods not only GET

Fix proxy endpoint

---

src/shared/components/GenericList/components.js

- fixed selected prop not working in the tables
#3422 

fix: selected prop is not working in the tables

---

index.html

- add unsafe eval for accessibility tests

chore: add unsafe eval for accessibility tests

---

src/components/Extensibility/components/FeaturedCard/FeaturedCard.scss
src/components/Preferences/Preferences.scss
src/resources/createResourceRoutes.js
src/shared/components/ExpandableListItem/ExpandableListItem.tsx
src/shared/components/GenericList/SortModalPanel.js
src/shared/components/Labels/Labels.js
src/shared/components/PodTemplate/components.js
src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
src/sidebar/Sidebar.scss
tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
tests/integration/tests/accessibility/test-acc-extensions.spec.js
tests/integration/tests/accessibility/test-acc-pizzas.spec.js

- fix Preferences modal styling
- fix resource conditions Badge
- fix ListGroupItems headers
- fix Banner causing overflow
- fix ProgressIndicatior applying colors with delay
#3422 

fix: small leftover bugs 

---

src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesCreate.js
src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/ModulesCard.js

- Display documentation URL from spec.info
- Find proper module on list
- Fix keys in dropdowns (add and edit modules)

feat: Modules docs url

---

kyma/extensions/discovery-and-network/horizontal-pod-autoscalers.yaml

- Adjust hpa yaml and move status to status.body

fix: Adjust hpa status in yaml

---

src/shared/components/MonacoEditorESM/Editor.scss

- Fixes form editor covering header
Closes #3544 

fix: Fix for editor popover

---

src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesCreate.js
src/components/KymaModules/KymaModulesList.js

- add beta check in ModuleReleaseMeta for add modules
- add beta check in ModuleReleaseMeta for Edit view
- add beta check in ModuleReleaseMeta for List view
Closes #3519 

feat(Modules): Add beta check for ModuleReleaseMeta

---

backend/package.json

- Set limit to 24kB because some k8s heaers are very big and bigger than default value 8kB
Default limit changed in: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-12-26-version-10150-dubnium-lts-mylesborins

chore: set header limit to 24kB

---

tests/lighthouse/package-lock.json
tests/lighthouse/package.json

- Upgradae ligthhouse to newest version to fix tests

chore: fix lighthouse tests by playwright upgrade 

---

src/shared/components/K8sResourceSelect.js

fix: ui5 combobox display strange value

---

src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.tsx
src/components/Extensibility/components/Badge.js
src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx
tests/integration/package-lock.json
tests/integration/package.json
tests/integration/tests/cluster/test-command-palette.spec.js

- fixed Command Palette shouldn't navigate when Form is edited 
- added test case
- upgraded Cypress version in integration test
#3422 

fix: Command Palette shouldn't navigate when Form is edited 

---

.github/scripts/upload_assets.sh

- fix generating k8s yaml in release process

fix: fix generating k8s yaml in release process

---

src/components/App/ContentWrapper/ContentWrapper.scss
src/shared/components/GenericList/components.js
src/shared/components/Spinner/Spinner.tsx
tests/integration/tests/cluster/test-navigation-features.spec.js

- removed unused CSS from ContentWrapper.css
- small adjustments
#3422

fix: remove unused CSS and small adjustments

---

src/components/Clusters/views/ClusterOverview/ClusterDetails.js
src/components/Clusters/views/ClusterOverview/ClusterStats.js
src/components/Clusters/views/ClusterOverview/ClusterStats.scss
src/components/Extensibility/components-form/FormGroup.scss
src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
src/components/Extensibility/components/FeaturedCard/FeaturedCard.scss
src/components/Extensibility/components/RadialChart.js
src/components/Extensibility/components/StatisticalCard.js
src/components/KymaModules/KymaModulesAddModule.js
src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
src/resources/Namespaces/ResourcesUsage.js
src/resources/other/kymaModules.routes.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
src/shared/components/GenericList/Pagination/Pagination.scss
src/shared/components/GenericList/Pagination/test/Pagination.cy.js
src/shared/components/PodTemplate/PodTemplate.js
src/shared/components/PodTemplate/PodTemplate.scss
src/shared/components/ResourceDetails/ResourceDetails.scss
src/shared/components/ResourceStatusCard/ResourceStatusCard.scss
src/shared/components/UI5Panel/UI5Panel.scss
tests/integration/tests/namespace/test-persistent-volume-claims.spec.js

- removed some unused properties and css styling
- fixed container selector (by adding container-type: inline-size to parent components)

fix: container selector

---

.github/workflows/pull-unit-tests.yml

- unit test workflow now runs for any changes in the entire cypress folder

test: adjust unit test workflow

---

.github/workflows/accessibility-tests.yml

- serve busola in different way on port 300

fix: fix accessibility tests

---

.github/workflows/accessibility-tests.yml

- get kubeconfig for `kyma` cluster not `k3DCluster` which doesn't exist

fix: accesibility tests choose correct k3d cluster

---

src/components/Nodes/nodeQueries.js
src/resources/Namespaces/ResourcesUsage.js
src/shared/helpers/resources.js

- fix unit format to return proper value
- improve rendering when resource quota is not loaded and is null value

fix: fix displaying namespace resource

---

src/components/KymaModules/KymaModulesList.js
src/shared/components/Labels/Labels.js

fix: UI5 adjust badges

---

src/components/Extensibility/components/tests/Badge.cy.js
src/components/Extensibility/helpers/index.js
src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/components/ModuleStatus.tsx
src/resources/Deployments/DeploymentDetails.js
src/shared/components/ExpandableListItem/ExpandableListItem.tsx

- adjusted badges types
#3422 

fix: adjust badges after overriding functionality

---

src/components/CustomResources/GroupingListPage.scss
src/resources/other/CustomResourcesByGroup.routes.js

- using Suspense to gently open the columns,
- removing unnecessary scroll under list item.
Closes #3533 

fix: Custom resources details wrong opening

---

sec-scanners-config.yaml

- Add checkmarx one to sec-config
tools/kyma/test-infra/issues/444

chore: Add checkmarx one to sec-config

---

sec-scanners-config.yaml

- chore: exclude .github dir for cxone

chore: Exclude .github dir for cxone

---

sec-scanners-config.yaml

- chore: exclude cypress dir for cxone

chore: Exclude cypress dir for cxone

---

src/header/Header.scss
src/header/Logo/Logo.tsx

- fixed buttons overlapping in header on 320px screens
Closes #3159 

fix: Buttons overlapping in Header

---

.github/pull-request-template.md
.github/workflows/pr-title-check.yml

chore: Add new PR prefix

---

src/sidebar/Sidebar.scss
src/sidebar/SidebarNavigation.tsx

chore: Remove hide-shadow

---

src/components/KymaModules/KymaModulesEdit.js
src/resources/Jobs/ScheduleSection.js
src/resources/Namespaces/MemoryQuotas.js
src/shared/ResourceForm/components/FormField.js
src/shared/ResourceForm/fields/KeyValueField.js
src/shared/ResourceForm/fields/RuntimeResources.js
src/shared/ResourceForm/inputs/ComboboxInput.js

- Adjusted accessible names in Edit Modules
- Added accessible names for form fields
Closes #3147 

fix: Adjust accessible names for form fields

---

src/sidebar/Sidebar.scss
src/sidebar/SidebarNavigation.tsx

- fixed SidebarNavigation margins

fix: SidebarNavigation margins

---

src/shared/components/DescriptionHint/DescriptionHint.tsx
src/shared/components/DynamicPageComponent/DynamicPageComponent.scss

- adjusted DynamicPage header margins
- fixed snapping on header click

fix: Adjust DynamicPage header margins and fix click

---

backend/index.js

- chore: Disable proxy endpoint due to https://github.com/kyma-project/busola/issues/3680
Closes #3679 

chore: Disable proxy endpoint

---

.github/scripts/create_changelog.sh
.github/workflows/create-release.yml

- chore: Adjust informations in changelog
Closes #3632 

chore: Adjust informations in changelog

---

.github/scripts/create_changelog.sh

Chore release messegaes 2

---

src/components/KymaModules/KymaModulesList.js

- feat: Add unmanaged info on Modules List
Closes #3638 

feat: Add unmanaged info on Modules List

---

src/shared/ResourceForm/components/ModeSelector.js
src/shared/ResourceForm/components/ResourceForm.scss
src/shared/components/ResourceCreate/ResourceCreate.js
src/styles/index.scss

- fix: Width of the buttons (ACC 282.1)
Closes #3157 

fix: Width of the buttons (ACC 282.1)

---

.github/workflows/busola-build.yml
.github/workflows/pull-kyma-integration-tests.yml

- revert changes made while solving the issue 
Related issue(s)**
https://github.com/kyma-project/busola/issues/3670

revert: Revert gh actions changes

---

src/components/KymaModules/KymaModulesAddModule.scss

- adjusted Add Modules form to fit better on small screens
Closes #3158 

fix: Improve Add Modules layout on small screens

---

.github/workflows/accessibility-tests.yml
.github/workflows/pull-integration-cluster-k3d.yml
.github/workflows/pull-integration-namespace-k3d.yml
.github/workflows/pull-kyma-integration-tests.yml
.github/workflows/pull-lighthouse.yml
.github/workflows/pull-smoke-test-prod.yml
.github/workflows/pull-smoke-test-stage.yml
.github/workflows/pull-unit-tests.yml
Dockerfile
Dockerfile.web
README.md
backend/Dockerfile
kyma/README.md

- bumped Alpine version in backend image

chore: Bump Alpine and Node.js

---

src/components/KymaModules/support.ts

- fix: Undefined in module name
Closes #3696 

fix: Undefined in module name

---

kyma/package-lock.json
kyma/package.json
src/shared/contexts/NotificationContext.tsx

- add accessible name to toasts
Closes #3152 

fix: Acc 264.4

---

src/hooks/useSentry.js

- feat: Add replay session for sentry

feat: Add replay session for sentry

---

src/hooks/useSentry.js

fix: Sentry replays

---

kyma/environments/dev/config.yaml
kyma/environments/stage/config.yaml
public/defaultConfig.yaml

chore: Disable snow feature

---

src/shared/components/GenericList/GenericList.js

- fix: Revert changes in genericlist

fix: Revert changes in genericlist

---

src/components/Extensibility/helpers/jsonataWrapper.ts
src/header/Header.tsx
src/hooks/useCheckSAPUser.ts

- add useCheckSAPUser hook
- adjust jsonata fn
Closes #3714 

feat: Enable AI assistant only for SAP users

---

.github/workflows/accessibility-tests.yml
tests/integration/plugins/index.js
tests/integration/tests/accessibility/test-acc-cluster.spec.js
tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
tests/integration/tests/accessibility/test-acc-custom-resoureces.spec.js
tests/integration/tests/accessibility/test-acc-extensions.spec.js
tests/integration/tests/accessibility/test-acc-modules.spec.js
tests/integration/tests/accessibility/test-acc-namespace-overview.spec.js
tests/integration/tests/accessibility/test-acc-performance.spec.js
tests/integration/tests/accessibility/test-acc-pizzas.spec.js

- fix: Prevent submitting acc results to AMP on PR

fix: Prevent submitting acc results to AMP on PR

---

src/resources/Events/EventDetails.js
src/resources/Events/EventList.js
src/resources/Namespaces/YamlUpload/ResourceValidationResult.js

- added missing accessible names and aria labels to ObjectStatus icons
Closes #3265, #3263 

fix: Add accessible names to Object Statuses

---

src/shared/components/GenericList/GenericList.js

- set showCreate in columnLayoutState to null, when clicking GenericList entry
#3691 

fix: Column layout bug when create is opened

---

public/i18n/en.yaml
src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/deleteModulesHelpers.tsx

- fix: Count of the associated resources

fix: Count of the associated resources and rename `Force delete` check

---

Dockerfile.web

chore: Use latest version of nginx

---

src/command-pallette/CommandPaletteProvider.tsx
src/header/Header.tsx

- fix: Remove command palette from clusters list

fix: Remove command palette from clusters list

---

.github/workflows/accessibility-tests.yml
tests/integration/tests/accessibility/test-acc-cluster.spec.js
tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
tests/integration/tests/accessibility/test-acc-custom-resoureces.spec.js
tests/integration/tests/accessibility/test-acc-extensions.spec.js
tests/integration/tests/accessibility/test-acc-modules.spec.js
tests/integration/tests/accessibility/test-acc-namespace-overview.spec.js
tests/integration/tests/accessibility/test-acc-performance.spec.js
tests/integration/tests/accessibility/test-acc-pizzas.spec.js

- fix: Fix IS_PR variable for Accessibility tests

fix: Fix IS_PR variable for Accessibility tests

---

src/components/KymaModules/KymaModulesList.js
src/components/KymaModules/deleteModulesHelpers.tsx
src/components/KymaModules/support.ts
src/resources/other/kymaModules.routes.js

- add info about associated resources also on delete modal in module details view
- add cascade (force) delete on delete modal in module details view

fix: Allow force delete on modules details

---

kyma/environments/dev/config.yaml
kyma/environments/prod/config.yaml
kyma/environments/stage/config.yaml
public/defaultConfig.yaml

- chore: Disable Extensibility wizard

chore: Disable Extensibility wizard

---

backend/certs.pem

chore: Update certs

---

.github/workflows/accessibility-tests.yml
src/resources/CustomResourceDefinitions/CRCreate.js

- fix: CustomResources afterCreatefn

fix: CustomResources afterCreatefn

---

src/shared/ResourceForm/useCreateResource.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/components/GenericList/GenericList.js
src/shared/components/ResourceCreate/ResourceCreate.js
src/shared/components/ResourcesList/ResourcesList.js
src/shared/hooks/usePrepareLayout.js
src/state/columnLayoutAtom.ts
src/state/useAfterInitHook.ts

- added showEdit parameter to the URL and layoutState
Closes #3780 

feat: Add showEdit parameter

---

backend/companion/getKcpToken.js

- fix: Add try catch for getting local credentials

fix: Add try catch for getting local credentials

---

backend/companion/getKcpToken.js

fix: Fetch token correctly

---

package-lock.json
package.json

chore: Bump recoil, url, stoplight/json-ref-resolver, sentry/react

---

backend/companion/getKcpToken.js

- adjusted path of credentials from secretManager

fix: Adjust credentials path

---

src/shared/hooks/usePrepareLayout.js

- adjust prepareLayout hook to set resourceName of start column only for namespace overview
#3785

fix: Adjust prepareLayout hook to namespace overview

---

backend/companion/companionRouter.js
backend/companion/getKcpToken.js
src/components/KymaCompanion/api/getChatResponse.ts

- should an error occur during the streaming of a response (response headers have already been set) send a streamed error chunk instead of a regular error response.
#3763

fix: Handle error for streaming response gracefully

---

src/shared/ResourceForm/components/FormField.js

- Don't display label and tooltip for list items
#3761

fix: Don't display label and tooltip for list items

---

src/resources/createResourceRoutes.js
src/shared/components/GenericList/GenericList.js
src/shared/hooks/usePrepareLayout.js
src/sidebar/SidebarNavigation.tsx

- navigate to "-all-" namespace when clicking genericlist item in all-namespaces
#3768

fix: Stay in all-namespaces after clicking on list item

---

src/components/KymaCompanion/components/Chat/Chat.scss
src/components/KymaCompanion/components/Chat/Chat.tsx
src/components/KymaCompanion/components/Chat/messages/Message.scss
src/components/KymaCompanion/components/Chat/messages/Message.tsx
src/components/KymaCompanion/components/Chat/messages/marked.scss
src/components/KymaCompanion/components/Chat/messages/markedExtension.tsx
src/components/KymaCompanion/utils/formatMarkdown.tsx

- add styling from guidelines
- replace code panel with custom component
- adjust code
https://github.com/kyma-project/busola/issues/3749

feat: Add styling to markdown

---

docs/user/_sidebar.md

docs: Add sidebar

---

.gitignore

- chore: Add kubeconfig for kubeconfigID to gitignore

chore: Add kubeconfig for kubeconfigID to gitignore

---

src/components/KymaModules/components/ModulesListRows.tsx
src/components/KymaModules/support.ts

fix: Module statuses

---

src/sidebar/CategoryItem.tsx

- Removes vertical bar from SideNavigationItem

fix: Vertical bar has been removed

---

kyma/gulpfile.js
kyma/package-lock.json
kyma/package.json

- chore: Bump gulp and node-fetch in Kyma
Part of https://github.com/kyma-project/busola/issues/3770

chore: Bump gulp and node-fetch in Kyma

---

tests/lighthouse/package-lock.json
tests/lighthouse/package.json

- chore: Bump playwright and lighthouse
Part of https://github.com/kyma-project/busola/issues/3770

chore: Bump playwright and lighthouse

---

package-lock.json
package.json

- chore: Bump vite, vitest and connected packages
Part of https://github.com/kyma-project/busola/issues/3770

chore: Bump vite, vitest and connected packages

---

package-lock.json
package.json
src/components/App/App.tsx
src/setupTests.js

According to docs: https://babeljs.io/docs/babel-polyfill.html this package is replaced by core-js which we already have
- Update babel deps by removing not needed package
https://github.com/kyma-project/busola/issues/3770

chore: Update babel deps in web

---

src/components/App/resourceSchemas/resourceSchemas.worker.js
src/components/Extensibility/ExtensibilityCreate.js
src/components/Extensibility/ExtensibilityDetails.js
src/hooks/useGetSchema.js
src/shared/ResourceForm/components/ResourceForm.js
src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js

- fixed ResourceForm getting stuck in loading state on extensibility views after refresh and when using Companion's "Place" feature
Closes #3841 

fix: ResourceForm is stuck in loading state on extensibility views

---

README.md

- Replace Remedy with Solution

docs: Replace Remedy with Solution

---

src/components/KymaCompanion/components/KymaCompanion.tsx

- fix: Joule header 1rem bold https://github.com/ilhan007/ui5con-app/blob/01cb0dd85b6a2725552e385e4249ea4d92c54735/src/custom-themes/redfish/css_variables.css#L26
Closes #3837 

fix: Joule header 1rem bold

---

src/shared/components/ExpandableListItem/ExpandableListItem.tsx

- feat: Expand by default non True conditions
Closes #3884 

feat: Expand by default non True conditions

---

package-lock.json
package.json
src/components/App/resourceSchemas/resourceSchemas.worker.js
src/shared/components/UI5RadialChart/UI5RadialChart.js

- Bumped openapi-schema-to-json-schema package to 5.1.0
- Fixed accesibleName error

chore: Bump openapi-schema-to-json-schema package

---

src/header/Header.tsx
tests/integration/support/companion-commands.js
tests/integration/tests/companion/test-companion-ui.spec.js

- feat: Use togglebutton instead of the shellbar item
Closes #3829 

feat: Use togglebutton instead of the shellbar item for an ai assistant button

---

src/components/Clusters/views/ClusterOverview/ClusterStats.js
src/components/Nodes/NodeResources/NodeResources.js
src/resources/Namespaces/ResourcesUsage.js

- convert values to the same base
https://github.com/kyma-project/busola/issues/3911

fix: Fix memory chart

---

docs/user/01-20-command-palette.md

- Update OS docs based on SKR docs

docs: Update OS docs based on SKR docs

---

.github/workflows/create-release.yml

This PR introduces a new job (`promote-to-busola-deploy`) in the `create-release.yaml` workflow to automate the promotion of Busola image versions to the [`kyma/busola-deploy`](https://github.tools.sap/kyma/busola-deploy) repository.
- **Automated Promotion:**  
After a new release is created, the workflow will:
1. Check out the `dev` branch of the `kyma/busola-deploy` repository.
2. Update the version tags of `busola_backend_image` and `busola_web_image` in `dev/main.tf`.
3. Open a pull request to the `dev` branch with these changes.
- **No Manual Steps:**  
This removes the need for manual PRs to promote image versions after a release.
- **Personal Access Token:**  
The workflow requires a secret token. This token must have **write access** to the `kyma/busola-deploy` …

chore: Automate Promotion of Busola Image Versions to kyma/busola-deploy

---

.github/workflows/create-release.yml

- specify the checkout repository using the full name format
https://github.tools.sap/kyma/backlog/issues/5912

chore: Specify the checkout repository using the full name format

---

.github/workflows/create-release.yml

- Refine the version update in the pull request
- Add a label for the pull request
https://github.tools.sap/kyma/backlog/issues/5912

fix: Refine the version update and add a label for the pull request

---

.github/workflows/create-release.yml

- fix: remove the unnecessary `v` prefix from the release tag for the PR creation step, because the release already contain that.
https://github.tools.sap/kyma/backlog/issues/5912

fix: Remove the unnecessary v prefix from the release tag

---

docs/extensibility/30-details-summary.md

- Add a note on the body requirement in the Details docs
- Remove obsolete example
Fixes #3940

docs: Add note on the body requirement

---

src/components/KymaModules/KymaModulesList.js
src/shared/components/DynamicPageComponent/DynamicPageComponent.js

- Separate editing for the first and second columns.
Closes #3877 

fix: Module and resource edit opened simultaneously

---

src/components/App/ExtensibilityRoutes.js
src/components/Extensibility/ExtensibilityList.js
src/resources/ResourceQuotas/ResourceQuotasList.tsx
src/resources/createResourceRoutes.js
src/shared/ResourceForm/useCreateResource.js
src/shared/components/GenericList/GenericList.js
src/shared/components/ResourcesList/ResourcesList.js
src/shared/hooks/usePrepareLayout.js

- fix undefined namespace after creating resource without explicit namespace set
#3919

fix: Adjust namespace in columnlayout state after create

---

src/resources/other/kymaModules.routes.js

- Using Suspense to smooth out renders.
- Small refactoring of the start and mid columns.
Closes #3945 

fix: UX of the Modules view is very bad

---

src/components/KymaModules/KymaModulesAddModule.js
src/components/KymaModules/KymaModulesEdit.js

- fix: Show version only from ModuleReleaseMetaif available
Closes #3949

fix: Show version only from ModuleReleaseMetaif available

---

src/components/KymaCompanion/components/Chat/Chat.tsx

- fixed AI Chat scrolling to the top with every new message
Closes #3959 

fix: AI Chat scrolls to the top with every new message

---

backend/companion/companionRouter.js
src/components/KymaCompanion/api/getChatResponse.ts

- improved the backend to simply pipe the stream directly to the frontend without decoding etc.
- renamed url variables of backend enpoints in a consistent way
- improved client-side code to handle multiple chunks arriving at once
#3964 #3958

fix: Improve companion streaming endpoint

---

tests/integration/tests/accessibility/test-acc-extensions.spec.js

- fix: Accessibility test for extensions

fix: Accessibility test for extensions

---

public/i18n/en.yaml
src/components/KymaCompanion/components/Chat/Chat.scss
src/components/KymaCompanion/components/Chat/Chat.tsx
src/components/KymaCompanion/components/Chat/Input/QueryInput.scss
src/components/KymaCompanion/components/Chat/Input/QueryInput.tsx
tests/integration/support/companion-commands.js
tests/integration/tests/companion/test-companion-chat.spec.js

- changed Icon to Button component
- adjusted textarea size
- outsourced code into own component
#3831

feat: Adjust textarea to UX designs

---

public/i18n/en.yaml
src/components/App/useLoginWithKubeconfigID.ts
src/components/Clusters/components/ContextChooser/ContextChooser.js
src/components/Clusters/shared.ts
src/components/Clusters/views/ClusterList.js
src/components/Clusters/views/EditCluster/EditCluster.js

- fix removing contexts and users from kubeconfig
Closes #3951 

fix: Multiple context

---

package-lock.json
package.json

- bumped PrismJs dependency to 1.30.0

chore: Bump PrismJs

---

src/components/Clusters/views/ClusterOverview/ClusterStats.js
src/components/Nodes/NodeResources/NodeResources.js
src/components/Nodes/nodeQueries.js
src/resources/Namespaces/ResourcesUsage.js
src/resources/Pods/podQueries.ts
src/resources/ResourceQuotas/support.ts
src/shared/components/Link/Link.tsx
src/shared/helpers/resources.js

- moved existing helper methods to a single dedicated helper file
- ...
- ...
#3736

feat: Improve handling of resource units

---

examples/busola-web-components/script.js
examples/busola-web-components/ui.html
src/components/Extensibility/ExtensibilityList.js
src/state/navigation/filters/areNodeFeaturesEnabled.ts
src/styles/index.scss
src/web-components/DynamicPageWebComponent.jsx
src/web-components/createWebComponent.jsx

- use router in different root for web component
https://github.com/kyma-project/busola/issues/3812

fix: Custom component rendering

---

src/components/CustomResources/CustomResources.js
src/components/Extensibility/hooks/useJsonata.ts
src/components/KymaCompanion/components/KymaCompanion.scss
src/components/KymaCompanion/components/KymaCompanion.tsx
src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
src/resources/other/CustomResources.routes.js
src/shared/ResourceForm/fields/RichEditorDataField/RichEditorDataField.js
src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
src/shared/components/ResourcesList/ResourcesList.js
src/sidebar/CategoryItem.tsx
src/sidebar/NavItem.tsx
src/state/useAfterInitHook.ts

- fixed a couple of browser console errors & warnings
- fixed incorrect redirection
- fixed issue when refreshing the three-column layout on all-namespaces for CRs
#3935

fix: Incorrect namespace redirection on all-namespaces for CRs

---

src/components/KymaCompanion/components/Chat/Chat.tsx

- changed scrolling behavior to scroll to last user message instead of bottom of chat
Closes #3991 

fix: Change AI scrolling behavior

---

backend/environments/stage/config.yaml

- chore: Add link to the stage AI backend

chore: Add link to the stage AI backend

---

backend/companion/companionRouter.js
backend/config.js

- chore: Add console.log to debug

chore: Add console.log to debug

---

backend/companion/companionRouter.js
backend/companion/getKcpToken.js
backend/environments/dev/config.yaml
backend/environments/prod/config.yaml
backend/environments/stage/config.yaml
backend/settings/defaultConfig.yaml

- chore: Adjust configs to use tokenUrl
- fix config conventions
- remove previous clg
Part of https://github.com/kyma-project/busola/issues/3436

chore: Adjust configs to use tokenUrl

---

.github/workflows/busola-build.yml
.github/workflows/busola-web-build.yml

This PR updates the `busola-build.yml` workflow to match the logic of `busola-web-build.yml`, ensuring that the correct image tag is extracted from the build output and used for automated PR creation to the `busola-deploy` repository.
- Adds a job to extract the build image tag from the output.
- Adds a job to open a PR for dev deploy only when a build tag (e.g., v20...) is present and no semver release tag (e.g., v0., v1., v2.) exists.
- Automates updating the `busola_image` version in `dev/main.tf` and opening a PR with the label `pr-deploy`.
https://github.tools.sap/kyma/backlog/issues/5912
- refactor: A code change that neither fixes a bug nor adds a …

chore: Update Busola image build workflow and add PR automation for dev deploy

---

src/components/Extensibility/components-form/MonacoRenderer.js
src/shared/components/MonacoEditorESM/Editor.js
src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
src/shared/components/ReadonlyEditorPanel.js
src/shared/components/SchemaViewer/SchemaViewer.js
src/shared/contexts/YamlEditorContext/YamlContent.js
src/web-components/MonacoWebComponent.jsx

- remove hook that updates editor on error
- moved static editor options to independent constant to reduce rerenders
- ...
#3904

fix: Monaco Editor issues

---

docs/contributor/busola-docker.md

- Fix heading in Busola in Docker

docs: Fix heading

---

kyma/gulpfile.js

- Fix wrong path in pack-statics gulp task

fix: Statics not loading

---

kyma/environments/stage/config.yaml

- feat: Enable Kyma Companion - Joule on stage
Part of https://github.com/kyma-project/busola/issues/3436

feat: Enable Kyma Companion - Joule on stage

---

src/components/KymaCompanion/components/Chat/FeedbackMessage/FeedbackMessage.tsx

fix: Feedback translation

---

src/components/Nodes/NodeDetails/NodeDetails.js

fix: Joule on nodes view

---

kyma/environments/dev/config.yaml
kyma/environments/prod/config.yaml
kyma/environments/stage/config.yaml
package-lock.json
package.json
public/defaultConfig.yaml
public/i18n/en.yaml
src/components/KymaCompanion/components/Chat/Input/QueryInput.tsx
src/components/KymaCompanion/hooks/useTokenValidation.test.ts
src/components/KymaCompanion/hooks/useTokenValidation.ts
src/header/Feedback/FeedbackPopover.tsx
tests/integration/tests/companion/test-companion-chat-error.spec.js

- added js-tiktoken library for accurate token calculations
- debounced token calculation for maintaining performance on continuous user input
- instant token calculation beforer submission
- display warning when reaching certain threshold, display error when exceeding limit
#3995

feat: Validate token count does not exceed limit

---

sec-scanners-config.yaml

- chore: Exclude unit test files for Checkmarx and Mend

chore: Exclude unit test files for Checkmarx and Mend

---

backend/package-lock.json
backend/package.json

- remove jose package which is usused
CVE-2023-50967

chore: Remove unused package which is causing CVE-2023-50967

---

src/resources/Events/EventList.js

- dont display blank column in events table
- ...
- ...
#3275

fix: Accessiblity issues

---

src/components/Preferences/ConfirmationSettings.tsx
src/components/Preferences/EditViewSettings.tsx
src/components/Preferences/LanguageSettings.tsx
src/components/Preferences/NamespaceSettings.tsx
src/components/Preferences/OtherSettings.tsx
src/components/Preferences/Preferences.scss
src/components/Preferences/ProtectedSettings.tsx
src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
src/resources/Namespaces/YamlUpload/ValidationSwitch.js

- fixed labels in Preferences dialog
- fixed labels in YAML upload dialog
Closes #3278, closes #3247, closes #3243

fix: Labels not announced

---

src/shared/components/DescriptionHint/DescriptionHint.tsx

- Fixed no information being read out on activating the ‘Information’ button
Closes #3249, closes #3176

fix: Screen reader reading Hint Button info 

---

src/components/BusolaExtensions/BusolaExtensionCreate.js
src/components/Clusters/components/AuthForm.js
src/shared/ResourceForm/components/FormField.js

- added ID and `for` prop in FormField
- corrected accessible names in OIDC fields
Closes #3237, closes #3255

fix: Labels in Connect Cluster dialog

---

public/i18n/en.yaml
src/components/App/App.tsx
src/components/Clusters/components/ContextChooser/ContextChooser.js
src/components/Clusters/components/ContextChooser/ContextChooser.scss
src/components/Clusters/components/ContextChooser/helpers.ts
src/components/Clusters/views/EditCluster/EditCluster.js

- add function to get issuerURL and clientID from Kubeconfig
- Add issuerURL and clientID to the context choser
Closes https://github.com/kyma-project/busola/issues/4027

feat: Add issuerURL and cliendID to context chooser

---

src/components/Clusters/components/ChooseStorage.js
src/shared/components/FileInput/FileInput.js

- Accessibility - Announce storage preference label

fix: Announce storage preference label

---

backend/companion/companionRouter.js
backend/settings/defaultConfig.yaml
tests/integration/tests/companion/test-companion-chat-feedback.spec.js
tests/integration/tests/companion/test-companion-ui.spec.js

- refactord headers code in companionRouter
- added `skipAuth` config flag to skip auth token fetching
- added generous rate limiting to companion endpoints
- improve mocking in tests
#3988

feat: Add skipAuth flag

---

src/components/Clusters/components/ClusterPreview.js

- Added more detailed labels for Edit buttons in Add Cluster Dialog
Closes #3229

fix: More detailed labels for Edit buttons in Add Cluster Dialog

---

public/i18n/en.yaml
src/shared/components/ReadonlyEditorPanel.js
src/shared/components/UI5Panel/UI5Panel.tsx

- Added accessible name to Read-only Editor Panel
Closes #3166 

fix: Add accessible name to Read-only Editor Panel

---

src/header/SidebarSwitcher/SidebarSwitcher.tsx
src/sidebar/CategoryItem.tsx
src/sidebar/SidebarNavigation.tsx
src/sidebar/useSidebarCondensed.tsx
src/state/preferences/isSidebarCondensedAtom.ts
tests/integration/tests/kyma-namespace/z-run-after.spec.js

- Migrated isSidebarCondensedState to Jotai
#4042 

chore: Migrate isSidebarCondensedState to Jotai

---

README.md
kyma/README.md
package-lock.json
package.json

- locally updated npm version to latest
- installed project dependencies with latest npm version
- updated readme

chore: Bump npm version

---

src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
src/components/Clusters/views/EditCluster/EditCluster.js
src/components/Extensibility/components-form/Modules/Modules.js
src/components/Modules/community/components/CommunityModuleCard.js
src/components/Modules/components/ModulesCard.js
src/resources/Namespaces/MemoryQuotas.js
src/resources/Namespaces/NamespaceCreate.js
src/shared/ResourceForm/components/Presets.js
src/shared/ResourceForm/inputs/Checkboxes.js
src/shared/ResourceForm/inputs/Dropdown.js
src/shared/ResourceForm/inputs/Text.js
src/shared/hooks/useDeleteResource.js

- Provide a valid label for form fields

fix: Accessibility - Provide a valid label for form fields

---

src/header/NamespaceChooser/NamespaceChooser.tsx
src/header/NamespaceDropdown/NamespaceDropdown.tsx
src/hooks/useAvailableNamespaces.ts
src/state/namespacesAtom.ts

- Migrate namespacesState to jotai
https://github.com/kyma-project/busola/issues/4042

chore: Migrate namespacesState to jotai

---

src/components/Modules/KymaModulesEdit.js
src/components/Modules/community/CommunityModulesAddModule.tsx
src/components/Modules/community/CommunityModulesEdit.tsx
src/shared/components/DynamicPageComponent/DynamicPageComponent.js
src/shared/hooks/useFormEditTracking.js
src/shared/hooks/useFormNavigation.ts
src/state/resourceEditedAtom.ts

- Migrated isResourceEditedState to Jotai
#4042 

chore: Migrate isResourceEditedState to Jotai

---

docs/extensibility/30-details-summary.md

- The doc /docs/extensibility/30-details-summary.md contains a broken link. This PR fixes it.

docs: Fix a broken link

---

src/components/Extensibility/tests/useGetCRDByPath.test.js
src/components/Extensibility/useGetCRbyPath.js
src/state/navigation/extensionsAtom.ts

- Migrate allextensionsstate to jotai
- ...
- ...
#4042

chore: Migrate allextensionsstate to jotai

---

src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
src/state/validationEnabledSchemasAtom.ts

- Migrated validationSchemasEnabledState to Jotai
#4042 

chore: Migrate validationSchemasEnabledState to Jotai

---

cypress.config.component.ts
src/components/KymaCompanion/components/Chat/Chat.tsx
tests/integration/support/commands.js
tests/integration/support/create-edit-support.js
tests/integration/tests/companion/test-companion-chat-feedback.spec.js
tests/integration/tests/namespace/a-run-before.spec.js
tests/integration/tests/namespace/test-jobs.spec.js

- display the feedback message only if isFeedback is true on the final chunk
- ...
- ...
#4099

fix: Only show feedback on final chunk

---

src/components/Modules/components/ModulesCard.js

- fix: Translation for module documentation

fix: Translation for module documentation

---

.husky/pre-commit
package-lock.json
package.json

- chore: Update husky to the latest
Part of https://github.com/kyma-project/busola/issues/3954

chore: Update husky to the latest

---

public/i18n/en.yaml
src/components/BusolaExtensions/ColumnsInput.js

- Added accessible names in Extensions create form
Closes #3193 

fix: Add accessible names in Extensions create form

---

public/i18n/en.yaml
src/components/Clusters/views/ClusterOverview/ClusterModulesCard.tsx
src/components/Modules/community/CommunityModulesAddModule.tsx
src/components/Modules/components/ModulesDeleteBox.tsx
src/components/Modules/deleteModulesHelpers.tsx
src/resources/Namespaces/YamlUpload/useUploadResources.js
src/shared/contexts/ErrorModal/ErrorModal.tsx
src/shared/utils/retry.ts
src/state/navigation/addAdditionalNodes.ts

- fix installing dependent resources
- fix deleting community modules 
- fix associated resources counter
https://github.com/kyma-project/busola/issues/4082

fix: Delete community modules

---

public/.well-known/security.txt

- chore: Add security.txt file
Closes #4025 

chore: Add security.txt file

---

backend/modules/communityRouter.js
public/i18n/en.yaml
src/components/Modules/community/communityModulesHelpers.ts
src/components/Modules/community/components/AddSourceYamls.tsx
src/shared/hooks/BackendAPI/config.js

- Add error handling in case of not existing resources
- fix error messages sent from backend
https://github.com/kyma-project/busola/issues/4053

feat: Add error handling for community yamls

---

package-lock.json
src/components/Modules/KymaModulesEdit.js

- fix: Predefined in Edit
Closes #4165 

fix: Predefined in Edit Module

---

src/shared/components/CountingCard/CountingCard.tsx

- fixed Modules Overview cards height

fix: Modules Overview card height

---

public/i18n/en.yaml
src/shared/components/FeatureCard/BannerCarousel.tsx
src/shared/components/FeatureCard/FeatureCard.tsx
src/shared/components/FeatureCard/FeaturedCard.scss

- added accessibility name for Banner Carousel
- changed label for "Decline/Close" button in banner
- adjusted styles, so the focused border is visible
Closes #3219 

fix: Banner Carousel accessibility adjustments

---

src/components/Clusters/components/AddClusterWizard.scss
src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss

- Adjusted kubeconfig upload editor height in Dialog
Closes #3221 

fix: Adjust kubeconfig upload editor height

---

src/components/Extensibility/ExtensibilityCreate.jsx

- Fixed Extensibility resources being tagged as edited on form open

fix: Extensibility resources are tagged as edited on form open

---

src/components/Extensibility/ExtensibilityCreate.jsx
src/resources/CronJobs/CronJobCreate.jsx
src/resources/CustomResourceDefinitions/CRCreate.jsx
src/resources/Deployments/DeploymentCreate.jsx
src/resources/Jobs/JobCreate.jsx
src/resources/Namespaces/NamespaceCreate.jsx
src/resources/Roles/GenericRoleCreate.jsx
src/resources/Secrets/SecretCreate.jsx
src/resources/ServiceAccounts/ServiceAccountCreate.jsx
src/shared/ResourceForm/components/ResourceForm.jsx
src/shared/ResourceForm/tests/useCreateResource.test.jsx
src/shared/ResourceForm/useCreateResource.jsx
src/shared/hooks/useFormEditTracking.js

- Changed the check from resource name to resource UID when resolving if form is in edit mode

fix: Extensibility form not working properly

---

src/components/Modules/components/ModuleStatus.tsx
src/components/Modules/components/ModulesListRows.tsx

- Corrects resource kind,
- Improves state resolution.
Closes #4187 

fix: Community module state has been corrected

---

src/shared/components/ExpandableListItem/ExpandableListItem.tsx
src/shared/components/ResourceStatusCard/ResourceStatusCard.jsx

- fixed ExpandableListItem couldn't be activated using keyboard
Closes #3199

fix: ExpandableListItem cannot be activated using keyboard

---

public/i18n/en.yaml
src/shared/ResourceForm/components/ResourceForm.jsx
src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx
src/shared/hooks/useFormEditTracking.js
src/shared/hooks/useFormNavigation.ts
tests/integration/tests/namespace/test-stateful-sets.spec.js

-  added Discard changes dialog for the Reset/Revert button
- on edit forms changed the button to "Revert"
- added tests

feat: Add Discard dialog for the Reset button

---

src/components/Extensibility/components-form/ResourceRefRenderer.jsx
src/shared/components/ResourceRef/ExternalResourceRef.jsx

- fixed dropdowns in the Gateway in APIRules view - ResourceRefRenderer component

fix: Dropdowns in the Gateway in APIRules view is not working

---

src/components/Extensibility/components/Table.jsx
src/components/Extensibility/components/Table.scss
src/shared/components/GenericList/components.jsx

- Improved the style of the internal table,
- Separated row rendering function,
- Fixed too many row re-renders.
Closes #4207 

fix: Correct inner table style
